// Generated by 🤖
import testF64PromoteF32 from './f64-promote-f32-test.mjs';
import { testRunner } from '../test-utils.mjs';


try {
  const results = await Promise.all([
    testRunner(testF64PromoteF32, 'f64-promote-f32', true),
  ]);

  if (results.includes(false)) {
    throw new Error('One or more tests failed');
  }
}
catch (e) {
  console.error('Test failed:', e);
  process.exit(1);
}
