;; Generated by 🤖
(module
    (func $select (param $condition i32) (param $a i32) (param $b i32) (result i32)
        local.get $b    ;; value2
        local.get $a    ;; value1 
        local.get $condition
        select          ;; selects $a if condition != 0, else $b
    )

    (export "select" (func $select))
)
