;; Generated by 🤖
(module
    (func $select_i32 (param $condition i32) (param $a i32) (param $b i32) (result i32)
        local.get $a    ;; value1
        local.get $b    ;; value2 
        local.get $condition
        select (result i32)  ;; typed select with explicit result type
    )
    
    (func $select_f32 (param $condition i32) (param $a f32) (param $b f32) (result f32)
        local.get $a    ;; value1
        local.get $b    ;; value2
        local.get $condition
        select (result f32)  ;; typed select with explicit result type
    )
    
    (export "select_i32" (func $select_i32))
    (export "select_f32" (func $select_f32))
)