;; Generated by 🤖
(module
    (table $t 4 funcref)
    
    (func $dummy)
    
    (func $select_funcref (param $condition i32) (param $idx1 i32) (param $idx2 i32) (result funcref)
        local.get $idx1
        table.get $t
        local.get $idx2
        table.get $t
        local.get $condition
        select (result funcref)  ;; typed select with reference type
    )
    
    (elem (table $t) (i32.const 0) func $dummy)
    
    (export "select_funcref" (func $select_funcref))
)
