;; Generated by 🤖
(module
  (memory (export "memory") 1)
  
  (data (i32.const 0) "\00\00\00\00\00\00\F0\3F\00\00\00\00\00\00\00\40") ;; 1.0, 2.0
  (data (i32.const 16) "\00\00\00\00\00\00\08\40\00\00\00\00\00\00\10\40") ;; 3.0, 4.0
  (data (i32.const 32) "\00\00\00\00\00\00\F0\BF\00\00\00\00\00\00\00\C0") ;; -1.0, -2.0
  (data (i32.const 48) "\9A\99\99\99\99\99\01\40\CD\CC\CC\CC\CC\CC\CC\BF") ;; 2.2, -0.1

  (func (export "f64x2_ceil_test") (result f64)
    i32.const 48
    v128.load
    f64x2.ceil
    f64x2.extract_lane 0)

  (func (export "f64x2_floor_test") (result f64)
    i32.const 48
    v128.load
    f64x2.floor
    f64x2.extract_lane 0)

  (func (export "f64x2_trunc_test") (result f64)
    i32.const 48
    v128.load
    f64x2.trunc
    f64x2.extract_lane 0)

  (func (export "f64x2_nearest_test") (result f64)
    i32.const 48
    v128.load
    f64x2.nearest
    f64x2.extract_lane 0)

  (func (export "f64x2_abs_test") (result f64)
    i32.const 32
    v128.load
    f64x2.abs
    f64x2.extract_lane 0)

  (func (export "f64x2_neg_test") (result f64)
    i32.const 0
    v128.load
    f64x2.neg
    f64x2.extract_lane 0)

  (func (export "f64x2_sqrt_test") (result f64)
    i32.const 0
    v128.load
    f64x2.sqrt
    f64x2.extract_lane 0)

  (func (export "f64x2_add_test") (result f64)
    i32.const 0
    v128.load
    i32.const 16
    v128.load
    f64x2.add
    f64x2.extract_lane 0)

  (func (export "f64x2_sub_test") (result f64)
    i32.const 16
    v128.load
    i32.const 0
    v128.load
    f64x2.sub
    f64x2.extract_lane 0)

  (func (export "f64x2_mul_test") (result f64)
    i32.const 0
    v128.load
    i32.const 16
    v128.load
    f64x2.mul
    f64x2.extract_lane 0)

  (func (export "f64x2_div_test") (result f64)
    i32.const 16
    v128.load
    i32.const 0
    v128.load
    f64x2.div
    f64x2.extract_lane 0)

  (func (export "f64x2_min_test") (result f64)
    i32.const 0
    v128.load
    i32.const 32
    v128.load
    f64x2.min
    f64x2.extract_lane 0)

  (func (export "f64x2_max_test") (result f64)
    i32.const 0
    v128.load
    i32.const 32
    v128.load
    f64x2.max
    f64x2.extract_lane 0)

  (func (export "f64x2_pmin_test") (result f64)
    i32.const 0
    v128.load
    i32.const 32
    v128.load
    f64x2.pmin
    f64x2.extract_lane 0)

  (func (export "f64x2_pmax_test") (result f64)
    i32.const 0
    v128.load
    i32.const 32
    v128.load
    f64x2.pmax
    f64x2.extract_lane 0)
)
