import testSIMDMemory from './simd-memory-test.mjs';
import { testRunner } from '../test-utils.mjs';

try {
    const result = await testRunner(testSIMDMemory, 'simd-memory', true);
    if (!result) {
        throw new Error('SIMD memory test failed');
    }
}
catch (error) {
    console.error('Error during SIMD memory test:', error);
    process.exit(1);
}
// Generated by 🤖
