import testI64ReinterpretF64 from './i64-reinterpret-f64-test.mjs';

// Generated by 🤖
async function runTests() {
  console.log('Running f64.reinterpret_i64 tests...');
  const debug = process.argv.includes('--debug');
  const result = await testI64ReinterpretF64(debug);
  
  // Exit with appropriate code
  process.exit(result ? 0 : 1);
}

runTests().catch(error => {
  console.error('Error running tests:', error);
  process.exit(1);
});