;; filepath: /Users/martinericsson/dev/fes-compiler/tests/simd-const/simd-const-error.wat
(module
  (func (export "v128_const_too_few") (result i32)
    ;; Missing some values (only 15 instead of 16)
    v128.const i8x16 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    
    ;; Extract the first lane as an unsigned int
    i8x16.extract_lane_u 0
  )

  (func (export "v128_const_too_many") (result i32)
    ;; Too many values (17 instead of 16)
    v128.const i8x16 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
    
    ;; Extract the 5th lane
    i8x16.extract_lane_u 4
  )
) ;; Generated by 🤖
