;; Generated by 🤖
(module
  (memory 1)
  (export "memory" (memory 0))

  ;; i32x4.trunc_sat_f32x4_s - Truncate f32x4 to i32x4 with signed saturation
  (func $i32x4_trunc_sat_f32x4_s_test (result i32)
    (local $result v128)
    v128.const f32x4 1.5 -1.5 1000000000.0 -1000000000.0
    i32x4.trunc_sat_f32x4_s
    local.set $result
    local.get $result
    i32x4.extract_lane 0
  )
  (export "i32x4_trunc_sat_f32x4_s_test" (func $i32x4_trunc_sat_f32x4_s_test))

  ;; i32x4.trunc_sat_f32x4_u - Truncate f32x4 to i32x4 with unsigned saturation
  (func $i32x4_trunc_sat_f32x4_u_test (result i32)
    (local $result v128)
    v128.const f32x4 2.7 -1.5 1000000000.0 -1000000000.0
    i32x4.trunc_sat_f32x4_u
    local.set $result
    local.get $result
    i32x4.extract_lane 0
  )
  (export "i32x4_trunc_sat_f32x4_u_test" (func $i32x4_trunc_sat_f32x4_u_test))

  ;; f32x4.convert_i32x4_s - Convert i32x4 to f32x4 (signed)
  (func $f32x4_convert_i32x4_s_test (result f32)
    (local $result v128)
    v128.const i32x4 42 -42 0 100
    f32x4.convert_i32x4_s
    local.set $result
    local.get $result
    f32x4.extract_lane 0
  )
  (export "f32x4_convert_i32x4_s_test" (func $f32x4_convert_i32x4_s_test))

  ;; f32x4.convert_i32x4_u - Convert i32x4 to f32x4 (unsigned)
  (func $f32x4_convert_i32x4_u_test (result f32)
    (local $result v128)
    v128.const i32x4 42 -1 0 100
    f32x4.convert_i32x4_u
    local.set $result
    local.get $result
    f32x4.extract_lane 0
  )
  (export "f32x4_convert_i32x4_u_test" (func $f32x4_convert_i32x4_u_test))

  ;; i32x4.trunc_sat_f64x2_s_zero - Truncate two f64 lanes to i32x4 with signed saturation and zero upper lanes
  (func $i32x4_trunc_sat_f64x2_s_zero_test (result i32)
    (local $result v128)
    v128.const f64x2 123.45 -123.45
    i32x4.trunc_sat_f64x2_s_zero
    local.set $result
    local.get $result
    i32x4.extract_lane 0
  )
  (export "i32x4_trunc_sat_f64x2_s_zero_test" (func $i32x4_trunc_sat_f64x2_s_zero_test))

  ;; i32x4.trunc_sat_f64x2_u_zero - Truncate two f64 lanes to i32x4 with unsigned saturation and zero upper lanes
  (func $i32x4_trunc_sat_f64x2_u_zero_test (result i32)
    (local $result v128)
    v128.const f64x2 234.56 -234.56
    i32x4.trunc_sat_f64x2_u_zero
    local.set $result
    local.get $result
    i32x4.extract_lane 0
  )
  (export "i32x4_trunc_sat_f64x2_u_zero_test" (func $i32x4_trunc_sat_f64x2_u_zero_test))

  ;; f64x2.convert_low_i32x4_s - Convert low two i32 lanes to f64x2 (signed)
  (func $f64x2_convert_low_i32x4_s_test (result f64)
    (local $result v128)
    v128.const i32x4 -42 84 100 200
    f64x2.convert_low_i32x4_s
    local.set $result
    local.get $result
    f64x2.extract_lane 0
  )
  (export "f64x2_convert_low_i32x4_s_test" (func $f64x2_convert_low_i32x4_s_test))

  ;; f64x2.convert_low_i32x4_u - Convert low two i32 lanes to f64x2 (unsigned)
  (func $f64x2_convert_low_i32x4_u_test (result f64)
    (local $result v128)
    v128.const i32x4 42 84 100 200
    f64x2.convert_low_i32x4_u
    local.set $result
    local.get $result
    f64x2.extract_lane 0
  )
  (export "f64x2_convert_low_i32x4_u_test" (func $f64x2_convert_low_i32x4_u_test))

  ;; f32x4.demote_f64x2_zero - Demote two f64 lanes to f32x4 with zero upper lanes
  (func $f32x4_demote_f64x2_zero_test (result f32)
    (local $result v128)
    v128.const f64x2 12345.6789 -12345.6789
    f32x4.demote_f64x2_zero
    local.set $result
    local.get $result
    f32x4.extract_lane 0
  )
  (export "f32x4_demote_f64x2_zero_test" (func $f32x4_demote_f64x2_zero_test))

  ;; f64x2.promote_low_f32x4 - Promote low two f32 lanes to f64x2
  (func $f64x2_promote_low_f32x4_test (result f64)
    (local $result v128)
    v128.const f32x4 42.5 -42.5 100.0 200.0
    f64x2.promote_low_f32x4
    local.set $result
    local.get $result
    f64x2.extract_lane 0
  )
  (export "f64x2_promote_low_f32x4_test" (func $f64x2_promote_low_f32x4_test))
)
