import path from "node:path";
import { fileURLToPath } from "node:url";
import { compileToWASM } from "../src/compile/compile.mjs";
import { parseWAT } from "../src/parser/parser.mjs";
import { readWATFile } from "../src/test-utils/file-utils.mjs";

// parseWAT and compileToWASM are imported above and also used by expectCompileError

// Generated by 🤖
// Custom replacer for JSON.stringify that handles BigInt values
const bigIntReplacer = (key, value) => {
	// Convert BigInt to string representation for serialization
	if (typeof value === "bigint") {
		return `${value.toString()}n`;
	}
	return value;
};

const logger = (debug = false) => {
	if (debug) {
		return (msg, level = "INFO") => {
			if (level !== "INFO") {
				console.error(msg);
			} else {
				console.log(msg);
			}
		};
	}
	return (_) => _;
};

const readTestData = async (filename, debug = false) => {
	const log = logger(debug);
	// Get directory name for current file
	const __filename = fileURLToPath(import.meta.url);
	const __dirname = path.dirname(__filename);

	// Path to WAT file
	const watFilePath = path.join(__dirname, filename);

	// Read the WAT file
	try {
		const watContent = await readWATFile(watFilePath);

		if (debug) console.log("Parsing WAT code...");
		const ast = parseWAT(watContent);

		if (debug) console.log("AST created:");
		if (debug) console.log(JSON.stringify(ast, bigIntReplacer, 2));

		if (debug) console.log("Compiling to WASM...");
		const wasmBinary = compileToWASM(ast);

		if (debug) console.log(`WASM binary created: ${wasmBinary.length} bytes`);

		const wasmBuffer = new Uint8Array(wasmBinary);

		// Validate the emitted bytes using the runtime
		if (typeof WebAssembly !== "undefined" && WebAssembly.validate) {
			const valid = WebAssembly.validate(wasmBuffer);
			if (!valid) {
				log({
					message: `⚠️  WebAssembly.validate returned false for ${filename}`,
					debug,
					level: "WARN",
				});
			}
		}

		return { wasmBuffer, ast };
	} catch (e) {
		log({
			message: `❌ Error reading WAT file: ${e.message}`,
			debug,
			level: "ERROR",
		});
		throw e;
	}
};

// Asserts that two Uint8Arrays produce the same hex string.
// expectedHex is a hex string like "0061736d01000000".
const assertBytesEqual = (actual, expectedHex) => {
	const actualHex = Array.from(actual)
		.map((b) => b.toString(16).padStart(2, "0"))
		.join("");
	if (actualHex !== expectedHex) {
		throw new Error(
			`Byte mismatch.\n  expected: ${expectedHex}\n  actual:   ${actualHex}`,
		);
	}
};

// Asserts that compiling the given WAT string throws an error matching messageRegex.
const expectCompileError = async (wat, messageRegex) => {
	let threw = false;
	try {
		const ast = parseWAT(wat);
		compileToWASM(ast);
	} catch (e) {
		threw = true;
		if (messageRegex && !messageRegex.test(e.message)) {
			throw new Error(
				`Expected error matching ${messageRegex} but got: ${e.message}`,
			);
		}
	}
	if (!threw) {
		throw new Error(
			`Expected a compile error${messageRegex ? ` matching ${messageRegex}` : ""} but none was thrown`,
		);
	}
};

const testRunner = async (testFunction, label = "test", debug = false) => {
	try {
		const result = await testFunction(debug);
		if (result) {
			console.log(`🆗 ${label} tests passed!`);
		} else {
			console.error(`❌ ${label} tests failed.`);
		}
		return result;
	} catch (error) {
		console.error(`❌ Error testing ${label}:`, error);
		return false;
	}
};

const dumpWASM = (wasmBuffer) => {
	const hexString = Array.from(wasmBuffer)
		.map((byte) => byte.toString(16).padStart(2, "0"))
		.join(" ");
	console.log(`WASM Binary: ${hexString}`);
};

export { readTestData, testRunner, logger, dumpWASM, assertBytesEqual, expectCompileError };
