(module
  ;; Imported memory to verify import section includes memory entries
  (import "env" "mem" (memory 1 2))

  (func $get (result i32)
    memory.size ;; returns current memory size in pages (should be 1)
  )

  (export "get" (func $get))
) ;; Generated by 🤖