;; Generated by 🤖
(module
  ;; Define a table to store function references
  (table $tbl 1 funcref)

  ;; Function to test if a null reference is null (should return 1)
  (func $test_null (result i32)
    ref.null func
    ref.is_null)

  ;; Function to test if a function reference is null (should return 0)
  (func $test_func_ref (result i32)
    ref.func $test_null
    ref.is_null)

  ;; Exports for testing
  (export "test_null" (func $test_null))
  (export "test_func_ref" (func $test_func_ref)))