import simdExtractLaneI16x8Test from './simd-extract-lane-i16x8-test.mjs';
import { testRunner } from '../test-utils.mjs';
try {
    const results = await Promise.all([
        testRunner(simdExtractLaneI16x8Test, 'simd-extract-lane-i16x8', true),
    ]);
    if (results.includes(false)) {
        throw new Error('One or more tests failed');
    }
} catch (e) {
    console.error('Test failed:', e);
    process.exit(1);
}
// Generated by 🤖
