// Generated by 🤖
import { testRunner } from '../test-utils.mjs';
import testTableFill from './table-fill-test.mjs';

try {
    const results = await Promise.all([
        testRunner(testTableFill, 'table-fill', true),
    ]);
    if (results.includes(false)) {
        throw new Error('One or more tests failed');
    }
    console.log('✅ All table-fill tests passed!');
} catch (e) {
    console.error('Test failed:', e);
    process.exit(1);
}
