;; Generated by 🤖
(module
  ;; Type for functions that return i32
  (type $fn_i32 (func (result i32)))
  
  ;; Define table with min size 4
  (table $tbl 4 4 funcref)
  
  ;; Define functions that will be referenced
  (func $f1 (type $fn_i32)
    i32.const 42)
    
  (func $f2 (type $fn_i32)
    i32.const 43)
    
  (func $f3 (type $fn_i32)
    i32.const 44)
  
  ;; Function to fill table entries with a reference value
  (func $fill_table (param $start i32) (param $val funcref) (param $len i32)
    local.get $start  ;; Start index
    local.get $val    ;; Value to fill with
    local.get $len    ;; Number of elements to fill
    table.fill 0)     ;; Fill in table 0
  
  ;; Function to get element from table and call it
  (func $get_func (param i32) (result i32)
    local.get 0      ;; Get index
    call_indirect (type $fn_i32))  ;; Call function through table
  
  ;; Exports for testing
  (export "fill_table" (func $fill_table))
  (export "get_func" (func $get_func))
  (export "f1" (func $f1))
  (export "f2" (func $f2))
  (export "f3" (func $f3))
  (export "tbl" (table $tbl)))