import { testRunner } from "../test-utils.mjs";
import testSharedMemory from "./memory-shared-test.mjs";
import testSharedMemoryFlags from "./memory-shared-flags-test.mjs"; // Generated by 🤖
import testComprehensiveSharedMemory from "./memory-comprehensive-test.mjs"; // Generated by 🤖

try {
    const results = await Promise.all([
      testRunner(testSharedMemory, 'shared-memory', true),
      testRunner(testSharedMemoryFlags, 'shared-memory-flags', true), // Generated by 🤖
      testRunner(testComprehensiveSharedMemory, 'comprehensive-shared-memory', true), // Generated by 🤖
    ]);
    if (results.includes(false)) {
      throw new Error('One or more tests failed');
    }
  }
  catch (e) {
    console.error('❌ Test failed:', e);
    process.exit(1);
  }