;; Generated by 🤖
(module
    ;; Define table with min size 2, max size 4, holding function references
    (table 2 4 funcref)
    
    ;; Define functions that will be referenced by the table
    (func $f1 (result i32)
        i32.const 42)
        
    (func $f2 (result i32)
        i32.const 43)

    ;; Add function to get table size
    (func $tableSize (result i32)
        table.size 0
    )
    
    ;; Initialize table elements
    (elem (i32.const 0) $f1 $f2)

     ;; Function to get element from table
    (func $get_func (param i32) (result funcref)
        local.get 0    ;; Get index from parameter
        table.get 0    ;; Get element from table 0
    )  
    
    ;; Function to set element in table
    (func $set_func (param i32) (param funcref)
        local.get 0    ;; Get index from parameter
        local.get 1    ;; Get function reference from parameter
        table.set 0    ;; Set element at index in table 0
    )
    
    ;; Export the table
    (export "tbl" (table 0))
    
    ;; Export functions for testing
    (export "f1" (func $f1))
    (export "f2" (func $f2))
    (export "tableSize" (func $tableSize))
    (export "get_func" (func $get_func))
    (export "set_func" (func $set_func))
)