// Generated by 🤖
import { atEnd, getToken, peekToken, skipToken } from "./tape.mjs";

export function parseImport() {
	let moduleName = null;
	let fieldName = null;
	let kind = null;
	let name = null;
	const params = [];
	const results = [];
	let min = 0;
	let max = null;
	let shared = false;

	// Parse module name (first string)
	if (!atEnd() && peekToken().startsWith('"') && peekToken().endsWith('"')) {
		const token = getToken();
		moduleName = token.substring(1, token.length - 1); // Remove quotes
	}

	// Parse field name (second string)
	if (!atEnd() && peekToken().startsWith('"') && peekToken().endsWith('"')) {
		const token = getToken();
		fieldName = token.substring(1, token.length - 1); // Remove quotes
	}

	// Parse the imported entity (func, global, memory, or table)
	if (!atEnd() && peekToken() === "(") {
		skipToken(); // Skip opening paren

		if (!atEnd()) {
			kind = getToken(); // Get the kind (func, global, memory, table)

			// Handle function import
			if (kind === "func") {
				// Check for function name
				if (!atEnd() && peekToken().startsWith("$")) {
					name = getToken();
				}

				// Parse parameters and results
				while (!atEnd() && peekToken() !== ")") {
					if (peekToken() === "(") {
						skipToken(); // Skip opening paren

						if (!atEnd()) {
							const keyword = getToken();

							if (keyword === "param") {
								// Parse parameters
								while (!atEnd() && peekToken() !== ")") {
									if (peekToken().startsWith("$")) {
										// Skip parameter name, we only care about types for imports
										skipToken();
									} else {
										// Add parameter type
										params.push(getToken());
									}
								}
							} else if (keyword === "result") {
								// Parse results
								while (!atEnd() && peekToken() !== ")") {
									results.push(getToken());
								}
							}

							// Skip closing paren
							if (!atEnd() && peekToken() === ")") {
								skipToken();
							}
						}
					} else {
						skipToken(); // Skip other tokens
					}
				}
			} else if (kind === "memory") {
				// Parse memory import: (memory <min> [<max>] [shared])
				// Parse minimum size (required)
				if (!atEnd() && /^\d+$/.test(peekToken())) {
					min = Number.parseInt(getToken(), 10);

					// Parse maximum size (optional)
					if (!atEnd() && /^\d+$/.test(peekToken())) {
						max = Number.parseInt(getToken(), 10);
					}
				}

				// Check for shared attribute
				if (!atEnd() && peekToken() === "shared") {
					getToken(); // consume 'shared' token
					shared = true;
				}

				// Skip any remaining tokens until closing paren
				while (!atEnd() && peekToken() !== ")") {
					skipToken();
				}
			} else {
				// For other import types (global, table)
				// Skip all tokens until closing paren
				while (!atEnd() && peekToken() !== ")") {
					skipToken();
				}
			}

			// Skip closing paren of the entity type
			if (!atEnd() && peekToken() === ")") {
				skipToken();
			}
		}
	}

	const importDecl = {
		module: moduleName,
		field: fieldName,
		kind: kind,
	};

	if (kind === "func") {
		importDecl.name = name;
		importDecl.params = params;
		importDecl.results = results; // Restored by 🤖
	} else if (kind === "memory") {
		importDecl.min = min;
		importDecl.max = max;
		importDecl.shared = shared;
		importDecl.name = fieldName; // Generated by 🤖
	}

	return importDecl;
}
