// Generated by 🤖
import { getCurrentCursor, atEnd, peekToken, skipToken, getToken } from './tape.mjs';
import { createError } from './parse-util.mjs';

export function parseType(passedKeywordLoc = null) {
    let mainLoc = passedKeywordLoc;
    let firstConsumedTokenLoc = null;

    let name = null, nameLoc = null;
    let funcKeywordLoc = null;
    let signatureParenLoc = null; // For the '(' of '(func ...)'
    const params = []; // Array of { value: string, loc: {line, col}, name?: string, nameLoc? }
    const results = []; // Array of { value: string, loc: {line, col} }

    let nextToken = peekToken();
    if (!mainLoc && nextToken) mainLoc = { line: nextToken.line, column: nextToken.column };
    if (!firstConsumedTokenLoc && nextToken) firstConsumedTokenLoc = { line: nextToken.line, column: nextToken.column };
    
    // Check for type name (e.g., $t0)
    if (nextToken && nextToken.value.startsWith('$')) {
        const nameToken = getToken();
        name = nameToken.value;
        nameLoc = { line: nameToken.line, column: nameToken.column };
        nextToken = peekToken();
    }

    // Parse the function signature (func (param ...) (result ...))
    if (nextToken && nextToken.value === '(') {
        signatureParenLoc = { line: nextToken.line, column: nextToken.column };
        skipToken(); // Skip opening paren '(' for func signature

        const funcToken = getToken();
        if (!funcToken || funcToken.value !== 'func') {
            throw createError(`Expected 'func' keyword in type definition, got '${funcToken ? funcToken.value : "EOF"}'.`, 
                              signatureParenLoc.line, signatureParenLoc.column + 1);
        }
        funcKeywordLoc = { line: funcToken.line, column: funcToken.column };
        nextToken = peekToken();

        // Parse parameters and results
        while (nextToken && nextToken.value !== ')') {
            if (nextToken.value === '(') {
                const sectionParenLoc = { line: nextToken.line, column: nextToken.column };
                skipToken(); // Skip opening paren '(' for param/result block
                
                const keywordToken = getToken(); // 'param' or 'result'
                if (!keywordToken) throw createError("Expected 'param' or 'result' keyword.", sectionParenLoc.line, sectionParenLoc.column + 1);
                const keyword = keywordToken.value;
                const keywordLoc = { line: keywordToken.line, column: keywordToken.column };

                const targetArray = keyword === 'param' ? params : (keyword === 'result' ? results : null);
                if (!targetArray) {
                    throw createError(`Unexpected section '${keyword}' in func signature. Expected 'param' or 'result'.`, keywordLoc.line, keywordLoc.column);
                }

                let itemToken = peekToken();
                while (itemToken && itemToken.value !== ')') {
                    let paramName = null, paramNameLoc = null;
                    // Handle named parameters e.g. (param $p i32)
                    if (keyword === 'param' && itemToken.value.startsWith('$')) {
                        const pNameToken = getToken();
                        paramName = pNameToken.value;
                        paramNameLoc = { line: pNameToken.line, column: pNameToken.column };
                        itemToken = peekToken(); // Next token is the type
                        if (!itemToken || itemToken.value === ')') throw createError(`Expected type for named parameter '${paramName}'.`, paramNameLoc.line, paramNameLoc.column + paramName.length);
                    }
                    
                    const typeValToken = getToken();
                    const typeInfo = { value: typeValToken.value, loc: { line: typeValToken.line, column: typeValToken.column }};
                    if (paramName) {
                        typeInfo.name = paramName;
                        typeInfo.nameLoc = paramNameLoc;
                    }
                    targetArray.push(typeInfo);
                    itemToken = peekToken();
                }

                if (!itemToken) throw createError(`Expected ')' to close '${keyword}' block, but found EOF.`, keywordLoc.line, keywordLoc.column);
                skipToken(); // Skip closing paren ')' of param/result block
            } else {
                throw createError(`Unexpected token '${nextToken.value}' in func signature. Expected '('.`, nextToken.line, nextToken.column);
            }
            nextToken = peekToken();
        }

        if (!nextToken) throw createError("Expected ')' to close func signature, but found EOF.", funcKeywordLoc.line, funcKeywordLoc.column + 4);
        skipToken(); // Skip closing paren ')' of func signature
    } else {
        throw createError(`Expected '(' to start 'func' signature in type definition, got '${nextToken ? nextToken.value : "EOF"}'.`,
                          nameLoc ? nameLoc.line : (mainLoc ? mainLoc.line : 0), 
                          nameLoc ? nameLoc.column + (name ? name.length : 0) : (mainLoc ? mainLoc.column : 0));
    }

    if (!mainLoc) mainLoc = passedKeywordLoc || firstConsumedTokenLoc || getCurrentCursor();

    return { 
        node_type: 'type_definition',
        name, 
        nameLoc,
        funcKeywordLoc, // loc of 'func'
        signatureParenLoc, // loc of '(' for (func ...)
        params,  // Array of { value, loc, name?, nameLoc? }
        results, // Array of { value, loc }
        loc: mainLoc // Overall loc for the type definition (ideally loc of 'type' keyword)
    };
}