// Generated by 🤖
import { atEnd, getCurrentCursor, peekToken, skipToken, getToken } from './tape.mjs';
import { createError } from './parse-util.mjs';

export function parseGlobal(passedKeywordLoc = null) {
    let mainLoc = passedKeywordLoc || getCurrentCursor(); // Loc of first token $name, type, or ( for mut/import

    let name = null, nameLoc = null;
    let type = null, typeLoc = null;
    let mutable = false, mutKeywordLoc = null, mutParenLoc = null;
    let init = null; // Will store { type, value, loc, valueLoc }
    let importModule = null, importModuleLoc = null;
    let importName = null, importNameLoc = null;
    let importKeywordLoc = null, importParenLoc = null;

    let nextToken = peekToken();
    if (!mainLoc && nextToken) mainLoc = { line: nextToken.line, column: nextToken.column };


    // Check for global name (e.g., $g1)
    if (nextToken && nextToken.value.startsWith('$')) {
        const nameToken = getToken();
        name = nameToken.value;
        nameLoc = { line: nameToken.line, column: nameToken.column };
        nextToken = peekToken();
    }

    // Check for mutability (mut type) or import (import "mod" "name")
    if (nextToken && nextToken.value === '(') {
        const parenLoc = { line: nextToken.line, column: nextToken.column };
        skipToken(); // Skip opening paren '('
        
        const keywordToken = getToken(); // 'mut' or 'import'
        if (!keywordToken) throw createError("Expected 'mut' or 'import' after '(' in global declaration.", parenLoc.line, parenLoc.column + 1);

        if (keywordToken.value === 'mut') {
            mutParenLoc = parenLoc;
            mutable = true;
            mutKeywordLoc = { line: keywordToken.line, column: keywordToken.column };
            
            const typeToken = getToken();
            if (!typeToken) throw createError("Expected type after '(mut'", mutKeywordLoc.line, mutKeywordLoc.column + 3);
            type = typeToken.value; // TODO: Validate type?
            typeLoc = { line: typeToken.line, column: typeToken.column };

            const closingParen = getToken();
            if (!closingParen || closingParen.value !== ')') {
                throw createError("Expected ')' after type in '(mut type)' declaration.", typeLoc.line, typeLoc.column + type.length);
            }
        } else if (keywordToken.value === 'import') {
            importParenLoc = parenLoc;
            importKeywordLoc = { line: keywordToken.line, column: keywordToken.column };

            const moduleToken = getToken();
            if (!moduleToken || !moduleToken.value.startsWith('"') || !moduleToken.value.endsWith('"')) {
                throw createError("Expected module name string for global import.", importKeywordLoc.line, importKeywordLoc.column + 6);
            }
            importModule = moduleToken.value.substring(1, moduleToken.value.length - 1);
            importModuleLoc = { line: moduleToken.line, column: moduleToken.column };

            const nameToken = getToken();
            if (!nameToken || !nameToken.value.startsWith('"') || !nameToken.value.endsWith('"')) {
                throw createError("Expected field name string for global import.", importModuleLoc.line, importModuleLoc.column + importModule.length + 2);
            }
            importName = nameToken.value.substring(1, nameToken.value.length - 1);
            importNameLoc = { line: nameToken.line, column: nameToken.column };
            
            const closingParen = getToken();
            if (!closingParen || closingParen.value !== ')') {
                throw createError("Expected ')' to close global import declaration.", importNameLoc.line, importNameLoc.column + importName.length + 2);
            }
        } else {
            throw createError(`Unexpected keyword '${keywordToken.value}' after '(' in global. Expected 'mut' or 'import'.`, keywordToken.line, keywordToken.column);
        }
        nextToken = peekToken();
    }

    // If type hasn't been parsed yet (i.e., not via (mut type) or if it's an imported global that also needs its type declared)
    if (!type && nextToken) {
        // For imported globals, the type is declared *after* the (import ...) block
        // For regular globals, if not (mut T), then T is next.
        const typeToken = getToken();
        type = typeToken.value; // TODO: Validate type?
        typeLoc = { line: typeToken.line, column: typeToken.column };
        nextToken = peekToken();
    }
    
    if (!type) { // Type must be defined by now
         throw createError(`Global variable ${name ? name : ""} must have a type.`, 
                           nameLoc ? nameLoc.line : (mainLoc ? mainLoc.line : 0), 
                           nameLoc ? nameLoc.column + (name? name.length : 0) : (mainLoc ? mainLoc.column : 0) );
    }


    // Parse initialization expression if not an import
    if (!importModule && nextToken && nextToken.value === '(') {
        const initExprLoc = { line: nextToken.line, column: nextToken.column };
        skipToken(); // Skip opening paren '(' of init expression
        
        const instrToken = getToken();
        if (!instrToken) throw createError("Expected instruction for global initializer.", initExprLoc.line, initExprLoc.column + 1);
        
        const instrOpcode = instrToken.value;
        const instrLoc = { line: instrToken.line, column: instrToken.column };
        let value, valueLoc;

        const supportedConstInstr = ['i32.const', 'i64.const', 'f32.const', 'f64.const'];
        if (supportedConstInstr.includes(instrOpcode)) {
            const valueToken = getToken();
            if (!valueToken) throw createError(`Expected value for ${instrOpcode}.`, instrLoc.line, instrLoc.column + instrOpcode.length);
            
            valueLoc = { line: valueToken.line, column: valueToken.column };
            if (instrOpcode.startsWith('i')) {
                value = BigInt(valueToken.value); // parseInt might lose precision for i64
            } else {
                value = Number.parseFloat(valueToken.value);
            }
            init = { type: instrOpcode, value: valueToken.value, loc: instrLoc, valueLoc, expressionLoc: initExprLoc };
        } else {
            // WebAssembly MVP allows only const expressions. For simplicity, only direct const instructions supported here.
            // More complex const expressions (e.g., global.get) would require a more robust expression parser.
            throw createError(`Unsupported instruction '${instrOpcode}' for global initializer. Only const instructions are allowed.`, instrLoc.line, instrLoc.column);
        }

        const closingParen = getToken();
        if (!closingParen || closingParen.value !== ')') {
            throw createError(`Expected ')' to close initializer expression but got ${closingParen ? closingParen.value : "EOF"}.`, 
                              valueLoc ? valueLoc.line : instrLoc.line, 
                              valueLoc ? valueLoc.column + value.toString().length : instrLoc.column + instrOpcode.length);
        }
    }
    
    if (!mainLoc && nameLoc) mainLoc = nameLoc; // Fallback if passedKeywordLoc was null and no other token consumed first
    else if (!mainLoc && typeLoc) mainLoc = typeLoc;

    return {
        node_type: 'global_variable', // Explicit type for this AST node
        name,
        nameLoc,
        type,
        typeLoc,
        mutable,
        mutKeywordLoc,
        mutParenLoc,
        init, // This is the init expression AST node { type, value, loc, valueLoc, expressionLoc }
        importInfo: importModule && importName ? { 
            module: importModule, moduleLoc: importModuleLoc, 
            field: importName, fieldLoc: importNameLoc, 
            keywordLoc: importKeywordLoc, parenLoc: importParenLoc 
        } : null,
        loc: mainLoc
    };
}