import {
	decodeWatStringToBytes,
	stripWatStringQuotes,
} from "../wat-string.mjs";

export function parseData(tape) {
	const { atEnd, getToken, peekToken, skipToken } = tape;
	// Parse data section: (data (i32.const <offset>) "<bytes>") or passive (data $name "<bytes>")
	let offset = 0;
	let bytes = "";
	let id = null;
	let isPassive = true;

	// Check for data segment identifier
	if (!atEnd() && peekToken().startsWith("$")) {
		id = getToken();
	}

	// Parse offset expression or continue with passive segment
	if (!atEnd() && peekToken() === "(") {
		skipToken(); // Skip opening paren
		isPassive = false; // If we have offset expression, it's an active segment

		if (!atEnd() && peekToken() === "i32.const") {
			skipToken(); // Skip i32.const

			if (!atEnd() && /^-?\d+$/.test(peekToken())) {
				offset = Number.parseInt(getToken(), 10);
			}

			// Skip closing paren of the offset expression
			if (!atEnd() && peekToken() === ")") {
				skipToken();
			}
		} else {
			// Skip unknown expression
			while (!atEnd() && peekToken() !== ")") {
				skipToken();
			}
			skipToken(); // Skip closing paren
		}
	}

	// Parse bytes strings (can be multiple string literals in one data segment)
	const rawStrings = [];
	const processedBytes = [];

	while (!atEnd() && peekToken().startsWith('"') && peekToken().endsWith('"')) {
		const rawString = stripWatStringQuotes(peekToken());

		rawStrings.push(rawString);
		processedBytes.push(...decodeWatStringToBytes(rawString));

		skipToken();
	}

	// Store the processed bytes directly in a format our compiler can use
	bytes = {
		raw: rawStrings.join(""),
		processedBytes: processedBytes,
	}; // Generated by 🤖

	return { id, offset, bytes, isPassive };
}
