// Generated by 🤖
import { atEnd, peekToken, getToken, getCurrentCursor, skipToken } from './tape.mjs';
import { createError } from './parse-util.mjs';

export function parseTable(passedKeywordLoc = null) {
    let mainLoc = passedKeywordLoc;
    let firstConsumedTokenLoc = null;

    let id = null, idLoc = null;
    let min = 0, minLoc = null; // Default min size
    let max = null, maxLoc = null;
    let tableType = 'funcref', typeLoc = null;  // Default type is funcref

    let nextToken = peekToken();
    if (!mainLoc && nextToken) mainLoc = { line: nextToken.line, column: nextToken.column };
    if (!firstConsumedTokenLoc && nextToken) firstConsumedTokenLoc = { line: nextToken.line, column: nextToken.column };

    // Check for table identifier (e.g., $t1)
    if (nextToken && nextToken.value.startsWith('$')) {
        const idToken = getToken();
        id = idToken.value;
        idLoc = { line: idToken.line, column: idToken.column };
        nextToken = peekToken();
    }

    // Parse minimum size (required if no ID and it's not (table type) form)
    // Or it could be an explicit table index if multi-table is considered $id <idx> <min> <max> <type>
    // Standard WAT is (table $id? <min> <max>? <reftype>) or (table $id? <reftype> (elem ...))
    // This parser seems to aim for the limits + type form.
    if (nextToken && /^\d+$/.test(nextToken.value)) {
        const minToken = getToken();
        min = Number.parseInt(minToken.value, 10);
        minLoc = { line: minToken.line, column: minToken.column };
        nextToken = peekToken();

        // Parse maximum size (optional)
        if (nextToken && /^\d+$/.test(nextToken.value)) {
            const maxToken = getToken();
            max = Number.parseInt(maxToken.value, 10);
            maxLoc = { line: maxToken.line, column: maxToken.column };
            nextToken = peekToken();
        }
    }

    // Parse element type (funcref or externref)
    // anyref is not standard for tables in MVP, but some proposals might use it.
    const validTableTypes = ['funcref', 'externref'];
    if (nextToken && validTableTypes.includes(nextToken.value)) {
        const typeToken = getToken();
        tableType = typeToken.value;
        typeLoc = { line: typeToken.line, column: typeToken.column };
        nextToken = peekToken();
    } else if (minLoc === null && id === null) { 
        // This means no ID, no numeric limits were parsed before.
        // It must be the type then. Example: (table funcref (elem ...))
        // Or it's an error if nothing is there.
        if (nextToken && nextToken.value !== ')') { // Check if there's a token that could be a type
             const typeToken = getToken();
             if (!validTableTypes.includes(typeToken.value)) {
                 throw createError(`Invalid table type '${typeToken.value}'. Expected 'funcref' or 'externref'.`, typeToken.line, typeToken.column);
             }
             tableType = typeToken.value;
             typeLoc = { line: typeToken.line, column: typeToken.column };
             nextToken = peekToken();
        } else {
             // If no ID, no limits, and no type, it's an error unless it's an import/export form not handled here.
             // For now, let's assume a type is expected if no limits.
             // Or the default 'funcref' applies if nothing else specified.
             // The current logic implies min is required if no ID.
             // Let's ensure min was parsed if no ID and no explicit type was first.
             if (id === null && minLoc === null && typeLoc === null) {
                 // This means something like (table) or (table $id) which is invalid without limits or type.
                 const errLine = idLoc ? idLoc.line : (mainLoc ? mainLoc.line : (nextToken ? nextToken.line : 0));
                 const errCol = idLoc ? idLoc.column + (id ? id.length : 0) : (mainLoc ? mainLoc.column + 5 : (nextToken ? nextToken.column : 0));
                 throw createError("Table declaration requires limits or type.", errLine, errCol);
             }
        }
    }
    
    // Note: This parser doesn't handle inline (export "name") or (import "mod" "nm") or (elem ...)
    // which are also possible within a table definition.

    if (!mainLoc) mainLoc = passedKeywordLoc || firstConsumedTokenLoc || getCurrentCursor(); // Fallback

    return { 
        node_type: 'table_decl',
        id, 
        idLoc,
        min, 
        minLoc,
        max, 
        maxLoc,
        tableType, // Renamed from 'type' to 'tableType' for clarity
        typeLoc,
        loc: mainLoc 
    };
}