// Generated by 🤖
import { atEnd, peekToken, skipToken, getToken, getCurrentCursor } from './tape.mjs';
import { createError } from './parse-util.mjs';

export function parseData(passedKeywordLoc = null) {
    let mainLoc = passedKeywordLoc;

    let id = null, idLoc = null;
    let offset = 0; // Default for active segments if not specified or if const expr is invalid
    let offsetExpressionLoc = null, offsetOpcode = null, offsetOpcodeLoc = null, offsetValue = null, offsetValueLoc = null;
    
    let memoryIndex = null, memoryIndexLoc = null; // For (data (memory <idx>) ...)

    let isPassive = false; // Becomes true if no offset expression or if only id is present.
    
    let firstConsumedTokenLoc = null;

    // Check for data segment identifier (e.g., $d1)
    let nextToken = peekToken();
    if (nextToken && nextToken.value.startsWith('$')) {
        const idToken = getToken();
        id = idToken.value;
        idLoc = { line: idToken.line, column: idToken.column };
        if (!firstConsumedTokenLoc) firstConsumedTokenLoc = idLoc;
        nextToken = peekToken();
    }
    
    // If there's no ID, and no explicit offset, it's a passive segment.
    // If there's an ID, but no offset, it's a named passive segment.
    // If there's an offset, it's an active segment.
    
    if (nextToken && nextToken.value === '(') { // Start of memory index or offset expression
        const exprStartLoc = { line: nextToken.line, column: nextToken.column };
        if (!firstConsumedTokenLoc) firstConsumedTokenLoc = exprStartLoc;
        skipToken(); // Consume '('

        nextToken = peekToken();
        if (nextToken && nextToken.value === 'memory') {
            // (memory <idx>)
            const memKeywordToken = getToken(); // consume 'memory'
            const memIdxToken = getToken(); // consume idx
            if (!memIdxToken || !/^\d+$/.test(memIdxToken.value)) {
                 throw createError(`Expected memory index after 'memory' keyword in data segment.`, memKeywordToken.line, memKeywordToken.column + memKeywordToken.value.length);
            }
            memoryIndex = Number.parseInt(memIdxToken.value, 10);
            memoryIndexLoc = { line: memIdxToken.line, column: memIdxToken.column };
            
            if (!(peekToken() && peekToken().value === ')')) {
                throw createError(`Expected ')' after memory index in data segment.`, memIdxToken.line, memIdxToken.column + memIdxToken.value.length);
            }
            skipToken(); // Consume ')' for (memory <idx>)
            
            // After (memory <idx>), there might be an offset expression (i32.const ...)
            nextToken = peekToken();
            if (nextToken && nextToken.value === '(') {
                offsetExpressionLoc = { line: nextToken.line, column: nextToken.column };
                skipToken(); // Consume '(' for offset expr
            } else {
                // No explicit offset expression after (memory <idx>), implies offset 0 for active segment
                isPassive = false; // Active segment, default offset 0
            }
        } else if (nextToken && nextToken.value === 'i32.const') {
             // This is (i32.const <offset>) directly
            offsetExpressionLoc = exprStartLoc; // The '(' already consumed was for this
        } else if (id && (!nextToken || nextToken.value.startsWith('"'))) {
            // This case: (data $name "string..."), implies passive if no offset expression follows.
            // The '(' was not for an offset or memory. This indicates an error or unexpected structure.
            // However, the loop for strings is outside. If we are here, it means `(` was consumed.
            // This implies an invalid expression if not memory or i32.const.
            // For now, let's assume if we consumed '(', it must be followed by a valid expression or it's an error.
            // If `nextToken` is a string, it means the `(` was not for an offset.
            // This path means we are inside an expression, but it's not memory or i32.const.
            // For simplicity, if it's not 'memory' or 'i32.const', we'll assume no valid offset expression.
             isPassive = true; // No valid offset expression found.
        }


        if (offsetExpressionLoc) { // If we expect an offset expression
            isPassive = false; // Has an offset expression, so it's active.
            const opcodeToken = getToken(); // Should be i32.const
            offsetOpcode = opcodeToken.value;
            offsetOpcodeLoc = { line: opcodeToken.line, column: opcodeToken.column };

            if (offsetOpcode === 'i32.const') {
                const valueToken = getToken();
                if (!valueToken || !/^-?\d+$/.test(valueToken.value)) {
                     throw createError(`Expected integer offset value for i32.const in data segment.`, offsetOpcodeLoc.line, offsetOpcodeLoc.column + offsetOpcode.length);
                }
                offsetValue = Number.parseInt(valueToken.value, 10);
                offsetValueLoc = { line: valueToken.line, column: valueToken.column };
                offset = offsetValue; // Set the actual offset
            } else {
                 throw createError(`Expected 'i32.const' for data offset, got '${offsetOpcode}'.`, offsetOpcodeLoc.line, offsetOpcodeLoc.column);
            }

            if (!(peekToken() && peekToken().value === ')')) {
                 throw createError(`Expected ')' to close offset expression in data segment.`, offsetValueLoc ? offsetValueLoc.line : offsetOpcodeLoc.line, offsetValueLoc ? offsetValueLoc.column + offsetValue.toString().length : offsetOpcodeLoc.column + offsetOpcode.length);
            }
            skipToken(); // Skip closing paren ')' of the offset expression
        }
    } else if (id && !(nextToken && nextToken.value.startsWith('"'))) {
        // Only ID is present, no offset expression, no strings immediately after -> passive by definition
        isPassive = true;
    } else if (!id && !(nextToken && nextToken.value.startsWith('"'))) {
        // No ID, no offset expression, no strings -> effectively an empty (data) which could be passive.
        isPassive = true;
    }


    // Parse bytes strings
    const stringLiterals = []; // To store { value: "raw_str_content", loc: {line, col} }
    const processedBytes = [];

    nextToken = peekToken();
    while (nextToken && nextToken.value.startsWith('"') && nextToken.value.endsWith('"')) {
        const stringToken = getToken();
        if (!firstConsumedTokenLoc) firstConsumedTokenLoc = { line: stringToken.line, column: stringToken.column };
        
        const rawStringContent = stringToken.value.substring(1, stringToken.value.length - 1);
        stringLiterals.push({ value: rawStringContent, loc: { line: stringToken.line, column: stringToken.column } });

        for (let k = 0; k < rawStringContent.length; k++) {
            if (rawStringContent[k] === '\\') {
                k++; 
                if (k < rawStringContent.length) {
                    const char = rawStringContent[k];
                    if ((char >= '0' && char <= '9') || (char >= 'a' && char <= 'f') || (char >= 'A' && char <= 'F')) {
                        if (k + 1 < rawStringContent.length) {
                            const char2 = rawStringContent[k+1];
                            if ((char2 >= '0' && char2 <= '9') || (char2 >= 'a' && char2 <= 'f') || (char2 >= 'A' && char2 <= 'F')) {
                                processedBytes.push(Number.parseInt(char + char2, 16));
                                k++; 
                                continue;
                            }
                        }
                        processedBytes.push(Number.parseInt(char, 16));
                    }
                    else if (char === 't') processedBytes.push(9);  
                    else if (char === 'n') processedBytes.push(10); 
                    else if (char === 'r') processedBytes.push(13); 
                    else if (char === '\\') processedBytes.push(92);
                    else if (char === '"') processedBytes.push(34); 
                    else if (char === '\'') processedBytes.push(39);
                    // Note: \0 is not standard WAT escape for null, but raw \00 is.
                    // If a literal \0 is needed, it should be \00.
                    // We'll treat non-standard escapes as errors or literals based on strictness.
                    // For now, pushing the char code of the escaped char.
                    else processedBytes.push(rawStringContent.charCodeAt(k)); 
                }
            } else {
                processedBytes.push(rawStringContent.charCodeAt(k));
            }
        }
        nextToken = peekToken();
    }
    
    if (stringLiterals.length === 0 && id && !offsetExpressionLoc) { // e.g. (data $name)
        isPassive = true;
    } else if (stringLiterals.length > 0 && !id && !offsetExpressionLoc && !memoryIndexLoc) { // e.g. (data "string")
        isPassive = true; // This is passive data
    }


    mainLoc = passedKeywordLoc || firstConsumedTokenLoc || getCurrentCursor(); // Fallback for loc

    return { 
        type: 'data_segment',
        id, 
        idLoc,
        memoryIndex,
        memoryIndexLoc,
        offset, // The numeric offset value
        offsetExpression: offsetOpcode ? { // Information about the offset expression
            opcode: offsetOpcode,
            opcodeLoc: offsetOpcodeLoc,
            value: offsetValue,
            valueLoc: offsetValueLoc,
            loc: offsetExpressionLoc
        } : null,
        bytes: {
            rawStrings: stringLiterals, // Array of { value: "raw_content", loc: {line,col} }
            processed: processedBytes  // Array of numbers (byte values)
        }, 
        isPassive,
        loc: mainLoc 
    };
}