// Generated by 🤖
import { peekToken, skipToken, atEnd, getToken, getCurrentCursor } from './tape.mjs';
import { createError } from './parse-util.mjs';

export function parseExport(passedKeywordLoc = null) {
    let mainLoc = passedKeywordLoc;
    let firstConsumedTokenLoc = null;

    let name = null, nameLoc = null;
    let kind = null, kindLoc = null;
    let index = null, indexLoc = null; // Can be a numeric string or a string starting with $
    let exportDescLoc = null; // Loc for the start of (<kind> <index>)

    // Parse export name (string)
    let currentToken = peekToken();
    if (currentToken && currentToken.value.startsWith('"') && currentToken.value.endsWith('"')) {
        const nameToken = getToken();
        name = nameToken.value.substring(1, nameToken.value.length - 1);
        nameLoc = { line: nameToken.line, column: nameToken.column };
        if (!firstConsumedTokenLoc) firstConsumedTokenLoc = nameLoc;
    } else {
        throw createError(`Expected export name (string) but got ${currentToken ? currentToken.value : "EOF"}`,
                          currentToken ? currentToken.line : (mainLoc ? mainLoc.line : 0),
                          currentToken ? currentToken.column : (mainLoc ? mainLoc.column : 0));
    }

    // Parse export definition: (func $name) or (func index) or (table $t) etc.
    currentToken = peekToken();
    if (currentToken && currentToken.value === '(') {
        exportDescLoc = { line: currentToken.line, column: currentToken.column };
        skipToken(); // Skip opening paren '('

        const kindToken = getToken();
        if (!kindToken) {
            throw createError("Expected export kind (func, table, memory, global) after '('",
                              exportDescLoc.line, exportDescLoc.column + 1);
        }
        kind = kindToken.value;
        kindLoc = { line: kindToken.line, column: kindToken.column };

        // Validate kind
        const validKinds = ['func', 'table', 'memory', 'global'];
        if (!validKinds.includes(kind)) {
            throw createError(`Invalid export kind '${kind}'. Expected one of ${validKinds.join(', ')}.`,
                              kindLoc.line, kindLoc.column);
        }

        const indexToken = getToken();
        if (!indexToken) {
            throw createError(`Expected export index or name for kind '${kind}'`,
                              kindLoc.line, kindLoc.column + kind.length);
        }
        index = indexToken.value; // Can be numeric string or $name
        indexLoc = { line: indexToken.line, column: indexToken.column };

        // Skip closing paren ')'
        const closingParenToken = getToken();
        if (!closingParenToken || closingParenToken.value !== ')') {
            throw createError(`Expected ')' to close export description but got ${closingParenToken ? closingParenToken.value : "EOF"}`,
                              indexLoc.line, indexLoc.column + index.length);
        }
    } else {
        throw createError(`Expected '(' to start export description (e.g., (func ...)) but got ${currentToken ? currentToken.value : "EOF"}`,
                          nameLoc ? nameLoc.line : (mainLoc ? mainLoc.line : 0),
                          nameLoc ? nameLoc.column + name.length + 2 : (mainLoc ? mainLoc.column : 0));
    }
    
    if (!mainLoc) mainLoc = firstConsumedTokenLoc || getCurrentCursor(); // Fallback for mainLoc

    return {
        type: 'export_decl', // Explicit type for this AST node
        name,
        nameLoc,
        kind,
        kindLoc,
        index, // This is the string representation of the index or name ($name)
        indexLoc,
        exportDescLoc, // Loc of the opening '(' for the description
        loc: mainLoc // Overall loc for the export statement (ideally loc of 'export' keyword)
    };
}