import {
	parseF32Literal,
	parseF64Literal,
	parseI32Literal,
	parseI64Literal,
} from "../number-literals.mjs";
import { decodeWatString } from "../wat-string.mjs";

export function parseGlobal(tape) {
	const { atEnd, getCurrentCursor, getToken, peekToken, skipToken } = tape;
	// Parse global declaration: (global $name [(mut)] type [init]) or (global $name (import "module" "name") type)
	let name = null;
	let type = null;
	let mutable = false;
	let init = null;
	let importModule = null;
	let importName = null;
	let invalidInitExpression = null;

	const position = getCurrentCursor();

	// Check for global name
	if (!atEnd() && peekToken().startsWith("$")) {
		name = getToken();
	}

	// Check for mutability or import
	if (!atEnd() && peekToken() === "(") {
		skipToken(); // Skip opening paren

		if (!atEnd()) {
			const keyword = peekToken();

			if (keyword === "mut") {
				mutable = true;
				skipToken(); // Skip 'mut'

				// Read the type after 'mut'
				if (!atEnd()) {
					type = getToken();
				}

				// Skip closing paren of mutability declaration
				if (!atEnd() && peekToken() === ")") {
					skipToken();
				}
			} else if (keyword === "import") {
				// Generated by 🤖
				skipToken(); // Skip 'import'

				// Parse module name (first string)
				if (
					!atEnd() &&
					peekToken().startsWith('"') &&
					peekToken().endsWith('"')
				) {
					const moduleStr = getToken();
					importModule = decodeWatString(moduleStr);
				}

				// Parse field name (second string)
				if (
					!atEnd() &&
					peekToken().startsWith('"') &&
					peekToken().endsWith('"')
				) {
					const fieldStr = getToken();
					importName = decodeWatString(fieldStr);
				}

				// Skip closing paren of import declaration
				if (!atEnd() && peekToken() === ")") {
					skipToken();
				}
			} else {
				// Skip unrecognized expression in parentheses
				while (!atEnd() && peekToken() !== ")") {
					skipToken();
				}
				skipToken(); // Skip closing paren
			}
		}
	}

	// If no mutability was declared, read the type directly
	if (!type && !atEnd()) {
		type = getToken();
	}

	// Parse initialization expression
	if (!atEnd() && peekToken() === "(") {
		skipToken(); // Skip opening paren of init expression

		// Currently supporting const expressions like i32.const, f32.const
		if (!atEnd()) {
			const instrType = getToken();

			if (instrType === "i32.const") {
				if (!atEnd()) {
					const value = parseI32Literal(getToken());
					init = { type: "i32.const", value };
				}
			} else if (instrType === "f32.const") {
				if (!atEnd()) {
					const { value, bits } = parseF32Literal(getToken());
					init = { type: "f32.const", value, bits };
				}
			} else if (instrType === "i64.const") {
				if (!atEnd()) {
					const value = parseI64Literal(getToken());
					init = { type: "i64.const", value };
				}
			} else if (instrType === "f64.const") {
				if (!atEnd()) {
					const { value, bits } = parseF64Literal(getToken());
					init = { type: "f64.const", value, bits };
				}
			} else if (instrType === "v128.const") {
				// Generated by 🤖
				if (!atEnd()) {
					const shape = getToken();
					const immediates = [];

					// Determine max values based on shape
					let maxValues = 16; // Default for i8x16
					if (shape === "i16x8" || shape === "i16x8_splat") {
						maxValues = 8;
					} else if (
						shape === "i32x4" ||
						shape === "i32x4_splat" ||
						shape === "f32x4" ||
						shape === "f32x4_splat"
					) {
						maxValues = 4;
					} else if (
						shape === "i64x2" ||
						shape === "i64x2_splat" ||
						shape === "f64x2" ||
						shape === "f64x2_splat"
					) {
						maxValues = 2;
					}

					// Parse immediate values
					while (
						!atEnd() &&
						peekToken() !== ")" &&
						immediates.length < maxValues
					) {
						if (/^-?(0x[0-9a-fA-F]+|\d+(\.\d+)?)$/.test(peekToken())) {
							const token = getToken();
							const isFloat = shape.startsWith("f") || token.includes(".");
							const value = isFloat
								? Number.parseFloat(token)
								: Number.parseInt(token, 10);
							immediates.push(value);
						} else {
							skipToken();
						}
					}

					init = {
						type: "v128.const",
						opcode: "v128.const",
						shape,
						immediates,
					};
				}
			} else {
				invalidInitExpression = instrType;
			}
		}

		// Skip closing paren of init expression
		while (!atEnd() && peekToken() !== ")") {
			skipToken();
		}
		if (!atEnd() && peekToken() === ")") {
			skipToken();
		}
	}

	return {
		name,
		type,
		mutable,
		init,
		invalidInitExpression,
		position,
		import:
			importModule && importName
				? { module: importModule, field: importName }
				: null,
	};
}
