// filepath: /Users/martinericsson/dev/fes-compiler/tests/simd-f64x2-compare/index.mjs
import testSIMDF64x2Compare from './simd-f64x2-compare-test.mjs';
import { testRunner } from '../test-utils.mjs';

try {
    const result = await testRunner(testSIMDF64x2Compare, 'simd-f64x2-compare', true);
    if (!result) {
        throw new Error('SIMD f64x2 compare test failed');
    }
}
catch (error) {
    console.error('Error during SIMD f64x2 compare test:', error);
    process.exit(1);
}
// Generated by 🤖
