(module
  ;; Memory for our test vectors
  (memory 1)

  ;; Function to test f64x2.eq
  (func $test_f64x2_eq (export "test_f64x2_eq") (result i32) (local v128)
    ;; Define test vectors
    v128.const f64x2 10.0 20.0  ;; a
    v128.const f64x2 10.0 25.0  ;; b
    ;; Compare for equality
    f64x2.eq
    ;; Extract results and combine into a single i32
    local.tee 0  ;; Store result in local 0 and keep a copy on stack
    i64x2.extract_lane 0
    i32.wrap_i64  ;; Convert to i32
    local.get 0
    i64x2.extract_lane 1
    i32.wrap_i64  ;; Convert to i32
    i32.add
    ;; Should be -1 + 0 = -1 (where -1 is all bits set for true)
  )

  ;; Function to test f64x2.ne
  (func $test_f64x2_ne (export "test_f64x2_ne") (result i32) (local v128)
    v128.const f64x2 10.0 20.0  ;; a
    v128.const f64x2 10.0 25.0  ;; b
    f64x2.ne
    ;; Extract results and combine
    local.tee 0
    i64x2.extract_lane 0
    i32.wrap_i64
    local.get 0
    i64x2.extract_lane 1
    i32.wrap_i64
    i32.add
    ;; Should be 0 + -1 = -1
  )

  ;; Function to test f64x2.lt
  (func $test_f64x2_lt (export "test_f64x2_lt") (result i32) (local v128)
    v128.const f64x2 10.0 30.0  ;; a
    v128.const f64x2 15.0 25.0  ;; b
    f64x2.lt
    ;; Extract results and combine
    local.tee 0
    i64x2.extract_lane 0
    i32.wrap_i64
    local.get 0
    i64x2.extract_lane 1
    i32.wrap_i64
    i32.add
    ;; Should be -1 + 0 = -1
  )

  ;; Function to test f64x2.gt
  (func $test_f64x2_gt (export "test_f64x2_gt") (result i32) (local v128)
    v128.const f64x2 15.0 30.0  ;; a
    v128.const f64x2 10.0 25.0  ;; b
    f64x2.gt
    ;; Extract results and combine
    local.tee 0
    i64x2.extract_lane 0
    i32.wrap_i64
    local.get 0
    i64x2.extract_lane 1
    i32.wrap_i64
    i32.add
    ;; Should be -1 + -1 = -2
  )

  ;; Function to test f64x2.le
  (func $test_f64x2_le (export "test_f64x2_le") (result i32) (local v128)
    v128.const f64x2 10.0 20.0  ;; a
    v128.const f64x2 10.0 25.0  ;; b
    f64x2.le
    ;; Extract results and combine
    local.tee 0
    i64x2.extract_lane 0
    i32.wrap_i64
    local.get 0
    i64x2.extract_lane 1
    i32.wrap_i64
    i32.add
    ;; Should be -1 + -1 = -2
  )

  ;; Function to test f64x2.ge
  (func $test_f64x2_ge (export "test_f64x2_ge") (result i32) (local v128)
    v128.const f64x2 10.0 30.0  ;; a
    v128.const f64x2 10.0 25.0  ;; b
    f64x2.ge
    ;; Extract results and combine
    local.tee 0
    i64x2.extract_lane 0
    i32.wrap_i64
    local.get 0
    i64x2.extract_lane 1
    i32.wrap_i64
    i32.add
    ;; Should be -1 + -1 = -2
  )
) 
// Generated by 🤖
