;; Generated by 🤖
(module
  ;; Define a table with initial size 2, max size 10
  (table 2 10 funcref)
  
  ;; Define functions that will be referenced
  (func $f1 (result i32)
    i32.const 42)
  
  ;; Function to grow table and return old size
  (func $grow_table (param $n i32) (result i32)
    ref.null func     ;; Initialize new elements with null
    local.get $n
    table.grow 0)  ;; Grow table 0 by n elements
    
  ;; Function to get current table size
  (func $table_size (result i32)
    table.size 0)
  
  ;; Exports for testing
  (export "grow_table" (func $grow_table))
  (export "table_size" (func $table_size))
  (export "tbl" (table 0)))