import { createDiagnostic } from "../diagnostics.mjs";
import wasmConstants from "./constants.mjs";

const { TYPE } = wasmConstants;

// Helper function to encode unsigned LEB128 integer
export function encodeULEB128(inputvalue) {
	let value = inputvalue;
	const result = [];
	do {
		let byte = value & 0x7f;
		value >>>= 7;
		if (value !== 0) {
			byte |= 0x80;
		}
		result.push(byte);
	} while (value !== 0);
	return result;
}

// Helper function to encode signed LEB128 integer for data section offsets
export function encodeSLEB128(inputvalue) {
	let value = inputvalue;
	const result = [];
	let more = true;

	while (more) {
		let byte = value & 0x7f;
		value >>= 7;

		// Sign bit of byte is second high order bit (0x40)
		if (
			(value === 0 && (byte & 0x40) === 0) ||
			(value === -1 && (byte & 0x40) !== 0)
		) {
			more = false;
		} else {
			byte |= 0x80; // Mark this byte to show that more bytes will follow
		}

		result.push(byte);
	}

	return result;
}

// Helper function to encode signed LEB128 integer from BigInt values for i64.const
export function encodeSLEB128BigInt(inputvalue) {
	let value = inputvalue;
	const result = [];
	let more = true;

	// Make sure we're working with a BigInt
	if (typeof value !== "bigint") {
		value = BigInt(value);
	}

	while (more) {
		// Extract the 7 least significant bits
		let byte = Number(value & BigInt(0x7f));

		// Arithmetic shift right by 7 bits (preserves sign)
		value = value >> BigInt(7);

		// Determine if this is the last byte we need
		// For positive numbers, we're done when the remaining value is 0 and the sign bit in byte is not set
		// For negative numbers, we're done when the remaining value is -1 and the sign bit in byte is set
		if (
			(value === BigInt(0) && (byte & 0x40) === 0) ||
			(value === BigInt(-1) && (byte & 0x40) !== 0)
		) {
			more = false;
		} else {
			// More bytes to come
			byte |= 0x80;
		}

		result.push(byte);
	}

	return result;
}

// Helper function to encode string
export function encodeString(str) {
	const utf8Encoder = new TextEncoder();
	const bytes = utf8Encoder.encode(str);
	return [...encodeULEB128(bytes.length), ...Array.from(bytes)];
}

// Helper function to encode f64 value to IEEE 754 bytes
// Generated by 🤖
export function encodeF64(value) {
	const buffer = new ArrayBuffer(8);
	new Float64Array(buffer)[0] = value;
	return Array.from(new Uint8Array(buffer));
}

// Helper function to encode f32 value to IEEE 754 bytes
// Generated by 🤖
export function encodeF32(value) {
	const buffer = new ArrayBuffer(4);
	new Float32Array(buffer)[0] = value;
	return Array.from(new Uint8Array(buffer));
}

// Helper function to encode bytes from WAT data section strings
export function encodeBytes(str) {
	// Special handler for WAT data section format
	// In WAT, data section strings look like "\01\02\03" with single backslashes
	// but in JS strings these are represented as "\\01\\02\\03"
	if (str.includes("\\\\")) {
		const bytes = [];
		let i = 0;

		while (i < str.length) {
			if (str[i] === "\\" && str[i + 1] === "\\") {
				// Skip the double backslash and process the WAT escape sequence
				i += 2; // Skip both backslashes
				if (i < str.length) {
					const c = str[i];

					// Handle numeric escapes (\0-\9)
					if (c >= "0" && c <= "9") {
						bytes.push(Number.parseInt(c, 10));
					}
					// Handle hex escapes
					else if (
						(c === "f" || c === "F") &&
						i + 1 < str.length &&
						(str[i + 1] === "f" || str[i + 1] === "F")
					) {
						bytes.push(255); // \ff = 0xFF = 255
						i++; // Skip the second 'f'
					} else if (
						(c === "f" || c === "F") &&
						i + 1 < str.length &&
						(str[i + 1] === "e" || str[i + 1] === "E")
					) {
						bytes.push(254); // \fe = 0xFE = 254
						i++; // Skip the 'e'
					}
					// Other escapes if needed...
					else {
						bytes.push(str.charCodeAt(i));
					}
				}
				i++;
			} else {
				bytes.push(str.charCodeAt(i));
				i++;
			}
		}

		return bytes;
	}

	// This is the normal case for regular strings
	const bytes = [];

	for (let i = 0; i < str.length; i++) {
		if (str[i] === "\\") {
			i++;
			if (i < str.length) {
				const c = str[i];
				if (c >= "0" && c <= "9") {
					bytes.push(Number.parseInt(c, 10));
				} else if (c === "f") {
					if (i + 1 < str.length && str[i + 1] === "f") {
						bytes.push(255);
						i++;
					} else {
						bytes.push(15);
					}
				} else if (c === "e") {
					if (i + 1 < str.length && str[i + 1] === "e") {
						bytes.push(254);
						i++;
					} else {
						bytes.push(14);
					}
				} else if (c === "t") bytes.push(9);
				else if (c === "n") bytes.push(10);
				else if (c === "r") bytes.push(13);
				else if (c === '"') bytes.push(34);
				else if (c === "'") bytes.push(39);
				else if (c === "\\") bytes.push(92);
			}
		} else {
			bytes.push(str.charCodeAt(i));
		}
	}

	return bytes;
}

// Generated by 🤖
// Helper function to determine natural alignment for memory instructions
export function getInstructionNaturalAlignment(instrType) {
	// Natural alignment is log2 of the size in bytes
	switch (instrType) {
		case "i32.load":
		case "f32.load":
		case "i32.store":
		case "f32.store":
			return 2; // 4 bytes = 2^2

		case "i64.load":
		case "f64.load":
		case "i64.store":
		case "f64.store":
			return 3; // 8 bytes = 2^3

		case "i32.load16_s":
		case "i32.load16_u":
		case "i64.load16_s":
		case "i64.load16_u":
		case "i32.store16":
		case "i64.store16":
			return 1; // 2 bytes = 2^1

		case "i32.load8_s":
		case "i32.load8_u":
		case "i64.load8_s":
		case "i64.load8_u":
		case "i32.store8":
		case "i64.store8":
			return 0; // 1 byte = 2^0

		case "i64.load32_s":
		case "i64.load32_u":
		case "i64.store32":
			return 2; // 4 bytes = 2^2

		default:
			return 0; // Default to byte alignment
	}
}

export function getAtomicInstructionNaturalAlignment(instrType) {
	if (
		instrType.includes("load8_") ||
		instrType.includes("store8") ||
		instrType.includes("rmw8")
	) {
		return 0;
	}

	if (
		instrType.includes("load16_") ||
		instrType.includes("store16") ||
		instrType.includes("rmw16")
	) {
		return 1;
	}

	if (
		instrType.includes("load32_") ||
		instrType.includes("store32") ||
		instrType.includes("rmw32")
	) {
		return 2;
	}

	return instrType.startsWith("i64.") ? 3 : 2;
}

export function encodeMemarg({ align, offset = 0, memoryIndex = null }) {
	const hasMemoryIndex = memoryIndex !== null && memoryIndex !== undefined;
	const flags = hasMemoryIndex ? align | 0x40 : align;
	const bytes = [...encodeULEB128(flags)];

	if (hasMemoryIndex) {
		bytes.push(...encodeULEB128(memoryIndex));
	}

	bytes.push(...encodeULEB128(offset || 0));
	return bytes;
}

// Convert WAT type string to binary type
export function getWasmType(type) {
	switch (type) {
		case "i32":
			return TYPE.I32;
		case "i64":
			return TYPE.I64;
		case "f32":
			return TYPE.F32;
		case "f64":
			return TYPE.F64;
		case "v128":
			return TYPE.V128;
		case "funcref":
			return TYPE.FUNCREF;
		case "externref":
			return TYPE.EXTERNREF;
		case "anyref":
			return TYPE.ANYREF;
		default: {
			const err = new Error(`Unknown type: ${type}`);
			err.context = {
				type: type,
				expectedTypes: [
					"i32",
					"i64",
					"f32",
					"f64",
					"v128",
					"funcref",
					"externref",
					"anyref",
				],
				position: {
					line: 0, // Placeholder for line number
					column: 0, // Placeholder for column number
				},
			};
			throw err;
		}
	}
}

export function orderFunctionsForBinary(functions) {
	const importedFunctions = [];
	const localFunctions = [];

	for (const func of functions) {
		if (func?.import) {
			importedFunctions.push(func);
		} else {
			localFunctions.push(func);
		}
	}

	return [...importedFunctions, ...localFunctions];
}

export function buildFunctionIndex(functions) {
	const byFunction = new Map();
	const byName = new Map();

	for (let i = 0; i < functions.length; i++) {
		const func = functions[i];
		byFunction.set(func, i);
		if (func?.name && !byName.has(func.name)) {
			byName.set(func.name, i);
		}
	}

	return { byFunction, byName };
}

export function resolveFunctionIndex(functionRef, moduleOrFunctions) {
	const functions = Array.isArray(moduleOrFunctions)
		? moduleOrFunctions
		: moduleOrFunctions?.functions || [];
	const functionIndex =
		!Array.isArray(moduleOrFunctions) && moduleOrFunctions?.functionIndex
			? moduleOrFunctions.functionIndex
			: buildFunctionIndex(functions);

	if (typeof functionRef === "number") {
		return functionRef;
	}

	if (typeof functionRef === "string" && functionRef.startsWith("$")) {
		return functionIndex.byName.get(functionRef) ?? -1;
	}

	const parsed = Number.parseInt(functionRef, 10);
	return Number.isNaN(parsed) ? -1 : parsed;
}

// Helper function to resolve label references to label indices
export function getLabelIndex(label, func, branchInstr = null) {
	// Generated by 🤖
	// In WebAssembly, branch indices are depths in the control structure stack
	// For loops, we need to branch to 0 (the loop itself) to continue the loop
	// For blocks, we need to branch to the block's parent depth to exit the block

	// If label is a number or numeric string, use it directly
	if (
		typeof label === "number" ||
		(typeof label === "string" && !Number.isNaN(Number.parseInt(label)))
	) {
		return Number.parseInt(label);
	}

	if (!func || !Array.isArray(func.instructions)) {
		return 0;
	}

	const stack = [];
	let resolvedDepth = null;

	const computeDepthFromStack = () => {
		for (let offset = 0; offset < stack.length; offset++) {
			const frame = stack[stack.length - 1 - offset];
			if (frame.label === label) {
				return offset;
			}
		}
		return null;
	};

	const walkInstructions = (instructions) => {
		for (const instr of instructions) {
			if (instr === branchInstr) {
				const depth = computeDepthFromStack();
				if (depth !== null) {
					resolvedDepth = depth;
					return true;
				}
			}

			if (instr.type === "block" || instr.type === "loop") {
				stack.push({ label: instr.label, type: instr.type });
				if (walkInstructions(instr.instructions || [])) {
					return true;
				}
				stack.pop();
			} else if (instr.type === "if") {
				stack.push({ label: instr.label, type: "if" });
				if (walkInstructions(instr.thenInstructions || [])) {
					return true;
				}
				if (walkInstructions(instr.elseInstructions || [])) {
					return true;
				}
				stack.pop();
			}
		}
		return false;
	};

	if (branchInstr) {
		walkInstructions(func.instructions);
		if (resolvedDepth !== null) {
			return resolvedDepth;
		}
	}

	// Fallback to original behaviour if branch context was not found
	const blocks = [];
	const blockTypes = [];

	const collectBlocks = (instructions) => {
		for (const instr of instructions) {
			if (instr.type === "block" || instr.type === "loop") {
				blocks.push(instr.label);
				blockTypes.push(instr.type);
				collectBlocks(instr.instructions || []);
			} else if (instr.type === "if") {
				collectBlocks(instr.thenInstructions || []);
				collectBlocks(instr.elseInstructions || []);
			}
		}
	};

	collectBlocks(func.instructions);
	blocks.reverse();
	blockTypes.reverse();

	const fallbackIndex = blocks.indexOf(label);
	if (fallbackIndex !== -1) {
		return blockTypes[fallbackIndex] === "loop" ? 0 : fallbackIndex;
	}

	return 0;
}

// Fix and clean up the AST if needed
export function sanitizeAST(ast) {
	if (!ast || !Array.isArray(ast) || ast.length === 0) {
		throw createDiagnostic({
			stage: "validate",
			code: "WAT_INVALID_AST",
			message: "Invalid AST structure",
		});
	}

	// Find the module object in the AST
	const moduleObj = ast.find(
		(item) => item && typeof item === "object" && "functions" in item,
	);

	if (!moduleObj) {
		throw createDiagnostic({
			stage: "validate",
			code: "WAT_NO_MODULE",
			message: "No module found in AST",
			position: ast[0]?.position,
			note: "Compilation requires a top-level `(module ...)` expression.",
		});
	}

	// Initialize module properties
	moduleObj.exports = moduleObj.exports || {};
	moduleObj.functions = moduleObj.functions || [];

	// Clear any existing functions to rebuild them properly
	const originalInModuleFunctions = [...moduleObj.functions];

	// Reset functions array
	moduleObj.functions = [];

	// Re-add original functions from the module
	moduleObj.functions.push(...originalInModuleFunctions);

	// Find all standalone function objects in the AST (outside the module object)
	const funcs = ast.filter(
		(item) =>
			item &&
			typeof item === "object" &&
			Array.isArray(item.instructions) &&
			item !== moduleObj,
	);

	// Process standalone functions
	for (const func of funcs) {
		// Add to module's functions array
		moduleObj.functions.push(func);

		// Handle exports after the final function order is known below.
		if (func.export && typeof func.export === "string") {
			moduleObj.exports[func.export] = {
				kind: "func",
				index: func.name || moduleObj.functions.length - 1,
			};
		}
	}

	moduleObj.functions = orderFunctionsForBinary(moduleObj.functions);
	Object.defineProperty(moduleObj, "functionIndex", {
		value: buildFunctionIndex(moduleObj.functions),
		configurable: true,
		writable: true,
	});

	for (const func of moduleObj.functions) {
		if (func?.export && typeof func.export === "string") {
			moduleObj.exports[func.export] = {
				kind: "func",
				index: moduleObj.functionIndex.byFunction.get(func),
			};
		}
	}

	for (const exportData of Object.values(moduleObj.exports)) {
		if (
			exportData?.kind === "func" &&
			typeof exportData.index === "string" &&
			exportData.index.startsWith("$")
		) {
			const index = resolveFunctionIndex(exportData.index, moduleObj);
			if (index !== -1) {
				exportData.index = index;
			}
		}
	}

	return moduleObj; // Generated by 🤖
}
