import { createDiagnostic } from "../diagnostics.mjs";
import { decodeWatStringToBytes } from "../wat-string.mjs";
export {
	encodeF32,
	encodeF32Bits,
	encodeF64,
	encodeF64Bits,
} from "../number-literals.mjs";
import { TYPE } from "./constants.mjs";

const utf8Encoder = new TextEncoder();

// Helper function to encode unsigned LEB128 integer
export function encodeULEB128(inputvalue) {
	let value = inputvalue;
	const result = [];
	do {
		let byte = value & 0x7f;
		value >>>= 7;
		if (value !== 0) {
			byte |= 0x80;
		}
		result.push(byte);
	} while (value !== 0);
	return result;
}

// Helper function to encode signed LEB128 integer for data section offsets
export function encodeSLEB128(inputvalue) {
	let value = inputvalue;
	const result = [];
	let more = true;

	while (more) {
		let byte = value & 0x7f;
		value >>= 7;

		// Sign bit of byte is second high order bit (0x40)
		if (
			(value === 0 && (byte & 0x40) === 0) ||
			(value === -1 && (byte & 0x40) !== 0)
		) {
			more = false;
		} else {
			byte |= 0x80; // Mark this byte to show that more bytes will follow
		}

		result.push(byte);
	}

	return result;
}

// Helper function to encode signed LEB128 integer from BigInt values for i64.const
export function encodeSLEB128BigInt(inputvalue) {
	let value = inputvalue;
	const result = [];
	let more = true;

	// Make sure we're working with a BigInt
	if (typeof value !== "bigint") {
		value = BigInt(value);
	}

	while (more) {
		// Extract the 7 least significant bits
		let byte = Number(value & BigInt(0x7f));

		// Arithmetic shift right by 7 bits (preserves sign)
		value = value >> BigInt(7);

		// Determine if this is the last byte we need
		// For positive numbers, we're done when the remaining value is 0 and the sign bit in byte is not set
		// For negative numbers, we're done when the remaining value is -1 and the sign bit in byte is set
		if (
			(value === BigInt(0) && (byte & 0x40) === 0) ||
			(value === BigInt(-1) && (byte & 0x40) !== 0)
		) {
			more = false;
		} else {
			// More bytes to come
			byte |= 0x80;
		}

		result.push(byte);
	}

	return result;
}

// Helper function to encode string
export function encodeString(str) {
	const bytes = utf8Encoder.encode(str);
	return [...encodeULEB128(bytes.length), ...Array.from(bytes)];
}

// Helper function to encode bytes from WAT data section strings
export function encodeBytes(str) {
	return decodeWatStringToBytes(str);
}

// Generated by 🤖
// Helper function to determine natural alignment for memory instructions
export function getInstructionNaturalAlignment(instrType) {
	// Natural alignment is log2 of the size in bytes
	switch (instrType) {
		case "i32.load":
		case "f32.load":
		case "i32.store":
		case "f32.store":
			return 2; // 4 bytes = 2^2

		case "i64.load":
		case "f64.load":
		case "i64.store":
		case "f64.store":
			return 3; // 8 bytes = 2^3

		case "i32.load16_s":
		case "i32.load16_u":
		case "i64.load16_s":
		case "i64.load16_u":
		case "i32.store16":
		case "i64.store16":
			return 1; // 2 bytes = 2^1

		case "i32.load8_s":
		case "i32.load8_u":
		case "i64.load8_s":
		case "i64.load8_u":
		case "i32.store8":
		case "i64.store8":
			return 0; // 1 byte = 2^0

		case "i64.load32_s":
		case "i64.load32_u":
		case "i64.store32":
			return 2; // 4 bytes = 2^2

		default:
			return 0; // Default to byte alignment
	}
}

export function getAtomicInstructionNaturalAlignment(instrType) {
	if (
		instrType.includes("load8_") ||
		instrType.includes("store8") ||
		instrType.includes("rmw8")
	) {
		return 0;
	}

	if (
		instrType.includes("load16_") ||
		instrType.includes("store16") ||
		instrType.includes("rmw16")
	) {
		return 1;
	}

	if (
		instrType.includes("load32_") ||
		instrType.includes("store32") ||
		instrType.includes("rmw32")
	) {
		return 2;
	}

	return instrType.startsWith("i64.") ? 3 : 2;
}

export function encodeMemarg({ align, offset = 0, memoryIndex = null }) {
	const hasMemoryIndex = memoryIndex !== null;
	const flags = hasMemoryIndex ? align | 0x40 : align;
	const bytes = [...encodeULEB128(flags)];

	if (hasMemoryIndex) {
		bytes.push(...encodeULEB128(memoryIndex));
	}

	bytes.push(...encodeULEB128(offset ?? 0));
	return bytes;
}

// Convert WAT type string to binary type
export function getWasmType(type) {
	switch (type) {
		case "i32":
			return TYPE.I32;
		case "i64":
			return TYPE.I64;
		case "f32":
			return TYPE.F32;
		case "f64":
			return TYPE.F64;
		case "v128":
			return TYPE.V128;
		case "funcref":
			return TYPE.FUNCREF;
		case "externref":
			return TYPE.EXTERNREF;
		case "anyref":
			return TYPE.ANYREF;
		default: {
			const err = new Error(`Unknown type: ${type}`);
			err.context = {
				type: type,
				expectedTypes: [
					"i32",
					"i64",
					"f32",
					"f64",
					"v128",
					"funcref",
					"externref",
					"anyref",
				],
				position: {
					line: 0, // Placeholder for line number
					column: 0, // Placeholder for column number
				},
			};
			throw err;
		}
	}
}

export function orderFunctionsForBinary(functions) {
	const importedFunctions = [];
	const localFunctions = [];

	for (const func of functions) {
		if (func?.import) {
			importedFunctions.push(func);
		} else {
			localFunctions.push(func);
		}
	}

	return [...importedFunctions, ...localFunctions];
}

export function buildFunctionIndex(functions) {
	const byFunction = new Map();
	const byName = new Map();

	for (let i = 0; i < functions.length; i++) {
		const func = functions[i];
		byFunction.set(func, i);
		if (func?.name && !byName.has(func.name)) {
			byName.set(func.name, i);
		}
	}

	return { byFunction, byName };
}

export function resolveFunctionIndex(functionRef, moduleOrFunctions) {
	const functions = Array.isArray(moduleOrFunctions)
		? moduleOrFunctions
		: moduleOrFunctions?.functions || [];
	const functionIndex =
		!Array.isArray(moduleOrFunctions) && moduleOrFunctions?.functionIndex
			? moduleOrFunctions.functionIndex
			: buildFunctionIndex(functions);

	if (typeof functionRef === "number") {
		return functionRef;
	}

	if (typeof functionRef === "string" && functionRef.startsWith("$")) {
		return functionIndex.byName.get(functionRef) ?? -1;
	}

	const parsed = Number.parseInt(functionRef, 10);
	return Number.isNaN(parsed) ? -1 : parsed;
}

// Fix and clean up the AST if needed
export function sanitizeAST(ast) {
	if (!ast || !Array.isArray(ast) || ast.length === 0) {
		throw createDiagnostic({
			stage: "validate",
			code: "WAT_INVALID_AST",
			message: "Invalid AST structure",
		});
	}

	// Find the module object in the AST
	const moduleObj = ast.find(
		(item) => item && typeof item === "object" && "functions" in item,
	);

	if (!moduleObj) {
		throw createDiagnostic({
			stage: "validate",
			code: "WAT_NO_MODULE",
			message: "No module found in AST",
			position: ast[0]?.position,
			note: "Compilation requires a top-level `(module ...)` expression.",
		});
	}

	// Initialize module properties
	moduleObj.exports = moduleObj.exports || {};
	moduleObj.functions = moduleObj.functions || [];

	// Clear any existing functions to rebuild them properly
	const originalInModuleFunctions = [...moduleObj.functions];

	// Reset functions array
	moduleObj.functions = [];

	// Re-add original functions from the module
	moduleObj.functions.push(...originalInModuleFunctions);

	// Find all standalone function objects in the AST (outside the module object)
	const funcs = ast.filter(
		(item) =>
			item &&
			typeof item === "object" &&
			Array.isArray(item.instructions) &&
			item !== moduleObj,
	);

	// Process standalone functions
	for (const func of funcs) {
		// Add to module's functions array
		moduleObj.functions.push(func);

		// Handle exports after the final function order is known below.
		if (func.export && typeof func.export === "string") {
			moduleObj.exports[func.export] = {
				kind: "func",
				index: func.name || moduleObj.functions.length - 1,
			};
		}
	}

	moduleObj.functions = orderFunctionsForBinary(moduleObj.functions);
	Object.defineProperty(moduleObj, "functionIndex", {
		value: buildFunctionIndex(moduleObj.functions),
		configurable: true,
		writable: true,
	});

	for (const func of moduleObj.functions) {
		if (func?.export && typeof func.export === "string") {
			moduleObj.exports[func.export] = {
				kind: "func",
				index: moduleObj.functionIndex.byFunction.get(func),
			};
		}
	}

	for (const exportData of Object.values(moduleObj.exports)) {
		if (
			exportData?.kind === "func" &&
			typeof exportData.index === "string" &&
			exportData.index.startsWith("$")
		) {
			const index = resolveFunctionIndex(exportData.index, moduleObj);
			if (index !== -1) {
				exportData.index = index;
			}
		}
	}

	return moduleObj; // Generated by 🤖
}
