import { enhanceError } from "../diagnostics.mjs";
import { SourceMapManager } from "../sourcemap.mjs";
import { validateModule } from "../validate/validate.mjs";
import { createBytesWriter } from "./bytes-writer.mjs";
import { sanitizeAST } from "./compile-utils.mjs";
import { BINARY } from "./constants.mjs";
import { codeSection } from "./sections/code.mjs";
import { dataCountSection, dataSection } from "./sections/data.mjs";
import { elementSection } from "./sections/element.mjs";
import { exportSection } from "./sections/export.mjs";
import { functionSection } from "./sections/function.mjs";
import { globalSection } from "./sections/global.mjs";
import { importSection } from "./sections/import.mjs"; // Generated by 🤖
import { memorySection } from "./sections/memory.mjs";
import { multivalueSection } from "./sections/multivalue.mjs";
import { startSection } from "./sections/start.mjs";
import { tableSection } from "./sections/table.mjs";
import { typeSection } from "./sections/type.mjs";

const compileToWASM = (ast, options = {}) => {
	try {
		const profile = options.profile || null;
		const tStart =
			typeof process !== "undefined" && process.hrtime?.bigint
				? process.hrtime.bigint()
				: BigInt(Math.floor(performance.now() * 1e6));

		// Initialize source map manager if requested
		let sourceMapManager = null;
		if (options.sourceMap) {
			sourceMapManager = new SourceMapManager();
		}

		// Clean up and validate the AST
		const module = sanitizeAST(ast);
		validateModule(module);

		// Start with the magic and version
		const binary = createBytesWriter();
		binary.writeBytes(BINARY.MAGIC);
		binary.writeBytes(BINARY.VERSION);

		// For completely empty module (no functions, memories, etc), just return the header
		if (
			(!module.functions || module.functions.length === 0) &&
			(!module.memories || module.memories.length === 0) &&
			(!module.datas || module.datas.length === 0) &&
			(!module.globals || module.globals.length === 0) &&
			(!module.imports || module.imports.length === 0) &&
			(!module.tables || module.tables.length === 0) &&
			(!module.elements || module.elements.length === 0) &&
			(!module.exports || Object.keys(module.exports).length === 0)
		) {
			return binary.toUint8Array();
		}

		const functions = module.functions || [];
		const globals = module.globals || [];
		const tables = module.tables || [];
		const elements = module.elements || [];
		const multiValueBlockTypes = [];

		multivalueSection(functions, multiValueBlockTypes);

		typeSection(module, functions, multiValueBlockTypes, binary);

		// =================== IMPORT SECTION ===================
		// Generated by 🤖
		importSection(module, binary);

		// =================== FUNCTION SECTION ===================
		functionSection(functions, binary);

		// =================== TABLE SECTION ===================
		tableSection(tables, binary);

		// =================== GLOBAL SECTION ===================
		globalSection(globals, binary);

		// =================== MEMORY SECTION ===================
		memorySection(module, binary);

		// =================== EXPORT SECTION ===================
		exportSection(module, binary);

		// =================== START SECTION ===================
		startSection(module, functions, binary);

		// =================== ELEMENT SECTION ===================
		elementSection(elements, functions, binary);

		// =================== DATA COUNT SECTION ===================
		// Only include if we have data sections
		if (module.datas && module.datas.length > 0) {
			dataCountSection(module, binary);
		}

		// =================== CODE SECTION ===================
		codeSection(functions, globals, module, binary, sourceMapManager, options);

		// =================== DATA SECTION ===================
		if (module.datas && module.datas.length > 0) {
			dataSection(module, binary);
		}

		const result = binary.toUint8Array();
		if (profile) {
			const tEnd =
				typeof process !== "undefined" && process.hrtime?.bigint
					? process.hrtime.bigint()
					: BigInt(Math.floor(performance.now() * 1e6));
			profile.compile_ns = Number(tEnd - tStart);
			profile.wasm_bytes = result.byteLength;
		}

		// Return object with binary and sourceMap if source mapping is enabled
		if (sourceMapManager) {
			return {
				binary: result,
				sourceMap: sourceMapManager.toJSON(),
			};
		}

		return result;
	} catch (error) {
		throw enhanceError(error, {
			stage: error?.context?.stage || "compile",
			source: options.source,
			filename: options.filename || "input.wat",
		});
	}
};

export { compileToWASM };
