;; Generated by 🤖
(module
  ;; Define table with min size 4
  (table 4 4 funcref)
  
  ;; Define functions that will be referenced
  (func $f1 (result i32)
    i32.const 42)
    
  (func $f2 (result i32)
    i32.const 43)
    
  ;; Define an active element segment at offset 0
  (elem (i32.const 0) $f1 $f2)
  
  ;; Define a passive element segment (index 1)
  (elem passive funcref $f1 $f2)
  
  ;; Function to drop element segment
  (func $drop_elem (param $idx i32)
    local.get $idx
    elem.drop
    drop)  ;; Drop any value left by elem.drop
  
  ;; Function to check if we can still use the function
  (func $get_func (param i32) (result funcref)
    local.get 0
    table.get 0)
  
  ;; Exports for testing
  (export "drop_elem" (func $drop_elem))
  (export "get_func" (func $get_func))
  (export "f1" (func $f1))
  (export "f2" (func $f2))
  (export "tbl" (table 0)))