;; Generated by 🤖
(module
  (memory 1 1 shared)

  (func (export "atomic_store_load") (param i32 i32) (result i32)
    ;; Store value atomically
    local.get 0  ;; address
    local.get 1  ;; value
    i32.atomic.store

    ;; Load value atomically
    local.get 0  ;; address
    i32.atomic.load
  )

  (func (export "atomic_i64_store_load") (param i32 i64) (result i64)
    ;; Store value atomically
    local.get 0  ;; address
    local.get 1  ;; value
    i64.atomic.store

    ;; Load value atomically
    local.get 0  ;; address
    i64.atomic.load
  )
    
  (func (export "atomic_load8_u") (param i32 i32) (result i32)
    ;; Store regular value (not atomic)
    local.get 0  ;; address
    local.get 1  ;; value
    i32.store8
    
    ;; Load value atomically (8-bit unsigned)
    local.get 0  ;; address
    i32.atomic.load8_u
  )
    
  ;; Generated by 🤖
  (func (export "atomic_store8_load8_u") (param i32 i32) (result i32)
    ;; Store value atomically (8-bit)
    local.get 0  ;; address
    local.get 1  ;; value
    i32.atomic.store8
    
    ;; Load value atomically (8-bit unsigned)
    local.get 0  ;; address
    i32.atomic.load8_u
  )

  (func (export "atomic_store16_load16_u") (param i32 i32) (result i32)
    ;; Store value atomically (16-bit)
    local.get 0  ;; address
    local.get 1  ;; value
    i32.atomic.store16
    
    ;; Load value atomically (8-bit unsigned)
    local.get 0  ;; address
    i32.atomic.load16_u
  )

   (func (export "atomic_i64_store8_load8_u") (param i32 i64) (result i64)
    local.get 0  ;; address
    local.get 1  ;; value
    i64.atomic.store8
    
    ;; Load value atomically (8-bit unsigned)
    local.get 0  ;; address
    i64.atomic.load8_u
  )

  (func (export "atomic_i64_store16_load16_u") (param i32 i64) (result i64)
    local.get 0  ;; address
    local.get 1  ;; value
    i64.atomic.store16
    
    ;; Load value atomically
    local.get 0  ;; address
    i64.atomic.load16_u
  )

  (func (export "atomic_i64_store32_load32_u") (param i32 i64) (result i64)
    local.get 0  ;; address
    local.get 1  ;; value
    i64.atomic.store32
    
    ;; Load value atomically
    local.get 0  ;; address
    i64.atomic.load32_u
  )
)
