import { testRunner } from "../test-utils.mjs";
// Generated by 🤖
import testAtomicMemory from "./atomic-memory-test.mjs";

try {
	await testRunner(testAtomicMemory, "atomic-memory", true);
} catch (e) {
	console.error("❌ Test failed:", e);
	process.exit(1);
}
