(module
  ;; Function with a mix of named and anonymous local variables
  (func $mixed_locals (export "mixed_locals") (result i32)
    ;; Named local variable
    (local $named i32)
    ;; Anonymous local variables of different types
    (local i32)
    (local i64)
    (local f32)
    (local v128)
    
    ;; Set values to locals
    i32.const 42
    local.set $named
    
    i32.const 100
    local.set 1  ;; First anonymous local (index 1)
    
    i64.const 200
    local.set 2  ;; Second anonymous local (index 2)
    
    f32.const 3.14
    local.set 3  ;; Third anonymous local (index 3)
    
    ;; Set SIMD local to a splat of 5
    v128.const i8x16 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
    local.set 4  ;; Fourth anonymous local (index 4)
    
    ;; Return sum of the named local and first anonymous local
    local.get $named
    local.get 1
    i32.add
  ) ;; Generated by 🤖
  
  ;; Function with only anonymous local variables
  (func $all_anon (export "all_anon") (result i32)
    ;; Only anonymous local variables
    (local i32)
    (local i32)
    (local i32)
    
    ;; Set values
    i32.const 10
    local.set 0
    
    i32.const 20
    local.set 1
    
    i32.const 30
    local.set 2
    
    ;; Return sum of all locals
    local.get 0
    local.get 1
    i32.add
    local.get 2
    i32.add
  ) ;; Generated by 🤖
  
  ;; Function with anonymous v128 for SIMD operations
  (func $simd_anon (export "simd_anon") (result i32)
    ;; Anonymous SIMD local
    (local v128)
    
    ;; Create a v128 value where all 16 lanes contain the value 7
    v128.const i8x16 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
    local.set 0
    
    ;; Extract and sum first two lanes
    local.get 0
    i8x16.extract_lane_u 0
    local.get 0
    i8x16.extract_lane_u 1
    i32.add
  ) ;; Generated by 🤖
)
