;; Generated by 🤖
(module
  (table 3 funcref)
  
  (type $i32_i32_to_i32 (func (param i32 i32) (result i32)))
  
  (func $add (type $i32_i32_to_i32)
    local.get 0
    local.get 1
    i32.add)
    
  (func $sub (type $i32_i32_to_i32)
    local.get 0
    local.get 1
    i32.sub)
    
  (func $mul (type $i32_i32_to_i32)
    local.get 0
    local.get 1
    i32.mul)
  
  (elem (i32.const 0) $add $sub $mul)
  
  (func (export "calc") (param i32 i32 i32) (result i32)
    local.get 0
    local.get 1
    local.get 2
    call_indirect (type $i32_i32_to_i32))
)
