;; Generated by 🤖
(module
  (table 1 funcref)
  (elem (i32.const 0) $add)
  
  (func $add (param i32 i32) (result i32)
    local.get 0
    local.get 1
    i32.add
)
    
  (func (export "run") (param i32 i32) (result i32)
    local.get 0
    local.get 1
    i32.const 0
    call_indirect (param i32 i32) (result i32)
  )
)
