// Generated by 🤖
import { testCallIndirect, testCallIndirectMulti, testCallIndirectLater } from "./call-indirect-test.mjs";
import { testRunner } from "../test-utils.mjs";

try {
    const results = await Promise.all([
        testRunner(testCallIndirect, "call-indirect", true),
        testRunner(testCallIndirectMulti, "call-indirect-multi", true),
        testRunner(testCallIndirectLater, "call-indirect-later", true)
    ]);
    
    if (results.includes(false)) {
        throw new Error("One or more tests failed");
    }
} catch (e) {
    console.error("Test failed:", e);
    process.exit(1);
}