import { testRunner } from "../test-utils.mjs";
// Generated by 🤖
import {
	testCallIndirect,
	testCallIndirectLater,
	testCallIndirectMulti,
} from "./call-indirect-test.mjs";

try {
	const results = await Promise.all([
		testRunner(testCallIndirect, "call-indirect", true),
		testRunner(testCallIndirectMulti, "call-indirect-multi", true),
		testRunner(testCallIndirectLater, "call-indirect-later", true),
	]);

	if (results.includes(false)) {
		throw new Error("One or more tests failed");
	}
} catch (e) {
	console.error("Test failed:", e);
	process.exit(1);
}
