(module
  ;; Define a memory section with 1 page (64KB)
  ;; Generated by 🤖
  (memory 1)
  
  ;; Export the memory
  ;; Generated by 🤖
  (export "memory" (memory 0))
  
  ;; Function that stores f32 to memory
  ;; Generated by 🤖
  (func $store_float (param $addr i32) (param $value f32)
    local.get $addr
    local.get $value
    f32.store
  )
  
  ;; Function that loads f32 from memory
  ;; Generated by 🤖
  (func $load_float (param $addr i32) (result f32)
    local.get $addr
    f32.load
  )
  
  ;; Store float at specified address and return it to verify
  ;; Generated by 🤖
  (func $store_and_load (param $addr i32) (param $value f32) (result f32)
    ;; Store the float
    local.get $addr
    local.get $value
    f32.store
    
    ;; Load it back
    local.get $addr
    f32.load
  )
  
  ;; Export functions
  ;; Generated by 🤖
  (export "store_float" (func $store_float))
  (export "load_float" (func $load_float))
  (export "store_and_load" (func $store_and_load))
)