(module
    (func (export "default")
        i32.const 42
        br_table 0
    )

    (func (export "early_exit") (result i32)
        i32.const 10 ;; return value
        i32.const 0
        br_table 0
        i32.const 100 ;; skipped
    )

    ;; Generated by 🤖
    (func (export "switch") (param i32) (result i32)
        block $default
        block $case0
            block $case1
            block $case2
                local.get 0
                br_table $case0 $case1 $case2 $default
            end
            i32.const 200
            return
            end
            i32.const 100
            return
        end
        i32.const 50
        return
        end
        i32.const 0
    )

    (func (export "switch_direct") (param i32) (result i32)
        block
        block
            block
            block
                local.get 0  ;; Get parameter value
                br_table 0 1 2 3  ;; Branch to blocks using indices directly
            end
            i32.const 100  ;; Case 0
            return
            end
            i32.const 200  ;; Case 1
            return
        end
        i32.const 300  ;; Case 2 
        return
        end
        i32.const 400  ;; Default case (3)
    )

    (;func (export "mixed_labels") (param i32) (result i32)
        block $end
        block $case1
            block
            local.get 0
            br_table 0 $case1 $end  ;; mix of index (0) and named labels
            end
            i32.const 10  ;; case 0
            return
        end
        i32.const 20  ;; case 1
        return
        end
        i32.const 30  ;; default case
    ;)
)