(module
  ;; Define a memory section with 1 page (64KB)
  ;; Generated by 🤖
  (memory 1)
  
  ;; Export the memory
  ;; Generated by 🤖
  (export "memory" (memory 0))
  
  ;; Initialize memory with floating point values
  ;; Generated by 🤖
  (data (i32.const 0) "\00\00\00\00\00\00\F0\3F\00\00\00\00\00\00\00\40\00\00\00\00\00\00\08\40\00\00\00\00\00\00\10\40")  ;; 1.0, 2.0, 3.0, 4.0 in IEEE-754 f64 format

  ;; Function that loads f64 from memory
  ;; Generated by 🤖
  (func $load_f64 (param $addr i32) (result f64)
    local.get $addr
    f64.load
  )
  
  ;; Export memory load function
  ;; Generated by 🤖
  (export "load_f64" (func $load_f64))
)