(module
    ;; Function that return a constnt f64 value
    (func (export "const_f64") (result f64)
        f64.const 1.0
    )
    
    ;; Function that returns a large constant f64 value
    (func (export "const_large_f64") (result f64)
        f64.const 1.7976931348623157e+308
    )

    ;; Function that returns a small constant f64 value
    (func (export "const_small_f64") (result f64)
        f64.const 2.2250738585072014e-308
    )
    ;; Function that performs f64 addition
    (func (export "add") (param $a f64) (param $b f64) (result f64)
        local.get $a
        local.get $b
        f64.add
    )
    
    ;; Function that performs f64 subtraction
    (func (export "sub") (param $a f64) (param $b f64) (result f64)
        local.get $a
        local.get $b
        f64.sub
    )
    
    ;; Function that performs f64 multiplication
    (func (export "mul") (param $a f64) (param $b f64) (result f64)
        local.get $a
        local.get $b
        f64.mul
    )
    
    ;; Function that performs f64 division
    (func (export "div") (param $a f64) (param $b f64) (result f64)
        local.get $a
        local.get $b
        f64.div
    )

    (func (export"abs") (param $a f64) (result f64)
        local.get $a
        f64.abs
    )

    (func (export "sqrt") (param $a f64) (result f64)
        local.get $a
        f64.sqrt
    )
    ;; Function that performs f64 negation
    (func (export "neg") (param $a f64) (result f64)
        local.get $a
        f64.neg
    )

    (func (export "min") (param $a f64) (param $b f64) (result f64)
        local.get $a
        local.get $b
        f64.min
    )
    (func (export "max") (param $a f64) (param $b f64) (result f64)
        local.get $a
        local.get $b
        f64.max
    )
    (func (export "copy_sign") (param $a f64) (param $b f64) (result f64)
        local.get $a
        local.get $b
        f64.copysign
    )
    (func (export "ceil") (param $a f64) (result f64)
        local.get $a
        f64.ceil
    )
    (func (export "floor") (param $a f64) (result f64)
        local.get $a
        f64.floor
    )
    (func (export "trunc") (param $a f64) (result f64)
        local.get $a
        f64.trunc
    )
    (func (export "nearest") (param $a f64) (result f64)
        local.get $a
        f64.nearest
    )
    
    ;; Function that tests f64 equality
    ;; Generated by 🤖
    (func (export "eq") (param $a f64) (param $b f64) (result i32)
        local.get $a
        local.get $b
        f64.eq
    )
    ;; Function that tests f64 inequality
    ;; Generated by 🤖
    (func (export "ne") (param $a f64) (param $b f64) (result i32)
        local.get $a
        local.get $b
        f64.ne
    )
    ;; Function that tests f64 less than
    ;; Generated by 🤖
    (func (export "lt") (param $a f64) (param $b f64) (result i32)
        local.get $a
        local.get $b
        f64.lt
    )
    ;; Function that tests f64 greater than
    ;; Generated by 🤖
    (func (export "gt") (param $a f64) (param $b f64) (result i32)
        local.get $a
        local.get $b
        f64.gt
    )
    ;; Function that tests f64 less than or equal
    ;; Generated by 🤖
    (func (export "le") (param $a f64) (param $b f64) (result i32)
        local.get $a
        local.get $b
        f64.le
    )
    ;; Function that tests f64 greater than or equal
    ;; Generated by 🤖
    (func (export "ge") (param $a f64) (param $b f64) (result i32)
        local.get $a
        local.get $b
        f64.ge
    )
)