(module
  (func (export "i32_trunc_f32_s") (param $a f32) (result i32)
    local.get $a
    i32.trunc_f32_s
  )
  
  (func (export "i32_trunc_f32_u") (param $a f32) (result i32)
    local.get $a
    i32.trunc_f32_u
  )

  (func (export "i32_trunc_f64_s") (param $a f64) (result i32)
    local.get $a
    i32.trunc_f64_s
  )
  
  (func (export "i32_trunc_f64_u") (param $a f64) (result i32)
    local.get $a
    i32.trunc_f64_u
  )

  (func (export "i32_reinterpret_f32") (param $a f32) (result i32)
    local.get $a
    i32.reinterpret_f32
  )
  
  (func (export "i32_trunc_sat_f32_s") (param $a f32) (result i32)
    local.get $a
    i32.trunc_sat_f32_s
  )
  
  (func (export "i32_trunc_sat_f32_u") (param $a f32) (result i32)
    local.get $a
    i32.trunc_sat_f32_u
  )
  
  (func (export "i32_extend8_s") (param $a i32) (result i32)
    local.get $a
    i32.extend8_s
  )
  
  (func (export "i32_extend16_s") (param $a i32) (result i32)
    local.get $a
    i32.extend16_s
  )

  ;; New functions for f32.convert_i32_s and f32.convert_i32_u
  (func (export "f32_convert_i32_s") (param $a i32) (result f32)
    local.get $a
    f32.convert_i32_s
  )
  
  (func (export "f32_convert_i32_u") (param $a i32) (result f32)
    local.get $a
    f32.convert_i32_u
  )

  (func (export "i32_wrap_i64") (param $a i64) (result i32)
    local.get $a
    i32.wrap_i64
  )

  ;; Generated by 🤖
  (func (export "i64_trunc_sat_f32_s") (param $a f32) (result i64)
    local.get $a
    i64.trunc_sat_f32_s
  )
  
  ;; Generated by 🤖
  (func (export "i64_trunc_sat_f32_u") (param $a f32) (result i64)
    local.get $a
    i64.trunc_sat_f32_u
  )
  
  ;; Generated by 🤖
  (func (export "i64_trunc_sat_f64_s") (param $a f64) (result i64)
    local.get $a
    i64.trunc_sat_f64_s
  )
  
  ;; Generated by 🤖
  (func (export "i64_trunc_sat_f64_u") (param $a f64) (result i64)
    local.get $a
    i64.trunc_sat_f64_u
  )
)
