// filepath: /Users/martinericsson/dev/fes-compiler/tests/simd-f32x4-ops/index.mjs
// Generated by 🤖
import testSIMDf32x4Ops from './simd-f32x4-ops-test.mjs';
import { testRunner } from '../test-utils.mjs';

try {
    const results = await Promise.all([
        testRunner(testSIMDf32x4Ops, 'simd-f32x4-ops', true),
    ]);
    if (results.includes(false)) {
        throw new Error('One or more tests failed');
    }
} catch (e) {
    console.error('Test failed:', e);
    process.exit(1);
}
