(module
  ;; Generated by 🤖
  (func $multi_value (export "multi_value") (result i32 i32)
    i32.const 1
    i32.const 2
  )
    
  ;; Block returning multiple values
  (func $multi_block (result i32 i64)
    block (result i32 i64)
      i32.const 42
      i64.const 7
    end)
  (export "multi_block" (func $multi_block))

  ;; If expression with multiple results
  (func $multi_if (param i32) (result i32 i64)
    local.get 0
    if (result i32 i64)
      i32.const 1
      i64.const 2
    else
      i32.const 3
      i64.const 4
    end)
  (export "multi_if" (func $multi_if))
  
  ;; Loop with multiple results
  (;func $multi_loop (param i32) (result i32 i64)
    loop $l (result i32 i64)
      local.get 0
      i32.const 1
      i32.sub
      local.tee 0
      i32.eqz
      if (result i32 i64)
        i32.const 42
        i64.const 100
      else
        br $l
      end
    end)
  (export "multi_loop" (func $multi_loop);)
  
  ;; BR with multiple values
  (func $multi_br (result i32 i64)
    block $b (result i32 i64)
      i32.const 5
      i64.const 6
      br $b
      i32.const 0
      i64.const 0
    end)
  (export "multi_br" (func $multi_br))
)