import { testRunner } from "../test-utils.mjs";
// Generated by 🤖
import testUnreachable from "./unreachable-test.mjs";

try {
	const results = await Promise.all([
		testRunner(testUnreachable, "unreachable", true),
	]);

	if (results.includes(false)) {
		throw new Error("One or more tests failed");
	}
} catch (e) {
	console.error("Test failed:", e);
	process.exit(1);
}
