// Generated by 🤖
import { readTestData } from '../test-utils.mjs';

async function testUnreachable(debug = false) {
  try {
    const { wasmBuffer } = await readTestData('unreachable/unreachable.wat');
    
    if(debug) console.log('AST:', JSON.stringify(ast, null, 2));
    
    // Instantiate the module
    const wasmModule = new WebAssembly.Module(wasmBuffer);
    const instance = new WebAssembly.Instance(wasmModule);
    
    if(debug) console.log('Exports:', Object.keys(instance.exports));
    
    // Test unreachable (should throw an exception)
    try {
      instance.exports.trap();
      console.error('❌ Unreachable did not trap!');
      return false;
    } catch (error) {
      console.log('✅ Unreachable correctly trapped with error:', error.message);
      return true;
    }
  } catch (error) {
    console.error('Test failed:', error);
    return false;
  }
}

export default testUnreachable;