// filepath: /Users/martinericsson/dev/fes-compiler/tests/simd-vector-ops/index.mjs
import { testRunner } from '../test-utils.mjs';
import testSIMDVectorOps from './simd-vector-ops-test.mjs';

try {
    await testRunner(testSIMDVectorOps, "simd-vector-ops", true);
} catch (error) {
    console.error(`Test failed: ${error.message}`);
    process.exit(1);
}
// Generated by 🤖
