(module
  (func (export "i8x16_shuffle0") (result i32)
    ;; Create two v128 constants
    v128.const i8x16 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
    v128.const i8x16 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
    
    ;; Shuffle the two vectors - selecting first byte from second vector (index 16)
    i8x16.shuffle 16 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
    
    ;; Extract the first lane (should be 16)
    i8x16.extract_lane_u 0
  )
) ;; Generated by 🤖
