import simdReplaceLaneTest from './simd-replace-lane-test.mjs';
import simdReplaceAllLaneTest from './simd-replace-lane-all-test.mjs';
import { testRunner } from '../test-utils.mjs';

try {
    const results = await Promise.all([
        testRunner(simdReplaceLaneTest, 'simd-replace-lane'),
        testRunner(simdReplaceAllLaneTest, 'simd-replace-lane-all')
    ]);
    
    if (results.includes(false)) {
        throw new Error('One or more tests failed');
    }
}
catch (error) {
    console.error('Error during SIMD replace_lane tests:', error);
    process.exit(1);
} // Generated by 🤖
