(module
  (func (export "i16x8_replace_lane_test") (result i32)
    ;; Create a v128 constant with all zeros
    v128.const i16x8 0 0 0 0 0 0 0 0
    
    ;; Replace lane 3 with value 12345
    i32.const 12345
    i16x8.replace_lane 3
    
    ;; Extract the modified lane to verify 
    i16x8.extract_lane_s 3
  )
  
  (func (export "i32x4_replace_lane_test") (result i32)
    ;; Create a v128 constant
    v128.const i32x4 0 0 0 0
    
    ;; Replace lane 2 with value 42424242
    i32.const 42424242
    i32x4.replace_lane 2
    
    ;; Extract the modified lane to verify
    i32x4.extract_lane 2
  )
  
  (func (export "i64x2_replace_lane_test") (result i64)
    ;; Create a v128 constant
    v128.const i64x2 0 0
    
    ;; Replace lane 1 with value 9876543210
    i64.const 9876543210
    i64x2.replace_lane 1
    
    ;; Extract the modified lane to verify 
    i64x2.extract_lane 1
  )
  
  (func (export "f32x4_replace_lane_test") (result f32)
    ;; Create a v128 constant 
    v128.const f32x4 0 0 0 0
    
    ;; Replace lane 0 with value 3.14159
    f32.const 3.14159
    f32x4.replace_lane 0
    
    ;; Extract the modified lane to verify
    f32x4.extract_lane 0
  )
  
  (func (export "f64x2_replace_lane_test") (result f64)
    ;; Create a v128 constant
    v128.const f64x2 0 0
    
    ;; Replace lane 1 with value 2.71828
    f64.const 2.71828
    f64x2.replace_lane 1
    
    ;; Extract the modified lane to verify
    f64x2.extract_lane 1
  )
) ;; Generated by 🤖
