(module
  (func (export "i8x16_replace_lane_test") (result i32)
    ;; Create a v128 constant with all zeros
    v128.const i8x16 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    
    ;; Push value 42 and then replace lane 5 with it
    i32.const 42
    i8x16.replace_lane 5
    
    ;; Extract the modified lane to verify it was replaced
    i8x16.extract_lane_s 5
  )
  
  (func (export "i8x16_replace_lane_multiple") (result i32)
    ;; Create a v128 constant with values 1-16
    v128.const i8x16 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
    
    ;; Push value 100 and then replace lane 0 with it
    i32.const 100
    i8x16.replace_lane 0
    
    ;; Push value 200 and then replace lane 15 with it
    i32.const 200
    i8x16.replace_lane 15
    
    ;; Extract lane 15 and return it (should be 200 but stored as -56 in i8)
    i8x16.extract_lane_s 15
  )
  
  (func (export "i8x16_replace_lane_negative") (result i32)
    ;; Create a v128 constant
    v128.const i8x16 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    
    ;; Push value -30 and then replace lane 10 with it
    i32.const -30
    i8x16.replace_lane 10
    
    ;; Extract the lane to verify it contains -30
    i8x16.extract_lane_s 10
  )
) ;; Generated by 🤖
