import { testRunner } from "../test-utils.mjs";
import testEscapedImportExportNames from "./escaped-names-test.mjs";
import testImportedFunctionOrdered from "./imported-functions-ordered-test.mjs";
// Generated by 🤖
import testImportedFunctions from "./imported-functions-test.mjs";

try {
	const results = await Promise.all([
		testRunner(testEscapedImportExportNames, "escaped-names", true),
		testRunner(testImportedFunctions, "imported-functions", true),
		testRunner(testImportedFunctionOrdered, "imported-functions-ordered", true),
	]);
	if (results.includes(false)) {
		throw new Error("One or more tests failed");
	}
} catch (e) {
	console.error("Test failed:", e);
	process.exit(1);
}
