(module
  ;; Function to convert a signed i64 to f64
  ;; Generated by 🤖
  (func $convert_i64_s_to_f64 (param $value i64) (result f64)
    local.get $value
    f64.convert_i64_s
  )
  
  ;; Function to convert an unsigned i64 to f64
  ;; Generated by 🤖
  (func $convert_i64_u_to_f64 (param $value i64) (result f64)
    local.get $value
    f64.convert_i64_u
  )
  
  ;; Function to test positive integer conversion (signed)
  ;; Generated by 🤖
  (func $test_positive (result f64)
    i64.const 42
    f64.convert_i64_s
  )
  
  ;; Function to test negative integer conversion (signed)
  ;; Generated by 🤖
  (func $test_negative (result f64)
    i64.const -42
    f64.convert_i64_s
  )
  
  ;; Function to test zero conversion (signed)
  ;; Generated by 🤖
  (func $test_zero (result f64)
    i64.const 0
    f64.convert_i64_s
  )
  
  ;; Function to test maximum i64 value (signed)
  ;; Generated by 🤖
  (func $test_max_i64 (result f64)
    i64.const 9223372036854775807 ;; 2^63 - 1
    f64.convert_i64_s
  )
  
  ;; Function to test minimum i64 value (signed)
  ;; Generated by 🤖
  (func $test_min_i64 (result f64)
    i64.const -9223372036854775808 ;; -2^63
    f64.convert_i64_s
  )
  
  ;; Function to test large positive value as unsigned
  ;; Generated by 🤖
  (func $test_unsigned_large (result f64)
    i64.const -1 ;; Will be treated as 18446744073709551615 (2^64 - 1) when unsigned
    f64.convert_i64_u
  )
  
  ;; Function to test medium value as unsigned
  ;; Generated by 🤖
  (func $test_unsigned_medium (result f64)
    i64.const 9223372036854775807 ;; 2^63 - 1
    f64.convert_i64_u
  )
  
  ;; Export functions
  ;; Generated by 🤖
  (export "convert_i64_s_to_f64" (func $convert_i64_s_to_f64))
  (export "convert_i64_u_to_f64" (func $convert_i64_u_to_f64))
  (export "test_positive" (func $test_positive))
  (export "test_negative" (func $test_negative))
  (export "test_zero" (func $test_zero))
  (export "test_max_i64" (func $test_max_i64))
  (export "test_min_i64" (func $test_min_i64))
  (export "test_unsigned_large" (func $test_unsigned_large))
  (export "test_unsigned_medium" (func $test_unsigned_medium))
)