import { testRunner } from "../test-utils.mjs";
// Generated by 🤖
import testAlignmentValidation from "./alignment-validation-test.mjs";

testRunner(testAlignmentValidation, "alignment validation", true);
