// filepath: /Users/martinericsson/dev/watranslator/tests/multi-memory/index.mjs
import { testRunner } from "../test-utils.mjs";
import testMultiMemoryMemargEncoding from "./memarg-encoding-test.mjs";
import testMultiMemoryIndexes from "./multi-memory-indexes-test.mjs"; // Generated by 🤖
import testMultiMemory from "./multi-memory-test.mjs";

try {
	const results = await Promise.all([
		testRunner(testMultiMemory, "multi-memory", true),
		testRunner(testMultiMemoryIndexes, "multi-memory-indexes", true), // Generated by 🤖
		testRunner(
			testMultiMemoryMemargEncoding,
			"multi-memory-memarg-encoding",
			true,
		),
	]);
	if (results.includes(false)) {
		throw new Error("One or more tests failed");
	}
} catch (e) {
	console.error("❌ Test failed:", e);
	process.exit(1);
}
