(module
  ;; Import memory instances instead of defining them
  (import "" "memory0" (memory 1))
  (import "" "memory1" (memory 2))

  ;; Function to store a value in memory 0 (default)
  (func $storeInMem0 (param $addr i32) (param $value i32)
    local.get $addr
    local.get $value
    i32.store
  )

  ;; Function to load a value from memory 0 (default)
  (func $loadFromMem0 (param $addr i32) (result i32)
    local.get $addr
    i32.load
  )

  ;; Function to store a value in memory 1 (using the default memory)
  (func $storeInMem1 (param $addr i32) (param $value i32)
    local.get $addr
    local.get $value
    i32.store
  )

  ;; Function to load a value from memory 1 (using the default memory)
  (func $loadFromMem1 (param $addr i32) (result i32)
    local.get $addr
    i32.load
  )

  ;; Export the functions
  (export "storeInMem0" (func $storeInMem0))
  (export "loadFromMem0" (func $loadFromMem0))
  (export "storeInMem1" (func $storeInMem1))
  (export "loadFromMem1" (func $loadFromMem1))
) ;; Generated by 🤖