(module
  ;; Import memory instances instead of defining them
  (import "" "memory0" (memory 1))
  (import "" "memory1" (memory 2))
  
  ;; Function to store a value in memory 0
  (func (export "storeInMem0") (param $addr i32) (param $value i32)
    local.get $addr
    local.get $value
    i32.store
  )
  
  ;; Function to load a value from memory 0
  (func (export "loadFromMem0") (param $addr i32) (result i32)
    local.get $addr
    i32.load
  )
  
  ;; Function to store a value in memory 1
  (func (export "storeInMem1") (param $addr i32) (param $value i32)
    local.get $addr
    local.get $value
    i32.store
  )
  
  ;; Function to load a value from memory 1
  (func (export "loadFromMem1") (param $addr i32) (result i32)
    local.get $addr
    i32.load
  )
) ;; Generated by 🤖