// Generated by 🤖
import { encodeULEB128 } from "../compile-utils.mjs";
import { addMapping } from "../../sourcemap.mjs";
// Assuming wasmConstants.INSTR might define these, or using literals directly.
const ATOMIC_PREFIX = 0xFE;

// RMW Add operations
const ATOMIC_RMW_ADD_I32 = 0x1E; const ATOMIC_RMW_ADD_I64 = 0x1F;
const ATOMIC_RMW8_ADD_U_I32 = 0x20; const ATOMIC_RMW16_ADD_U_I32 = 0x21;
const ATOMIC_RMW8_ADD_U_I64 = 0x22; const ATOMIC_RMW16_ADD_U_I64 = 0x23; const ATOMIC_RMW32_ADD_U_I64 = 0x24;
// RMW Sub operations
const ATOMIC_RMW_SUB_I32 = 0x25; const ATOMIC_RMW_SUB_I64 = 0x26;
const ATOMIC_RMW8_SUB_U_I32 = 0x27; const ATOMIC_RMW16_SUB_U_I32 = 0x28;
const ATOMIC_RMW8_SUB_U_I64 = 0x29; const ATOMIC_RMW16_SUB_U_I64 = 0x2A; const ATOMIC_RMW32_SUB_U_I64 = 0x2B;
// RMW And operations
const ATOMIC_RMW_AND_I32 = 0x2C; const ATOMIC_RMW_AND_I64 = 0x2D;
const ATOMIC_RMW8_AND_U_I32 = 0x2E; const ATOMIC_RMW16_AND_U_I32 = 0x2F;
const ATOMIC_RMW8_AND_U_I64 = 0x30; const ATOMIC_RMW16_AND_U_I64 = 0x31; const ATOMIC_RMW32_AND_U_I64 = 0x32;
// RMW Or operations
const ATOMIC_RMW_OR_I32 = 0x33; const ATOMIC_RMW_OR_I64 = 0x34;
const ATOMIC_RMW8_OR_U_I32 = 0x35; const ATOMIC_RMW16_OR_U_I32 = 0x36;
const ATOMIC_RMW8_OR_U_I64 = 0x37; const ATOMIC_RMW16_OR_U_I64 = 0x38; const ATOMIC_RMW32_OR_U_I64 = 0x39;
// RMW Xor operations
const ATOMIC_RMW_XOR_I32 = 0x3A; const ATOMIC_RMW_XOR_I64 = 0x3B;
const ATOMIC_RMW8_XOR_U_I32 = 0x3C; const ATOMIC_RMW16_XOR_U_I32 = 0x3D;
const ATOMIC_RMW8_XOR_U_I64 = 0x3E; const ATOMIC_RMW16_XOR_U_I64 = 0x3F; const ATOMIC_RMW32_XOR_U_I64 = 0x40;
// RMW Xchg operations
const ATOMIC_RMW_XCHG_I32 = 0x41; const ATOMIC_RMW_XCHG_I64 = 0x42;
const ATOMIC_RMW8_XCHG_U_I32 = 0x43; const ATOMIC_RMW16_XCHG_U_I32 = 0x44;
const ATOMIC_RMW8_XCHG_U_I64 = 0x45; const ATOMIC_RMW16_XCHG_U_I64 = 0x46; const ATOMIC_RMW32_XCHG_U_I64 = 0x47;
// RMW Cmpxchg operations
const ATOMIC_RMW_CMPXCHG_I32 = 0x48; const ATOMIC_RMW_CMPXCHG_I64 = 0x49;
const ATOMIC_RMW8_CMPXCHG_U_I32 = 0x4A; const ATOMIC_RMW16_CMPXCHG_U_I32 = 0x4B;
const ATOMIC_RMW8_CMPXCHG_U_I64 = 0x4C; const ATOMIC_RMW16_CMPXCHG_U_I64 = 0x4D; const ATOMIC_RMW32_CMPXCHG_U_I64 = 0x4E;
// Fence
const ATOMIC_FENCE = 0x03;

const ATOMIC_INSTR_MAP = new Map([
    ['i32.atomic.rmw.add', ATOMIC_RMW_ADD_I32], ['i64.atomic.rmw.add', ATOMIC_RMW_ADD_I64],
    ['i32.atomic.rmw8.add_u', ATOMIC_RMW8_ADD_U_I32], ['i32.atomic.rmw16.add_u', ATOMIC_RMW16_ADD_U_I32],
    ['i64.atomic.rmw8.add_u', ATOMIC_RMW8_ADD_U_I64], ['i64.atomic.rmw16.add_u', ATOMIC_RMW16_ADD_U_I64], ['i64.atomic.rmw32.add_u', ATOMIC_RMW32_ADD_U_I64],
    ['i32.atomic.rmw.sub', ATOMIC_RMW_SUB_I32], ['i64.atomic.rmw.sub', ATOMIC_RMW_SUB_I64],
    ['i32.atomic.rmw8.sub_u', ATOMIC_RMW8_SUB_U_I32], ['i32.atomic.rmw16.sub_u', ATOMIC_RMW16_SUB_U_I32],
    ['i64.atomic.rmw8.sub_u', ATOMIC_RMW8_SUB_U_I64], ['i64.atomic.rmw16.sub_u', ATOMIC_RMW16_SUB_U_I64], ['i64.atomic.rmw32.sub_u', ATOMIC_RMW32_SUB_U_I64],
    ['i32.atomic.rmw.and', ATOMIC_RMW_AND_I32], ['i64.atomic.rmw.and', ATOMIC_RMW_AND_I64],
    ['i32.atomic.rmw8.and_u', ATOMIC_RMW8_AND_U_I32], ['i32.atomic.rmw16.and_u', ATOMIC_RMW16_AND_U_I32],
    ['i64.atomic.rmw8.and_u', ATOMIC_RMW8_AND_U_I64], ['i64.atomic.rmw16.and_u', ATOMIC_RMW16_AND_U_I64], ['i64.atomic.rmw32.and_u', ATOMIC_RMW32_AND_U_I64],
    ['i32.atomic.rmw.or', ATOMIC_RMW_OR_I32], ['i64.atomic.rmw.or', ATOMIC_RMW_OR_I64],
    ['i32.atomic.rmw8.or_u', ATOMIC_RMW8_OR_U_I32], ['i32.atomic.rmw16.or_u', ATOMIC_RMW16_OR_U_I32],
    ['i64.atomic.rmw8.or_u', ATOMIC_RMW8_OR_U_I64], ['i64.atomic.rmw16.or_u', ATOMIC_RMW16_OR_U_I64], ['i64.atomic.rmw32.or_u', ATOMIC_RMW32_OR_U_I64],
    ['i32.atomic.rmw.xor', ATOMIC_RMW_XOR_I32], ['i64.atomic.rmw.xor', ATOMIC_RMW_XOR_I64],
    ['i32.atomic.rmw8.xor_u', ATOMIC_RMW8_XOR_U_I32], ['i32.atomic.rmw16.xor_u', ATOMIC_RMW16_XOR_U_I32],
    ['i64.atomic.rmw8.xor_u', ATOMIC_RMW8_XOR_U_I64], ['i64.atomic.rmw16.xor_u', ATOMIC_RMW16_XOR_U_I64], ['i64.atomic.rmw32.xor_u', ATOMIC_RMW32_XOR_U_I64],
    ['i32.atomic.rmw.xchg', ATOMIC_RMW_XCHG_I32], ['i64.atomic.rmw.xchg', ATOMIC_RMW_XCHG_I64],
    ['i32.atomic.rmw8.xchg_u', ATOMIC_RMW8_XCHG_U_I32], ['i32.atomic.rmw16.xchg_u', ATOMIC_RMW16_XCHG_U_I32],
    ['i64.atomic.rmw8.xchg_u', ATOMIC_RMW8_XCHG_U_I64], ['i64.atomic.rmw16.xchg_u', ATOMIC_RMW16_XCHG_U_I64], ['i64.atomic.rmw32.xchg_u', ATOMIC_RMW32_XCHG_U_I64],
    ['i32.atomic.rmw.cmpxchg', ATOMIC_RMW_CMPXCHG_I32], ['i64.atomic.rmw.cmpxchg', ATOMIC_RMW_CMPXCHG_I64],
    ['i32.atomic.rmw8.cmpxchg_u', ATOMIC_RMW8_CMPXCHG_U_I32], ['i32.atomic.rmw16.cmpxchg_u', ATOMIC_RMW16_CMPXCHG_U_I32],
    ['i64.atomic.rmw8.cmpxchg_u', ATOMIC_RMW8_CMPXCHG_U_I64], ['i64.atomic.rmw16.cmpxchg_u', ATOMIC_RMW16_CMPXCHG_U_I64], ['i64.atomic.rmw32.cmpxchg_u', ATOMIC_RMW32_CMPXCHG_U_I64],
]);

export function compileAtomicOps(instr, func, binary, module) { // Changed body to binary
    const instrType = instr.op || instr.type;

    if (instrType === 'atomic.fence') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(ATOMIC_PREFIX);
        binary.push(ATOMIC_FENCE);
        binary.push(0x00); // Reserved byte for fence
        return true;
    }

    if (!ATOMIC_INSTR_MAP.has(instrType)) {
        return false;
    }

    if (instr.loc && instr.loc.line != null) {
        addMapping(instr.loc.line, instr.loc.column, binary.length);
    }
    binary.push(ATOMIC_PREFIX);
    binary.push(ATOMIC_INSTR_MAP.get(instrType));
    
    // Determine default alignment based on the instruction type string
    let defaultAlign = 2; // For i32
    if (instrType.startsWith('i64.')) defaultAlign = 3; // For i64

    if (instrType.includes('rmw8')) defaultAlign = 0;
    else if (instrType.includes('rmw16')) defaultAlign = 1;
    else if (instrType.includes('rmw32')) defaultAlign = 2;
    
    // AST should provide memarg: { offset, align } from the parser if specified
    const align = instr.memarg && instr.memarg.align != null ? instr.memarg.align : defaultAlign;
    const offset = instr.memarg && instr.memarg.offset != null ? instr.memarg.offset : 0;

    // TODO: Validate alignment against natural alignment if necessary

    binary.push(...encodeULEB128(align));
    binary.push(...encodeULEB128(offset));
    
    return true;
}