// Generated by 🤖
import wasmConstants from "../constants.mjs";
import { addMapping } from "../../sourcemap.mjs";
import {
    encodeULEB128,
    encodeSLEB128,
    getWasmType,
    getLabelIndex
} from "../compile-utils.mjs";
import { createError } from "./error.mjs";
import { compileInstruction } from "./instructions.mjs";

const {
    INSTR,
    TYPE
} = wasmConstants;

export function compileControlFlow(instr, func, binary, moduleFunctions, moduleGlobals, module) {
    // Note: addMapping for the main instruction (e.g. 'if', 'block', 'loop', 'br')
    // should be called *before* the opcode itself is pushed to binary.

    if (instr.type === 'select_t') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.SELECT_T);
        binary.push(0x01); // Vector length (1 type)
        if (instr.resultType) {
            try {
                binary.push(getWasmType(instr.resultType));
            } catch (err) {
                throw createError(instr, func, module, `Invalid select_t result type: ${instr.resultType}`);
            }
        } else {
            binary.push(TYPE.I32); // Default if type not specified (though select_t implies type)
        }
        return true;
    }

    if (instr.type === 'block' || instr.type === 'loop') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(instr.type === 'block' ? INSTR.BLOCK : INSTR.LOOP);

        if (instr.typeIndex !== undefined) {
            binary.push(...encodeSLEB128(instr.typeIndex));
        } else if (instr.resultType) {
            try {
                binary.push(getWasmType(instr.resultType));
            } catch (err) {
                throw createError(instr, func, module, `Invalid ${instr.type} result type: ${instr.resultType}`);
            }
        } else {
            binary.push(TYPE.BLOCK_VOID);
        }

        if (instr.instructions) { // Ensure instructions array exists
            for (const nestedInstr of instr.instructions) {
                compileInstruction(nestedInstr, func, binary, moduleFunctions, moduleGlobals, module);
            }
        }
        
        if (instr.endLoc && instr.endLoc.line != null) { // Assuming endLoc was added by parser
            addMapping(instr.endLoc.line, instr.endLoc.column, binary.length);
        }
        binary.push(INSTR.END);
        return true;
    }

    if (instr.type === 'if') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.IF);

        if (instr.typeIndex !== undefined) {
            binary.push(...encodeSLEB128(instr.typeIndex));
        } else if (instr.resultType) {
            try {
                binary.push(getWasmType(instr.resultType));
            } catch (err) {
                throw createError(instr, func, module, `Invalid if result type: ${instr.resultType}`);
            }
        } else {
            binary.push(TYPE.BLOCK_VOID);
        }

        if (instr.thenInstructions) { // Ensure array exists
            for (const thenInstr of instr.thenInstructions) {
                compileInstruction(thenInstr, func, binary, moduleFunctions, moduleGlobals, module);
            }
        }

        if (instr.elseInstructions && instr.elseInstructions.length > 0) {
            if (instr.elseLoc && instr.elseLoc.line != null) { // Assuming elseLoc was added by parser
                 addMapping(instr.elseLoc.line, instr.elseLoc.column, binary.length);
            }
            binary.push(INSTR.ELSE);
            for (const elseInstr of instr.elseInstructions) {
                compileInstruction(elseInstr, func, binary, moduleFunctions, moduleGlobals, module);
            }
        }
        
        if (instr.endLoc && instr.endLoc.line != null) { // Assuming endLoc was added by parser
             addMapping(instr.endLoc.line, instr.endLoc.column, binary.length);
        }
        binary.push(INSTR.END);
        return true;
    }

    if (instr.type === 'br') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.BR);
        try {
            const labelIndex = getLabelIndex(instr.label, func); // instr.label is string value
            binary.push(...encodeULEB128(labelIndex));
        } catch (err) {
            throw createError(instr, func, module, `Invalid branch target: ${instr.label}. ${err.message}`);
        }
        return true;
    }

    if (instr.type === 'br_if') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.BR_IF);
        try {
            const labelIndex = getLabelIndex(instr.label, func);
            binary.push(...encodeULEB128(labelIndex));
        } catch (err) {
            throw createError(instr, func, module, `Invalid conditional branch target: ${instr.label}. ${err.message}`);
        }
        return true;
    }

    if (instr.type === 'br_table') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.BR_TABLE);
        try {
            binary.push(...encodeULEB128(instr.labels.length)); // Vector count of labels
            for (const label of instr.labels) { // instr.labels is array of string values
                const labelIndex = getLabelIndex(label, func);
                binary.push(...encodeULEB128(labelIndex));
            }
            const defaultLabelIndex = getLabelIndex(instr.defaultLabel, func); // instr.defaultLabel is string value
            binary.push(...encodeULEB128(defaultLabelIndex));
        } catch (err) {
            throw createError(instr, func, module, `Invalid branch table target: ${err.message}.`);
        }
        return true;
    }
    
    // Instructions like 'return', 'unreachable', 'nop' are handled by compileStackInstruction usually.
    // If they need specific handling here or if compileStackInstruction is too generic:
    if (instr.type === 'return') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.RETURN);
        return true;
    }
     if (instr.type === 'unreachable') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.UNREACHABLE);
        return true;
    }
     if (instr.type === 'nop') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.NOP);
        return true;
    }


    return false; 
}