import {
	encodeSLEB128,
	encodeULEB128,
	getWasmType,
} from "../compile-utils.mjs";
import { INSTR, TYPE } from "../constants.mjs";
import { createError } from "./error.mjs";
import { compileInstruction } from "./instructions.mjs";

const getBranchDepth = (label, depth) => {
	if (typeof depth === "number" && depth >= 0) {
		return depth;
	}
	throw new Error(`Unresolved branch target: ${label}`);
};

/**
 * Record source map entry before emitting opcode bytes
 */
function recordSourceMap(
	instr,
	sourceMapManager,
	funcIndex,
	body,
	options,
	position = null,
) {
	if (sourceMapManager && funcIndex !== null) {
		const pos = position || instr.position;
		if (pos) {
			const filename = options.filename || "input.wat";
			sourceMapManager.addMapping({
				file: filename,
				line: pos.line - 1, // Convert to 0-based
				column: pos.column - 1, // Convert to 0-based
				funcIndex: funcIndex,
				bodyOffset: body.length,
			});
		}
	}
}

export function compileControlFlow(
	instr,
	func,
	body,
	moduleFunctions,
	moduleGlobals,
	module,
	sourceMapManager = null,
	funcIndex = null,
	options = {},
) {
	if (instr.op === "select_t") {
		// Handle typed select instruction: select (result <type>)
		body.push(INSTR.SELECT_T);

		// For select_t, we need to provide the vector of types (currently always 1)
		body.push(0x01); // Vector length (1 type)

		// Add the result type
		if (instr.resultType) {
			try {
				body.push(getWasmType(instr.resultType));
			} catch (err) {
				throw createError(
					instr,
					func,
					module,
					`Invalid select_t result type: ${instr.resultType}`,
				);
			}
		} else {
			// Default to i32 if type not specified
			body.push(TYPE.I32);
		}

		return true;
	}

	if (instr.op === "block") {
		// Record source map for block start
		recordSourceMap(instr, sourceMapManager, funcIndex, body, options);

		body.push(INSTR.BLOCK);

		// Generated by 🤖
		// For multi-value blocks, we need to use a function type index
		if (instr.typeIndex !== undefined) {
			// Use the type index assigned during type section generation
			body.push(...encodeSLEB128(instr.typeIndex));
		} else if (instr.resultType) {
			try {
				// Single result type
				body.push(getWasmType(instr.resultType));
			} catch (err) {
				throw createError(
					instr,
					func,
					module,
					`Invalid block result type: ${instr.resultType}`,
				);
			}
		} else {
			body.push(TYPE.BLOCK_VOID); // No value type
		}

		// Recursively compile instructions inside the block
		for (const nestedInstr of instr.instructions) {
			compileInstruction(
				nestedInstr,
				func,
				body,
				moduleFunctions,
				moduleGlobals,
				module,
				sourceMapManager,
				funcIndex,
				options,
			);
		}

		// Record source map for block end
		if (instr.endPosition) {
			recordSourceMap(
				instr,
				sourceMapManager,
				funcIndex,
				body,
				options,
				instr.endPosition,
			);
		}

		// End block
		body.push(INSTR.END);

		return true;
	}

	if (instr.op === "loop") {
		// Record source map for loop start
		recordSourceMap(instr, sourceMapManager, funcIndex, body, options);

		body.push(INSTR.LOOP);

		// Generated by 🤖
		// For multi-value loops, we need to use a function type index
		if (instr.typeIndex !== undefined) {
			// Use the type index assigned during type section generation
			body.push(...encodeSLEB128(instr.typeIndex));
		} else if (instr.resultType) {
			try {
				// Single result type
				body.push(getWasmType(instr.resultType));
			} catch (err) {
				throw createError(
					instr,
					func,
					module,
					`Invalid loop result type: ${instr.resultType}`,
				);
			}
		} else {
			body.push(TYPE.BLOCK_VOID); // No value type
		}

		// Recursively compile instructions inside the loop
		for (const nestedInstr of instr.instructions) {
			compileInstruction(
				nestedInstr,
				func,
				body,
				moduleFunctions,
				moduleGlobals,
				module,
				sourceMapManager,
				funcIndex,
				options,
			);
		}

		// Record source map for loop end
		if (instr.endPosition) {
			recordSourceMap(
				instr,
				sourceMapManager,
				funcIndex,
				body,
				options,
				instr.endPosition,
			);
		}

		// End loop
		body.push(INSTR.END);

		return true;
	}

	if (instr.op === "if") {
		// Record source map for if start
		recordSourceMap(instr, sourceMapManager, funcIndex, body, options);

		body.push(INSTR.IF);

		// Generated by 🤖
		// For multi-value ifs, we need to use a function type index
		if (instr.typeIndex !== undefined) {
			// Use the type index assigned during type section generation
			body.push(...encodeSLEB128(instr.typeIndex));
		} else if (instr.resultType) {
			try {
				// Single result type
				body.push(getWasmType(instr.resultType));
			} catch (err) {
				throw createError(
					instr,
					func,
					module,
					`Invalid if result type: ${instr.resultType}`,
				);
			}
		} else {
			body.push(TYPE.BLOCK_VOID); // No value type
		}

		// Compile then branch instructions
		for (const thenInstr of instr.thenInstructions) {
			compileInstruction(
				thenInstr,
				func,
				body,
				moduleFunctions,
				moduleGlobals,
				module,
				sourceMapManager,
				funcIndex,
				options,
			);
		}

		// If there are else branch instructions, add else opcode and compile them
		if (instr.elseInstructions && instr.elseInstructions.length > 0) {
			// Record source map for else
			if (instr.elsePosition) {
				recordSourceMap(
					instr,
					sourceMapManager,
					funcIndex,
					body,
					options,
					instr.elsePosition,
				);
			}

			body.push(INSTR.ELSE);

			for (const elseInstr of instr.elseInstructions) {
				compileInstruction(
					elseInstr,
					func,
					body,
					moduleFunctions,
					moduleGlobals,
					module,
					sourceMapManager,
					funcIndex,
					options,
				);
			}
		}

		// Record source map for if end
		if (instr.endPosition) {
			recordSourceMap(
				instr,
				sourceMapManager,
				funcIndex,
				body,
				options,
				instr.endPosition,
			);
		}

		// End if
		body.push(INSTR.END);

		return true;
	}

	if (instr.op === "br") {
		body.push(INSTR.BR);

		try {
			const labelIndex = getBranchDepth(instr.label, instr.labelDepth);
			body.push(...encodeULEB128(labelIndex));
		} catch (err) {
			throw createError(
				instr,
				func,
				module,
				`Invalid branch target: ${instr.label}. Make sure the label exists in the current scope.`,
			);
		}

		return true;
	}

	if (instr.op === "br_if") {
		body.push(INSTR.BR_IF);

		try {
			const labelIndex = getBranchDepth(instr.label, instr.labelDepth);
			body.push(...encodeULEB128(labelIndex));
		} catch (err) {
			throw createError(
				instr,
				func,
				module,
				`Invalid conditional branch target: ${instr.label}. Make sure the label exists in the current scope.`,
			);
		}

		return true;
	}

	if (instr.op === "br_table") {
		// Generated by 🤖
		body.push(INSTR.BR_TABLE);

		try {
			// Add the vector count of labels
			body.push(...encodeULEB128(instr.labels.length));

			// Add each label's depth
			for (let i = 0; i < instr.labels.length; i++) {
				const label = instr.labels[i];
				const labelIndex = getBranchDepth(label, instr.labelDepths?.[i]);
				body.push(...encodeULEB128(labelIndex));
			}

			// Add the default label's depth
			const defaultLabelIndex = getBranchDepth(
				instr.defaultLabel,
				instr.defaultLabelDepth,
			);
			body.push(...encodeULEB128(defaultLabelIndex));
		} catch (err) {
			throw createError(
				instr,
				func,
				module,
				`Invalid branch table target: ${err.message}. Make sure all branch labels exist in the current scope.`,
			);
		}

		return true;
	}

	return false; // No control flow instruction matched
}
