// Generated by 🤖
import wasmConstants from "../constants.mjs";
import { encodeULEB128 } from "../compile-utils.mjs";
import { createError } from "./error.mjs";
import { addMapping } from "../../sourcemap.mjs";

const {
    INSTR
} = wasmConstants;

export function compileFunctionCall(instr, binary, module, func, moduleFunctions) { // Changed body to binary
    if (instr.type === 'call') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.CALL);

        let funcIndex = -1;
        const funcIdentifier = instr.functionName || instr.funcIdentifier; // AST might use either

        if (typeof funcIdentifier === 'string' && funcIdentifier.startsWith('$')) {
            funcIndex = moduleFunctions.findIndex(f => f.name === funcIdentifier);
        } else {
            funcIndex = Number.parseInt(funcIdentifier, 10);
            if (Number.isNaN(funcIndex)) {
                 throw createError(instr, func, module, `Invalid function index: ${funcIdentifier}`);
            }
        }

        if (funcIndex === -1 || funcIndex >= moduleFunctions.length) {
            throw createError(instr, func, module, `Unknown function: ${funcIdentifier}.`);
        }
        
        // TODO: Type checking for function parameters (requires stack tracking)

        binary.push(...encodeULEB128(funcIndex));
        return true;
    }

    if (instr.type === 'call_indirect') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.CALL_INDIRECT);

        try {
            let typeIndex = 0; // Default to type index 0 for MVP if not specified or found

            // instr.typeRef could be a string name (e.g., "$sig") or a direct numeric index.
            // The parser for call_indirect was updated to store typeRef (name) and tableIndex.
            // AST node: { type: 'call_indirect', typeRef: string | number, typeRefLoc?, tableIndex: number, tableIndexLoc?, paramsInfo?, resultsInfo?, loc }
            
            if (instr.typeRef != null) { // AST stores the $name or number in typeRef
                if (typeof instr.typeRef === 'string' && instr.typeRef.startsWith('$')) {
                    if (module && module.types) {
                        const typeEntryIndex = module.types.findIndex(t => t.name === instr.typeRef);
                        if (typeEntryIndex !== -1) {
                            typeIndex = typeEntryIndex;
                        } else {
                            throw createError(instr, func, module, `Unknown type reference: ${instr.typeRef}`);
                        }
                    } else {
                        throw createError(instr, func, module, `No types defined in module, cannot resolve type reference: ${instr.typeRef}`);
                    }
                } else if (typeof instr.typeRef === 'number') {
                    typeIndex = instr.typeRef;
                } else {
                     // If typeRef is not a name or number, but params/results are directly on instr (older AST?)
                     // This path might be less common with current parser that favors typeRef.
                     // For now, assume typeRef is primary. If it's null, and old AST had instr.params,
                     // a more complex type matching/creation would be needed.
                     // Defaulting to 0 if no valid typeRef found or if not specified.
                     console.warn(`call_indirect: typeRef '${instr.typeRef}' not directly usable as index or name. Defaulting type index to 0. AST should provide a numeric type index or a resolvable name.`);
                }
            }
            // TODO: If instr.typeRef is null, but instr.params/results are defined, a type matching logic
            // would be needed here to find or create a matching type index. This is complex.
            // For now, if typeRef is not directly providing an index, it defaults to 0.
            // This implies the AST from parsing should ideally resolve typeRef to an index.

            binary.push(...encodeULEB128(typeIndex));
            
            // Table index (MVP: must be 0x00)
            // The parser was updated to provide tableIndex on instr if specified.
            const tableIdx = instr.tableIndex != null ? instr.tableIndex : 0;
             if (typeof tableIdx !== 'number' || tableIdx !== 0) { // MVP restriction
                const errLoc = instr.tableIndexLoc || instr.loc;
                throw createError(instr, func, module, `call_indirect table index must be 0 in MVP, got ${tableIdx}.`, errLoc? errLoc.line:null, errLoc?errLoc.column:null);
            }
            binary.push(...encodeULEB128(tableIdx)); // Should be 0x00

            return true;
        } catch (err) {
            // If createError was already thrown, rethrow it. Otherwise, wrap.
            if (err.message.startsWith("PARSE ERROR") || err.message.startsWith("COMPILE ERROR")) throw err;
            throw createError(instr, func, module, `Invalid indirect call: ${err.message}`);
        }
    }

    return false;
}