import { compileAtomicLoadStore } from "./atomic-load-store.mjs";
import { compileAtomicOps } from "./atomic-ops.mjs";
import { compileAtomicWaitNotify } from "./atomic-wait-notify.mjs";
import { compileControlFlow } from "./control-flow.mjs";
import { createError } from "./error.mjs";
import { compileFunctionCall } from "./function-call.mjs";
import { compileMemoryAccess } from "./memory-access.mjs";
import { compileMemoryInstruction } from "./memory.mjs";
import { compileNonTrappingFloatToInt } from "./non-trapping-float-to-int.mjs";
import { compileReferenceOpcodes } from "./reference-operation.mjs";
import { compileSIMDLaneBased } from "./simd-lane-based.mjs";
import { compileSIMDMemory } from "./simd-memory.mjs";
import { compileSIMDPlainOpcode } from "./simd-plain-opcode.mjs"; // Generated by 🤖
import { compileStackInstruction } from "./stack-instruction.mjs";
import { compileTableInstruction } from "./table.mjs";
import { compileVariableAccess } from "./variable-access.mjs";
import { compileVariableConstants } from "./variable-constants.mjs";

/**
 * Record source map entry before emitting opcode bytes
 */
function recordSourceMap(instr, sourceMapManager, funcIndex, body, options) {
	if (sourceMapManager && instr.position && funcIndex !== null) {
		const filename = options.filename || "input.wat";
		sourceMapManager.addMapping({
			file: filename,
			line: instr.position.line - 1, // Convert to 0-based
			column: instr.position.column - 1, // Convert to 0-based
			funcIndex: funcIndex,
			bodyOffset: body.length,
		});
	}
}

export function compileInstruction(
	instr,
	func,
	body,
	moduleFunctions,
	moduleGlobals,
	module,
	sourceMapManager = null,
	funcIndex = null,
	options = {},
) {
	// Record source map for this instruction
	recordSourceMap(instr, sourceMapManager, funcIndex, body, options);

	// Handler order is significant (e.g. SIMD-memory must precede SIMD-plain).
	const handlers = [
		() => compileVariableAccess(instr, func, body, moduleGlobals, module),
		() => compileVariableConstants(instr, body),
		() =>
			compileControlFlow(
				instr,
				func,
				body,
				moduleFunctions,
				moduleGlobals,
				module,
				sourceMapManager,
				funcIndex,
				options,
			),
		() => compileStackInstruction(instr, body),
		() => compileMemoryAccess(instr, func, body, module),
		() => compileMemoryInstruction(instr, body, module),
		() => compileFunctionCall(instr, body, module, func, moduleFunctions),
		() => compileTableInstruction(instr, func, module, body),
		() => compileReferenceOpcodes(instr, func, module, body),
		() => compileAtomicLoadStore(instr, func, body, module),
		() => compileAtomicWaitNotify(instr, func, body, module),
		() => compileAtomicOps(instr, func, body, module),
		() => compileSIMDLaneBased(instr, body),
		() => compileNonTrappingFloatToInt(instr, body),
		() => compileSIMDMemory(instr, body),
		() => compileSIMDPlainOpcode(instr, body),
	];

	for (const handle of handlers) {
		if (handle()) return;
	}

	throw createError(
		instr,
		func,
		module,
		`Unsupported instruction type: ${instr.op}. Check for typos or refer to the WebAssembly specification.`,
	);
}
