import {
	encodeULEB128,
	getInstructionNaturalAlignment,
} from "../compile-utils.mjs";
import wasmConstants from "../constants.mjs";
import { createError } from "./error.mjs";

const { INSTR } = wasmConstants;

const MEMORY_ACCESS_INSTR = new Map([
	["i32.load", INSTR.I32_LOAD],
	["i32.load8_s", INSTR.I32_LOAD8_S],
	["i32.load8_u", INSTR.I32_LOAD8_U],
	["i32.load16_s", INSTR.I32_LOAD16_S],
	["i32.load16_u", INSTR.I32_LOAD16_U],
	["i64.load", INSTR.I64_LOAD],
	["i64.load8_s", INSTR.I64_LOAD8_S],
	["i64.load8_u", INSTR.I64_LOAD8_U],
	["i64.load16_s", INSTR.I64_LOAD16_S],
	["i64.load16_u", INSTR.I64_LOAD16_U],
	["i64.load32_s", INSTR.I64_LOAD32_S],
	["i64.load32_u", INSTR.I64_LOAD32_U],
	["f32.load", INSTR.F32_LOAD],
	["f64.load", INSTR.F64_LOAD],
	["i32.store", INSTR.I32_STORE],
	["i32.store8", INSTR.I32_STORE8],
	["i32.store16", INSTR.I32_STORE16],
	["i64.store", INSTR.I64_STORE],
	["i64.store8", INSTR.I64_STORE8],
	["i64.store16", INSTR.I64_STORE16],
	["i64.store32", INSTR.I64_STORE32],
	["f32.store", INSTR.F32_STORE],
	["f64.store", INSTR.F64_STORE],
]);

// Modified to properly handle imported memories
export function compileMemoryAccess(instr, func, body, module) {
	if (MEMORY_ACCESS_INSTR.has(instr.type)) {
		// Use standard memory access instruction
		body.push(MEMORY_ACCESS_INSTR.get(instr.type));

		// Validate alignment
		const align = instr.align || 0;
		if (align < 0) {
			throw createError(
				instr,
				func,
				module,
				`Invalid alignment value: ${align}`,
			);
		}

		// Get natural alignment for this instruction type
		const naturalAlign = getInstructionNaturalAlignment(instr.type);

		// Validate that alignment doesn't exceed natural alignment
		if (align > naturalAlign) {
			throw createError(
				instr,
				func,
				module,
				`Invalid alignment value: ${align}. Cannot exceed natural alignment of ${naturalAlign}`,
			);
		}

		// Memory arguments: alignment and offset
		body.push(...encodeULEB128(align));
		body.push(...encodeULEB128(instr.offset || 0));

		// Encode memory index only for multi-memory support
		// Single-memory modules (MVP) don't include the memory index
		const hasMultipleMemories =
			(module.memories && module.memories.length > 1) ||
			module.imports?.filter((imp) => imp.kind === "memory").length > 1;

		if (
			hasMultipleMemories ||
			(instr.memoryRef !== null && instr.memoryRef !== undefined)
		) {
			let memoryIndex = 0; // Default to memory 0

			if (instr.memoryRef !== null && instr.memoryRef !== undefined) {
				if (
					typeof instr.memoryRef === "string" &&
					instr.memoryRef.startsWith("$")
				) {
					// For named memory reference, find the memory index
					const memoryName = instr.memoryRef.substring(1);

					// Check imported memories first
					const importedMemIndex = module.imports
						?.filter((imp) => imp.kind === "memory")
						.findIndex(
							(imp) => imp.field === memoryName || imp.name === instr.memoryRef,
						);

					if (importedMemIndex !== -1) {
						memoryIndex = importedMemIndex;
					} else if (module.memories) {
						// Check module-defined memories
						const localMemIndex = module.memories.findIndex(
							(mem) => mem.id === instr.memoryRef || mem.name === memoryName,
						);
						if (localMemIndex !== -1) {
							// Add offset for imported memories
							const importedMemCount =
								module.imports?.filter((imp) => imp.kind === "memory").length ||
								0;
							memoryIndex = importedMemCount + localMemIndex;
						} else {
							throw createError(
								instr,
								func,
								module,
								`Unknown memory reference: ${instr.memoryRef}`,
							);
						}
					}
				} else if (typeof instr.memoryRef === "number") {
					memoryIndex = instr.memoryRef;
				}
			}

			// Encode memory index as LEB128 for multi-memory support
			body.push(...encodeULEB128(memoryIndex));
		}

		return true;
	}

	return false;
} // Generated by 🤖
