// Generated by 🤖
import wasmConstants from "../constants.mjs";
import { encodeULEB128, getInstructionNaturalAlignment } from "../compile-utils.mjs";
import { createError } from "./error.mjs";
import { addMapping } from "../../sourcemap.mjs";

const {
    INSTR
} = wasmConstants;

// Map of memory instruction types to their opcodes
const MEMORY_ACCESS_INSTR = new Map([
    ['i32.load', INSTR.I32_LOAD], ['i32.load8_s', INSTR.I32_LOAD8_S], ['i32.load8_u', INSTR.I32_LOAD8_U],
    ['i32.load16_s', INSTR.I32_LOAD16_S], ['i32.load16_u', INSTR.I32_LOAD16_U],
    ['i64.load', INSTR.I64_LOAD], ['i64.load8_s', INSTR.I64_LOAD8_S], ['i64.load8_u', INSTR.I64_LOAD8_U],
    ['i64.load16_s', INSTR.I64_LOAD16_S], ['i64.load16_u', INSTR.I64_LOAD16_U],
    ['i64.load32_s', INSTR.I64_LOAD32_S], ['i64.load32_u', INSTR.I64_LOAD32_U],
    ['f32.load', INSTR.F32_LOAD], ['f64.load', INSTR.F64_LOAD],
    ['i32.store', INSTR.I32_STORE], ['i32.store8', INSTR.I32_STORE8], ['i32.store16', INSTR.I32_STORE16],
    ['i64.store', INSTR.I64_STORE], ['i64.store8', INSTR.I64_STORE8], ['i64.store16', INSTR.I64_STORE16],
    ['i64.store32', INSTR.I64_STORE32],
    ['f32.store', INSTR.F32_STORE], ['f64.store', INSTR.F64_STORE]
]);

export function compileMemoryAccess(instr, func, binary, module) { // Changed body to binary
    if (MEMORY_ACCESS_INSTR.has(instr.type)) {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }

        // Multi-memory handling (instr.memoryRef)
        // For MVP, memory index is 0. If multi-memory proposal is enabled,
        // memory instructions can take an optional memory index.
        // If instr.memoryRef is not null or 0, it indicates a non-default memory.
        // Standard opcodes are for memory 0. For other memories, specific opcodes or prefixes might be needed if not handled by context.
        // Current spec (MVP) implies memory index 0 for these opcodes.
        // If instr.memoryRef exists and is not 0, and we are strictly MVP, this could be an error.
        // However, parser might allow it, and we log a warning.
        let memoryIndexToEncode = 0; // Default to memory 0 for MVP.
        
        if (instr.memoryRef != null && instr.memoryRef !== 0) { // Allow string or number for memoryRef
            if (typeof instr.memoryRef === 'string' && instr.memoryRef.startsWith('$')) {
                 const importedMemIndex = module.imports
                    .filter(imp => imp.kind === 'memory')
                    .findIndex(imp => imp.field === instr.memoryRef.substring(1) || imp.name === instr.memoryRef);
                if (importedMemIndex !== -1) memoryIndexToEncode = importedMemIndex;
                else throw createError(instr, func, module, `Unknown memory reference: ${instr.memoryRef}`);
            } else if (typeof instr.memoryRef === 'number') {
                memoryIndexToEncode = instr.memoryRef;
            } else {
                 throw createError(instr, func, module, `Invalid memory reference: ${instr.memoryRef}`);
            }
            
            // For MVP, any memoryIndexToEncode other than 0 is problematic without multi-memory proposal.
            // The opcodes in MEMORY_ACCESS_INSTR are for memory 0.
            // If multi-memory is supported, the encoding might change (e.g., prefix for memory idx).
            // For now, we assume these opcodes are used, and if memoryIndexToEncode != 0, it's a multi-memory feature.
            if (memoryIndexToEncode !== 0) {
                 console.warn(`⚠️ Multi-memory operation detected (${instr.type} on memory ${memoryIndexToEncode}). This requires multi-memory proposal.`);
                 // If multi-memory proposal means these opcodes take an immediate memory index, it would be encoded here.
                 // As of current core spec, these opcodes imply memidx 0.
                 // We will proceed assuming the opcode implies memory 0, and memoryRef is for validation/future use.
            }
        }
        
        binary.push(MEMORY_ACCESS_INSTR.get(instr.type));

        const align = instr.align != null ? instr.align : getInstructionNaturalAlignment(instr.type);
        // AST might store align: null if not specified, so default it.
        // Or, align might be 0 if explicitly set that way.
        
        if (align < 0) {
            throw createError(instr, func, module, `Invalid alignment value: ${align}`);
        }
        const naturalAlign = getInstructionNaturalAlignment(instr.type);
        if (align > naturalAlign) {
            throw createError(instr, func, module, `Invalid alignment value: ${align}. Cannot exceed natural alignment of ${naturalAlign} for ${instr.type}.`);
        }

        binary.push(...encodeULEB128(align));
        binary.push(...encodeULEB128(instr.offset || 0)); // Default offset to 0 if not present

        return true;
    }
    return false;
}