// Generated by 🤖
import wasmConstants from "../constants.mjs";
import { createError } from "./error.mjs";
import { addMapping } from "../../sourcemap.mjs";
import { encodeULEB128 } from "../compile-utils.mjs";


const {
    INSTR
} = wasmConstants;

export function compileTableInstruction(instr, func, module, binary) { // Changed body to binary
    // Helper for simple table instructions that take one table index
    const compileSimpleTableOp = (wasmInstr) => {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(wasmInstr);
        // Ensure tableIndex is valid if provided (can be 0 or $name)
        const tableIdx = instr.tableIndex == null ? 0 : (typeof instr.tableIndex === 'string' ? module.tables.findIndex(t => t.id === instr.tableIndex) : instr.tableIndex);
        if (tableIdx === -1 || (module.tables && tableIdx >= module.tables.length)) {
             throw createError(instr, func, module, `Invalid table index '${instr.tableIndex}' for ${instr.type}.`);
        }
        binary.push(...encodeULEB128(tableIdx)); // Table index is ULEB128
        return true;
    };
    
    // Helper for bulk table instructions that take one table index
    const compileBulkTableOp = (wasmBulkOpcode) => {
         if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.BULK_PREFIX);
        binary.push(wasmBulkOpcode);
        const tableIdx = instr.tableIndex == null ? 0 : (typeof instr.tableIndex === 'string' ? module.tables.findIndex(t => t.id === instr.tableIndex) : instr.tableIndex);
        if (tableIdx === -1 || (module.tables && tableIdx >= module.tables.length)) {
             throw createError(instr, func, module, `Invalid table index '${instr.tableIndex}' for ${instr.type}.`);
        }
        binary.push(...encodeULEB128(tableIdx));
        return true;
    };


    switch (instr.type) {
        case 'table.init':
            // Operands: element_segment_index, table_index
            // Binary: 0xFC, 0x0C, elem_idx (ULEB), table_idx (ULEB)
            if (instr.loc && instr.loc.line != null) {
                addMapping(instr.loc.line, instr.loc.column, binary.length);
            }
            binary.push(INSTR.BULK_PREFIX);
            binary.push(INSTR.TABLE_INIT);
            
            const elemIdx = typeof instr.elementIndex === 'string' ? module.elements.findIndex(e => e.id === instr.elementIndex) : instr.elementIndex;
            if (elemIdx === -1 || (module.elements && elemIdx >= module.elements.length)) {
                throw createError(instr, func, module, `Element segment '${instr.elementIndex}' not found for table.init.`);
            }
            binary.push(...encodeULEB128(elemIdx));

            const tableIdxForInit = instr.tableIndex == null ? 0 : (typeof instr.tableIndex === 'string' ? module.tables.findIndex(t => t.id === instr.tableIndex) : instr.tableIndex);
            if (tableIdxForInit === -1 || (module.tables && tableIdxForInit >= module.tables.length)) {
                 throw createError(instr, func, module, `Invalid table index '${instr.tableIndex}' for table.init.`);
            }
            binary.push(...encodeULEB128(tableIdxForInit));
            return true;

        case 'table.size': // This is not a bulk op in current spec, but often grouped. Let's assume standard.
                           // Standard is: TABLE_SIZE_OPCODE table_idx
            return compileSimpleTableOp(INSTR.TABLE_SIZE_OPCODE); // Assuming TABLE_SIZE_OPCODE exists for 0x25 0x00 in constants

        case 'table.grow': // 0xFC 0x0F table_idx
            return compileBulkTableOp(INSTR.TABLE_GROW);
            
        case 'table.get': // TABLE_GET_OPCODE table_idx
            return compileSimpleTableOp(INSTR.TABLE_GET);

        case 'table.set': // TABLE_SET_OPCODE table_idx
            return compileSimpleTableOp(INSTR.TABLE_SET);

        case 'table.copy':
            // Operands: dest_table_index, src_table_index
            // Binary: 0xFC, 0x0E, dest_idx (ULEB), src_idx (ULEB)
             if (instr.loc && instr.loc.line != null) {
                addMapping(instr.loc.line, instr.loc.column, binary.length);
            }
            binary.push(INSTR.BULK_PREFIX);
            binary.push(INSTR.TABLE_COPY);

            const destIdx = instr.destTableIndex == null ? 0 : (typeof instr.destTableIndex === 'string' ? module.tables.findIndex(t => t.id === instr.destTableIndex) : instr.destTableIndex);
            if (destIdx === -1 || (module.tables && destIdx >= module.tables.length)) {
                 throw createError(instr, func, module, `Invalid destination table index '${instr.destTableIndex}' for table.copy.`);
            }
            binary.push(...encodeULEB128(destIdx));

            const srcIdx = instr.srcTableIndex == null ? 0 : (typeof instr.srcTableIndex === 'string' ? module.tables.findIndex(t => t.id === instr.srcTableIndex) : instr.srcTableIndex);
            if (srcIdx === -1 || (module.tables && srcIdx >= module.tables.length)) {
                 throw createError(instr, func, module, `Invalid source table index '${instr.srcTableIndex}' for table.copy.`);
            }
            binary.push(...encodeULEB128(srcIdx));
            return true;

        case 'elem.drop':
            // Operand: element_segment_index
            // Binary: 0xFC, 0x0D, elem_idx (ULEB)
            if (instr.loc && instr.loc.line != null) {
                addMapping(instr.loc.line, instr.loc.column, binary.length);
            }
            binary.push(INSTR.BULK_PREFIX);
            binary.push(INSTR.ELEM_DROP);
            
            const elemDropIdx = typeof instr.elementIdx === 'string' ? module.elements.findIndex(e => e.id === instr.elementIdx) : instr.elementIdx;
            if (elemDropIdx === -1 || (module.elements && elemDropIdx >= module.elements.length)) {
                throw createError(instr, func, module, `Element segment '${instr.elementIdx}' not found for elem.drop.`);
            }
            binary.push(...encodeULEB128(elemDropIdx));
            return true;

        case 'table.fill': // 0xFC 0x11 table_idx
            return compileBulkTableOp(INSTR.TABLE_FILL);
    }

    return false;
}