// Generated by 🤖
import wasmConstants from "../constants.mjs";
import { createError } from "./error.mjs";
import { encodeULEB128 } from "../compile-utils.mjs";
import { addMapping } from "../../sourcemap.mjs";

const {
    INSTR
} = wasmConstants;

function variableByIndexName(instr, func) { // instr here is the AST node for the instruction
    let varIndex = -1;
    const operandValue = instr.operand; // instr.operand is the string value like "$var" or "0"

    if (typeof operandValue !== 'string') { // Should be a string from parser
        throw new Error(`Invalid variable operand: ${operandValue}`);
    }

    if (operandValue.startsWith('$')) {
        varIndex = func.parameters.findIndex(p => p.name === operandValue);
        if (varIndex === -1 && func.locals) {
            const localIndex = func.locals.findIndex(l => l.name === operandValue);
            if (localIndex !== -1) {
                // Correctly calculate index relative to combined params+locals space
                varIndex = (func.parameters ? func.parameters.length : 0) + func.locals.indexOf(l);
            }
        }
    } else {
        varIndex = Number.parseInt(operandValue, 10);
        if (Number.isNaN(varIndex)) {
             throw new Error(`Invalid numeric variable index: ${operandValue}`);
        }
    }

    if (varIndex === -1) {
        throw new Error(`Unknown variable: ${operandValue}`);
    }

    // If we have a local variable map (from code.mjs reordering), use it.
    // The map's keys should be original indices (param count + original local index).
    if (func.localMap?.has(varIndex)) {
        return func.localMap.get(varIndex);
    }
    // Otherwise, it's a parameter or a global, or local not reordered (shouldn't happen if localMap is used consistently).
    return varIndex;
}

export function compileVariableAccess(instr, func, binary, moduleGlobals, module) {
    const opType = instr.type; // e.g., 'local.get'

    if (opType === 'get_local' || opType === 'local.get') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.LOCAL_GET);
        try {
            const varIndex = variableByIndexName(instr, func);
            binary.push(...encodeULEB128(varIndex));
            return true;
        } catch (err) {
            throw createError(instr, func, module, `Cannot find local variable: ${instr.operand}. Error: ${err.message}`);
        }
    } else if (opType === 'set_local' || opType === 'local.set') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.LOCAL_SET);
        try {
            const varIndex = variableByIndexName(instr, func);
            binary.push(...encodeULEB128(varIndex));
            return true;
        } catch (err) {
            throw createError(instr, func, module, `Cannot find local variable: ${instr.operand}. Error: ${err.message}`);
        }
    } else if (opType === 'local.tee') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.LOCAL_TEE);
        try {
            const varIndex = variableByIndexName(instr, func);
            binary.push(...encodeULEB128(varIndex));
            return true;
        } catch (err) {
            throw createError(instr, func, module, `Cannot find local variable: ${instr.operand}. Error: ${err.message}`);
        }
    } else if (opType === 'global.get') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.GLOBAL_GET);
        let globalIndex = -1;
        if (instr.operand.startsWith('$')) {
            globalIndex = moduleGlobals.findIndex(g => g.name === instr.operand);
        } else {
            globalIndex = Number.parseInt(instr.operand, 10);
             if (Number.isNaN(globalIndex))  throw createError(instr, func, module, `Invalid numeric global index: ${instr.operand}`);
        }
        if (globalIndex === -1 || globalIndex >= moduleGlobals.length) {
            throw createError(instr, func, module, `Unknown global variable: ${instr.operand}.`);
        }
        binary.push(...encodeULEB128(globalIndex));
        return true;
    } else if (opType === 'global.set') {
        if (instr.loc && instr.loc.line != null) {
            addMapping(instr.loc.line, instr.loc.column, binary.length);
        }
        binary.push(INSTR.GLOBAL_SET);
        let globalIndex = -1;
        if (instr.operand.startsWith('$')) {
            globalIndex = moduleGlobals.findIndex(g => g.name === instr.operand);
        } else {
            globalIndex = Number.parseInt(instr.operand, 10);
            if (Number.isNaN(globalIndex)) throw createError(instr, func, module, `Invalid numeric global index: ${instr.operand}`);
        }

        if (globalIndex === -1 || globalIndex >= moduleGlobals.length) {
            throw createError(instr, func, module, `Unknown global variable: ${instr.operand}.`);
        }
        if (!moduleGlobals[globalIndex].mutable) {
            throw createError(instr, func, module, `Cannot set immutable global: ${instr.operand}. Add (mut) qualifier.`);
        }
        binary.push(...encodeULEB128(globalIndex));
        return true;
    }

    return false;
}