// Generated by 🤖

let mappings = [];
let currentSectionBaseOffset = 0;

/**
 * Resets the internal list of mappings and the section base offset.
 * Call this before starting a new compilation.
 */
export function resetMappings() {
  mappings = [];
  currentSectionBaseOffset = 0;
}

/**
 * Sets a base offset for the current section being compiled.
 * Mappings added via addMapping will have this baseOffset added to their wasmOffset.
 * @param {number} baseOffset - The starting offset of the current section in the final binary.
 */
export function setSectionBaseOffset(baseOffset) {
  if (typeof baseOffset !== 'number') {
    console.warn('Invalid baseOffset provided to setSectionBaseOffset:', baseOffset);
    currentSectionBaseOffset = 0; // Default to 0 if invalid
    return;
  }
  currentSectionBaseOffset = baseOffset;
}

/**
 * Adds a new mapping from WAT source location to WASM bytecode offset.
 * The provided wasmOffset is relative to the current section's base offset.
 * @param {number} watLine - The line number in the WAT source file (1-indexed).
 * @param {number} watColumn - The column number in the WAT source file (1-indexed).
 * @param {number} relativeWasmOffset - The offset relative to the current section's start.
 */
export function addMapping(watLine, watColumn, relativeWasmOffset) {
  if (typeof watLine !== 'number' || typeof watColumn !== 'number' || typeof relativeWasmOffset !== 'number') {
    console.warn('Invalid mapping data provided:', { watLine, watColumn, relativeWasmOffset });
    return;
  }
  mappings.push({
    watLine,
    watColumn,
    wasmOffset: currentSectionBaseOffset + relativeWasmOffset // wasmOffset is now relative
  });
}

/**
 * Serializes all collected mappings into a JSON string.
 * @returns {string} A JSON string representing the source map.
 */
export function serializeMappings() {
  return JSON.stringify(mappings, null, 2); // Using 2 for pretty printing
}

/**
 * Returns the raw array of mappings.
 * Useful for testing or direct inspection.
 * @returns {Array<object>}
 */
export function getMappings() {
  return mappings;
}
