;; Generated by 🤖
(module
  ;; Define table with min size 4
  (table 4 4 funcref)
  
  ;; Define functions that will be referenced
  (func $f1 (result i32)
    i32.const 42)
    
  (func $f2 (result i32)
    i32.const 43)
    
  (func $f3 (result i32)
    i32.const 44)
    
  ;; Define an active element segment at offset 0
  (elem (i32.const 0) $f1 $f2 $f3)
  
  ;; Function to copy table entries
  (func $copy_table (param $dst i32) (param $src i32) (param $size i32)
    local.get $dst  ;; Destination index
    local.get $src  ;; Source index
    local.get $size ;; Number of elements to copy
    table.copy 0 0) ;; Both source and destination tables are table 0
  
  ;; Function to get element from table
  (func $get_func (param i32) (result funcref)
    local.get 0
    table.get 0)
  
  ;; Function to get table size
  (func $table_size (result i32)
    table.size 0)
    
  ;; Exports for testing
  (export "copy_table" (func $copy_table))
  (export "get_func" (func $get_func))
  (export "table_size" (func $table_size))
  (export "f1" (func $f1))
  (export "f2" (func $f2))
  (export "f3" (func $f3))
  (export "tbl" (table 0)))