// Generated by 🤖
import wasmConstants from "../constants.mjs";
import {
    encodeULEB128,
    encodeSLEB128, // For i32.const offset value
    // encodeString, // Not typically used for data segment bytes, direct bytes are used.
} from "../compile-utils.mjs";
import { addMapping, setSectionBaseOffset } from "../../sourcemap.mjs";
import { createError } from "../instructions/error.mjs";


const {
    INSTR,
    SECTION
} = wasmConstants;

// Helper function (if needed, or inline)
function encodeBytes(str) { // This seems like a legacy helper if bytes are already processed
    const encoder = new TextEncoder();
    return Array.from(encoder.encode(str));
}

export function dataCountSection(module, binary) {
    if (!module.datas || module.datas.length === 0) return;

    // No specific AST node for data count itself to map its loc.
    // If module.loc existed, it could be mapped here.
    // For now, dataCountSection does not add mappings.
    
    const dataCountSectionContentBytes = [...encodeULEB128(module.datas.length)];

    binary.push(SECTION.DATA_COUNT);
    binary.push(...encodeULEB128(dataCountSectionContentBytes.length)); // Size of content
    binary.push(...dataCountSectionContentBytes);
}

export function dataSection(module, binary) {
    if (!module.datas || module.datas.length === 0) {
        return;
    }

    const sourceMapEntries = [];
    const dataSectionContentBytes = [];

    dataSectionContentBytes.push(...encodeULEB128(module.datas.length)); // Count of data segments

    for (const data of module.datas) {
        // data AST: { type: 'data_segment', id, idLoc, memoryIndex, memoryIndexLoc, offset: offsetExpression, bytes, isPassive, loc }
        // offsetExpression: { opcode: 'i32.const', value, valueLoc, loc }
        
        if (data.loc && data.loc.line != null) {
            sourceMapEntries.push({ loc: data.loc, relativeOffset: dataSectionContentBytes.length });
        }

        let flags;
        if (data.isPassive) {
            flags = 0x01; // Passive segment
            dataSectionContentBytes.push(flags);
        } else {
            // Active segment
            if (data.memoryIndex != null && data.memoryIndex !== 0) {
                flags = 0x02; // Active, with explicit memory index
                dataSectionContentBytes.push(flags);
                dataSectionContentBytes.push(...encodeULEB128(data.memoryIndex));
            } else {
                flags = 0x00; // Active, memory index 0
                dataSectionContentBytes.push(flags);
            }
            
            // Offset expression
            if (!data.offsetExpression || data.offsetExpression.opcode !== 'i32.const') {
                 throw createError(data.offsetExpression || data, null, module, "Active data segment requires an i32.const offset expression.");
            }
            // TODO: Add mapping for data.offsetExpression.loc if desired, relative to this point.
            // addMapping(data.offsetExpression.loc.line, data.offsetExpression.loc.column, baseOffset + dataSectionContentBytes.length)
            dataSectionContentBytes.push(INSTR.I32_CONST);
            dataSectionContentBytes.push(...encodeSLEB128(Number(data.offsetExpression.value)));
            dataSectionContentBytes.push(INSTR.END);
        }

        // Bytes content
        // data.bytes should be { rawStrings: [{value, loc},...], processedBytes: number[] }
        const bytesArray = data.bytes && Array.isArray(data.bytes.processed) 
            ? data.bytes.processed 
            : (typeof data.bytes === 'string' ? encodeBytes(data.bytes) : []); // Fallback for old string format

        dataSectionContentBytes.push(...encodeULEB128(bytesArray.length));
        dataSectionContentBytes.push(...bytesArray);
    }

    if (dataSectionContentBytes.length === encodeULEB128(module.datas.length).length && module.datas.length === 0) {
        return; 
    }

    const sectionStartOffsetInBinary = binary.length;
    binary.push(SECTION.DATA);
    const sectionSizeBytesArray = encodeULEB128(dataSectionContentBytes.length);
    binary.push(...sectionSizeBytesArray);
    
    setSectionBaseOffset(sectionStartOffsetInBinary + 1 + sectionSizeBytesArray.length);
    
    for (const entry of sourceMapEntries) {
        addMapping(entry.loc.line, entry.loc.column, entry.relativeOffset);
    }
    
    binary.push(...dataSectionContentBytes);
    setSectionBaseOffset(0);
}