// Generated by 🤖
import wasmConstants from "../constants.mjs";
import { 
    encodeULEB128,
    encodeSLEB128, // For i32.const offset
    getWasmType    // For element type like funcref
 } from "../compile-utils.mjs";
import { addMapping, setSectionBaseOffset } from "../../sourcemap.mjs";
import { createError } from "../instructions/error.mjs";


const {
    INSTR,
    SECTION,
    TYPE // For TYPE.FUNCREF etc.
} = wasmConstants;

export function elementSection(elements, functions, binary) {
    if (!elements || elements.length === 0) {
        return;
    }

    const sourceMapEntries = [];
    const elementSectionContentBytes = [];

    elementSectionContentBytes.push(...encodeULEB128(elements.length)); // Count of element segments

    for (const element of elements) {
        // element AST node: { type: 'element_segment', id, idLoc, tableIndex, tableIndexLoc, mode, modeLoc, elemType, typeLoc, offset: offsetExpression, items, loc }
        // offsetExpression: { opcode: 'i32.const', value, loc, opcodeLoc, valueLoc }
        
        if (element.loc && element.loc.line != null) {
            sourceMapEntries.push({ loc: element.loc, relativeOffset: elementSectionContentBytes.length });
        }

        let flags = 0;
        let tableIdx = 0; // Default for MVP if not specified or active mode 0x00
        let elemKindByte = TYPE.FUNCREF; // Default elem kind

        if (element.tableIndex != null) { // Can be 0 or a name $t
            if (typeof element.tableIndex === 'string' && element.tableIndex.startsWith('$')) {
                // Resolve table name to index - assuming module.tables exists and is populated
                // This resolution should ideally happen in a prior "linking" phase.
                // For now, error if named table index is used without a simple way to resolve.
                // Or assume table 0 if not specified.
                // MVP only has table 0.
                throw createError(element, null, { elements }, `Named table index '${element.tableIndex}' in element segment requires table resolution.`);
            } else {
                tableIdx = Number(element.tableIndex);
            }
        }
        
        if (element.elemType) {
            try {
                elemKindByte = getWasmType(element.elemType);
            } catch(e) {
                 throw createError(element, null, { elements }, `Invalid element type '${element.elemType}'.`);
            }
        }

        if (element.mode === 'passive') {
            flags = 0x01; // Passive
            if (element.elemType) flags |= 0x00; // elemkind is present (funcref or externref)
            else flags |= 0x00; // elemkind is implicitly funcref
            elementSectionContentBytes.push(flags);
            elementSectionContentBytes.push(elemKindByte);
        } else if (element.mode === 'active') {
            if (tableIdx !== 0) { // If not table 0, mode 0x02
                flags = 0x02;
                elementSectionContentBytes.push(flags);
                elementSectionContentBytes.push(...encodeULEB128(tableIdx));
            } else { // table 0
                flags = 0x00;
                elementSectionContentBytes.push(flags);
            }
            // Offset expression
            if (!element.offset || element.offset.opcode !== 'i32.const') {
                throw createError(element.offset || element, null, { elements }, "Active element segment requires an i32.const offset expression.");
            }
            // TODO: Add mapping for element.offset.loc if available
            elementSectionContentBytes.push(INSTR.I32_CONST);
            elementSectionContentBytes.push(...encodeSLEB128(Number(element.offset.value)));
            elementSectionContentBytes.push(INSTR.END);
            
            if (flags === 0x00 || flags === 0x02) { // These modes have elemkind after offset
                 elementSectionContentBytes.push(elemKindByte);
            }

        } else if (element.mode === 'declarative') {
            flags = 0x03; // Declarative
            if (element.elemType) flags |= 0x00; 
            else flags |= 0x00; 
            elementSectionContentBytes.push(flags);
            elementSectionContentBytes.push(elemKindByte);
        } else {
            throw createError(element, null, { elements }, `Unknown element mode: ${element.mode}`);
        }
        
        // Function indices / expressions
        const items = element.items || element.functionIndices || []; // AST might use 'items' or 'functionIndices'
        elementSectionContentBytes.push(...encodeULEB128(items.length));

        for (const item of items) {
            // item should be { value: string (idx or $name), loc: Location }
            let funcIndex;
            const itemValue = item.value !== undefined ? item.value : item; // Handle if items are simple strings/numbers

            // TODO: Add mapping for item.loc if available, relative to this point in elementSectionContentBytes
            // addMapping(item.loc.line, item.loc.column, elementSectionContentBytes.length + baseOffsetForThisSection)

            if (typeof itemValue === 'string' && itemValue.startsWith('$')) {
                funcIndex = functions.findIndex(f => f.name === itemValue);
                if (funcIndex === -1) {
                    throw createError(item, null, { functions }, `Unknown function reference in element segment: ${itemValue}`);
                }
            } else {
                funcIndex = Number.parseInt(String(itemValue), 10);
                 if (Number.isNaN(funcIndex) || funcIndex < 0 || funcIndex >= functions.length) { // Check against total functions length
                    throw createError(item, null, { functions }, `Invalid function index in element segment: ${itemValue}`);
                 }
            }
            elementSectionContentBytes.push(...encodeULEB128(funcIndex));
        }
    }

    if (elementSectionContentBytes.length === encodeULEB128(elements.length).length && elements.length === 0) {
        return; 
    }

    const sectionStartOffsetInBinary = binary.length;
    binary.push(SECTION.ELEMENT);
    const sectionSizeBytesArray = encodeULEB128(elementSectionContentBytes.length);
    binary.push(...sectionSizeBytesArray);
    
    setSectionBaseOffset(sectionStartOffsetInBinary + 1 + sectionSizeBytesArray.length);
    
    for (const entry of sourceMapEntries) {
        addMapping(entry.loc.line, entry.loc.column, entry.relativeOffset);
    }
    
    binary.push(...elementSectionContentBytes);
    setSectionBaseOffset(0);
}