import { encodeString, encodeULEB128 } from "../compile-utils.mjs";
import { EXPORT, SECTION } from "../constants.mjs";

const parseIndex = (value) => {
	if (typeof value === "number") return value;
	const parsed = Number.parseInt(value, 10);
	return Number.isNaN(parsed) ? 0 : parsed;
};

export function exportSection(module, binary) {
	if (module.exports && Object.keys(module.exports).length > 0) {
		const exportSection = [SECTION.EXPORT]; // Section ID

		// Export count
		const exportEntries = [
			...encodeULEB128(Object.keys(module.exports).length),
		];

		// Add each export entry
		for (const [exportName, exportData] of Object.entries(module.exports)) {
			// Export name
			const nameBytes = encodeString(exportName);
			exportEntries.push(...nameBytes);

			if (exportData.kind === "func") {
				// Kind (function)
				exportEntries.push(EXPORT.FUNC);

				// Function index
				const funcIndex = parseIndex(exportData.index);

				exportEntries.push(...encodeULEB128(funcIndex));
			} else if (exportData.kind === "memory") {
				// Kind (memory)
				exportEntries.push(EXPORT.MEM);

				// Memory index
				const memIndex = parseIndex(exportData.index);

				exportEntries.push(...encodeULEB128(memIndex));
			} else if (exportData.kind === "global") {
				// Kind (global)
				exportEntries.push(EXPORT.GLOBAL);

				// Global index
				const globalIndex = parseIndex(exportData.index);

				exportEntries.push(...encodeULEB128(globalIndex));
			} else if (exportData.kind === "table") {
				// Generated by 🤖
				// Kind (table)
				exportEntries.push(EXPORT.TABLE);

				// Table index
				const tableIndex = parseIndex(exportData.index);

				exportEntries.push(...encodeULEB128(tableIndex));
			}
		}

		// Section size
		exportSection.push(...encodeULEB128(exportEntries.length));

		// Section content
		exportSection.push(...exportEntries);

		binary.push(...exportSection);
	}
}
