// Generated by 🤖
import wasmConstants from "../constants.mjs";
import { encodeULEB128 } from "../compile-utils.mjs";
import { addMapping, setSectionBaseOffset } from "../../sourcemap.mjs";

const {
    SECTION,
} = wasmConstants;

export function functionSection(functions, binary) {
    if (!functions || functions.length === 0) {
        return;
    }
    
    const nonImportedFunctions = functions.filter(func => !func.import);
    if (nonImportedFunctions.length === 0) {
        return;
    }
    
    const sourceMapEntries = [];
    const functionSectionContentBytes = [];

    // Vector of type indices for each function
    functionSectionContentBytes.push(...encodeULEB128(nonImportedFunctions.length)); // Count of functions

    for (let i = 0; i < nonImportedFunctions.length; i++) {
        const func = nonImportedFunctions[i];
        // func.typeIndex should be populated by the type section generation,
        // mapping this function to its signature index in the type section.
        if (func.typeIndex == null) {
            // Fallback or error: if typeIndex is not set, this indicates an issue in earlier compilation stages.
            // For robustness, could default to 'i' but this implies types are ordered same as functions.
            console.warn(`Function '${func.name || i}' missing typeIndex, defaulting to ${i}. This might be incorrect.`);
            func.typeIndex = i; // This is a guess and might be wrong.
        }

        if (func.loc && func.loc.line != null) {
            // The mapping is for the function's declaration, pointing to where its type_index is written.
            sourceMapEntries.push({ loc: func.loc, relativeOffset: functionSectionContentBytes.length });
        }
        functionSectionContentBytes.push(...encodeULEB128(func.typeIndex)); // Type index for this function
    }

    if (functionSectionContentBytes.length === encodeULEB128(nonImportedFunctions.length).length && nonImportedFunctions.length === 0) {
        // Only contains the count of functions (which is 0)
        return;
    }

    const sectionStartOffsetInBinary = binary.length;
    binary.push(SECTION.FUNCTION);
    const sectionSizeBytesArray = encodeULEB128(functionSectionContentBytes.length);
    binary.push(...sectionSizeBytesArray);
    
    setSectionBaseOffset(sectionStartOffsetInBinary + 1 + sectionSizeBytesArray.length);
    
    for (const entry of sourceMapEntries) {
        addMapping(entry.loc.line, entry.loc.column, entry.relativeOffset);
    }
    
    binary.push(...functionSectionContentBytes);
    setSectionBaseOffset(0);
}