import { encodeULEB128 } from "../compile-utils.mjs";
import { SECTION } from "../constants.mjs";

export function functionSection(functions, binary) {
	if (functions.length > 0) {
		// Generated by 🤖
		// Filter out imported functions
		const nonImportedFunctions = functions.filter((func) => !func.import);

		if (nonImportedFunctions.length === 0) {
			return;
		}

		// Maps functions to their type signatures
		const functionSection = [SECTION.FUNCTION]; // Section ID

		// Function signatures
		const funcSignatures = [...encodeULEB128(nonImportedFunctions.length)];
		for (let i = 0; i < nonImportedFunctions.length; i++) {
			const func = nonImportedFunctions[i];
			const typeIndex = func.typeIndex ?? 0;
			funcSignatures.push(...encodeULEB128(typeIndex)); // Type index
		}

		// Section size
		functionSection.push(...encodeULEB128(funcSignatures.length));

		// Section content
		functionSection.push(...funcSignatures);

		binary.push(...functionSection);
	}
}
