// Generated by 🤖
import wasmConstants from "../constants.mjs";
import { addMapping, setSectionBaseOffset } from "../../sourcemap.mjs";
import {
    encodeULEB128,
    encodeSLEB128BigInt, // For i64.const
    encodeF32,          // Helper for f32.const if not direct byte writing
    encodeF64,
    getWasmType,
} from "../compile-utils.mjs";
import { createError } from "../instructions/error.mjs";


const {
    INSTR,
    SECTION
} = wasmConstants;

export function globalSection(globals, binary) {
    const nonImportedGlobals = globals ? globals.filter(g => !(g.importInfo || g.import)) : [];
    
    if (nonImportedGlobals.length === 0) {
        return;
    }

    const sourceMapEntries = [];
    const globalSectionContentBytes = [];

    globalSectionContentBytes.push(...encodeULEB128(nonImportedGlobals.length)); // Count of globals

    for (const glob of nonImportedGlobals) {
        // glob AST should have: name, nameLoc, type, typeLoc, mutable, mutKeywordLoc, init (expr AST), loc
        if (glob.loc && glob.loc.line != null) {
            sourceMapEntries.push({ loc: glob.loc, relativeOffset: globalSectionContentBytes.length });
        }

        globalSectionContentBytes.push(getWasmType(glob.type));
        globalSectionContentBytes.push(glob.mutable ? 1 : 0);

        // Initialization expression
        const initExpr = glob.init;
        if (initExpr) {
            // The AST for initExpr should be simple { type: 'i32.const', value: N, loc, valueLoc, expressionLoc }
            // This mapping would be for the const instruction of the init expression.
            // The main glob.loc already maps to the start of this global's definition.
            if (initExpr.loc && initExpr.loc.line != null) {
                 // Offset is relative to start of globalSectionContentBytes
                 addMapping(initExpr.loc.line, initExpr.loc.column, globalSectionContentBytes.length);
            }

            if (initExpr.type === 'i32.const') {
                globalSectionContentBytes.push(INSTR.I32_CONST);
                globalSectionContentBytes.push(...encodeSLEB128(Number(initExpr.value))); // Value from AST might be string
            } else if (initExpr.type === 'i64.const') {
                globalSectionContentBytes.push(INSTR.I64_CONST);
                globalSectionContentBytes.push(...encodeSLEB128BigInt(String(initExpr.value)));
            } else if (initExpr.type === 'f32.const') {
                globalSectionContentBytes.push(INSTR.F32_CONST);
                globalSectionContentBytes.push(...encodeF32(Number(initExpr.value)));
            } else if (initExpr.type === 'f64.const') {
                globalSectionContentBytes.push(INSTR.F64_CONST);
                globalSectionContentBytes.push(...encodeF64(Number(initExpr.value)));
            } else if (initExpr.type === 'global.get') { // Initializer can be another global
                globalSectionContentBytes.push(INSTR.GLOBAL_GET);
                let refGlobalIndex = -1;
                if (typeof initExpr.operand === 'string' && initExpr.operand.startsWith('$')) {
                    refGlobalIndex = globals.findIndex(g => g.name === initExpr.operand);
                } else {
                    refGlobalIndex = Number.parseInt(initExpr.operand, 10);
                }
                if (refGlobalIndex === -1 || refGlobalIndex >= globals.length) {
                     throw createError(initExpr, null, {globals}, `Initializer global.get refers to unknown global '${initExpr.operand}'.`);
                }
                if (refGlobalIndex >= nonImportedGlobals.indexOf(glob)) { // Must refer to an already defined (imported or earlier non-imported) global
                    throw createError(initExpr, null, {globals}, `Initializer global.get must refer to an already defined global. '${initExpr.operand}' is defined later or is self-referential.`);
                }
                globalSectionContentBytes.push(...encodeULEB128(refGlobalIndex));
            } else {
                throw createError(initExpr, null, {globals}, `Unsupported initializer expression type: ${initExpr.type}. Only const or global.get allowed.`);
            }
            globalSectionContentBytes.push(INSTR.END);
        } else {
            // This case should ideally not happen if parser enforces initializers for non-imported globals,
            // or if a default (like 0) is always filled in by the parser.
            // WebAssembly requires an init_expr for globals.
            throw createError(glob, null, {globals}, `Global variable '${glob.name || "?"}' must have an initializer expression.`);
        }
    }
    
    if (globalSectionContentBytes.length === encodeULEB128(nonImportedGlobals.length).length && nonImportedGlobals.length === 0){
        return; // Only count was written, but count is 0.
    }

    const sectionStartOffsetInBinary = binary.length;
    binary.push(SECTION.GLOBAL);
    const sectionSizeBytesArray = encodeULEB128(globalSectionContentBytes.length);
    binary.push(...sectionSizeBytesArray);
    
    setSectionBaseOffset(sectionStartOffsetInBinary + 1 + sectionSizeBytesArray.length);
    
    for (const entry of sourceMapEntries) {
        addMapping(entry.loc.line, entry.loc.column, entry.relativeOffset);
    }
    
    binary.push(...globalSectionContentBytes);
    setSectionBaseOffset(0);
}