// Generated by 🤖
import wasmConstants from "../constants.mjs";
import { encodeULEB128, getWasmType } from "../compile-utils.mjs";
import { addMapping, setSectionBaseOffset } from "../../sourcemap.mjs";

const {
    SECTION,
    IMPORT_KIND
} = wasmConstants;

export function importSection(module, binary) {
    const collectedImports = []; // To store { originalLoc, kind, module, field, ... }

    // Consolidate imports from various parts of the AST module
    // module.imports contains AST nodes from `(import ...)` statements
    if (module.imports && module.imports.length > 0) {
        for (const astImportNode of module.imports) {
            // astImportNode should have .loc, .module, .field, .kind, and kind-specific details
            // e.g., for func: .name (imported as name), .params, .results
            // e.g., for global: .globalType, .mutable
            // e.g., for memory: .min, .max, .shared
            // e.g., for table: .min, .max, .tableType (funcref/externref)
            if (astImportNode.type === 'import_decl') { // Check if it's the expected AST node type
                 collectedImports.push({ ...astImportNode, originalLoc: astImportNode.loc });
            }
        }
    }
    
    // The AST structure might also have import information directly on functions, globals, etc.
    // This part seems to be for a design where imports are also part of the function/global definition itself.
    // The `module.imports` array (from `(import ...)` statements) should be the primary source.
    // If `func.import` exists, it means `func` is an imported function. Its `loc` is for the `(func $name (import ...))` part.
    // The `typeIndex` for imported functions is their index in the overall function list.
    if (module.functions) {
        for (let i = 0; i < module.functions.length; i++) {
            const func = module.functions[i];
            if (func.import && func.isImported !== true) { // isImported might be used to avoid double counting if already from module.imports
                // This function was declared as an import inside its own definition,
                // e.g. (func $imp (import "mod" "f") (param i32) (result i32))
                // Its `loc` is for the `(func ...)` s-expression.
                // We need to ensure it's not a duplicate of what's in module.imports.
                // A robust solution would be to primarily rely on `module.imports` from `(import ...)` s-expressions.
                // For now, let's assume this path is for a different AST structure or needs careful deduplication.
                // To simplify, we prioritize `module.imports` if it's comprehensive.
                // If `module.imports` is empty, this could be an alternative source.
                // For this exercise, we assume `module.imports` (parsed from `(import)` statements) is the canonical list.
            }
        }
    }
    // Similar logic for globals, tables, memories if they can define imports inline in your AST.

    if (collectedImports.length === 0) {
        return;
    }

    const importSectionContentBytes = []; // Byte content of the section
    const sourceMapEntries = []; // To store { loc, relativeOffset }

    importSectionContentBytes.push(...encodeULEB128(collectedImports.length)); // Vector count of imports

    for (const imp of collectedImports) {
        if (imp.originalLoc && imp.originalLoc.line != null) {
            sourceMapEntries.push({ loc: imp.originalLoc, relativeOffset: importSectionContentBytes.length });
        }

        const moduleNameBytes = new TextEncoder().encode(imp.module);
        importSectionContentBytes.push(...encodeULEB128(moduleNameBytes.length));
        importSectionContentBytes.push(...moduleNameBytes);

        const fieldNameBytes = new TextEncoder().encode(imp.field);
        importSectionContentBytes.push(...encodeULEB128(fieldNameBytes.length));
        importSectionContentBytes.push(...fieldNameBytes);

        switch (imp.kind) {
            case 'func': // Standard kind from parser for (import "" "" (func ...))
            case 'function': // Allow flexibility
                importSectionContentBytes.push(IMPORT_KIND.FUNCTION);
                // The typeIndex for an imported function refers to its signature's index in the type section.
                // This index must be correctly assigned when types are collected or when functions are indexed.
                // `module.functions` contains all functions, imported or defined.
                // The type index is func's actual index in the `module.functions` if types are 1:1 with funcs,
                // or a separate `typeIndex` field on the func AST node.
                // Let's assume func AST node has `typeIndex` referring to its signature in the type section.
                const funcAstNode = module.functions.find(f => f.import && f.import.module === imp.module && f.import.field === imp.field && f.name === imp.name);
                if (!funcAstNode || funcAstNode.typeIndex == null) {
                    throw new Error(`Type index not found for imported function ${imp.module}.${imp.field}`);
                }
                importSectionContentBytes.push(...encodeULEB128(funcAstNode.typeIndex));
                break;
            case 'global':
                importSectionContentBytes.push(IMPORT_KIND.GLOBAL);
                importSectionContentBytes.push(getWasmType(imp.globalType || imp.type)); // AST might use .type or .globalType
                importSectionContentBytes.push(imp.mutable ? 1 : 0);
                break;
            case 'memory':
                importSectionContentBytes.push(IMPORT_KIND.MEMORY);
                let flags = 0;
                if (imp.max != null) flags |= 0x01; // max is present
                if (imp.shared) flags |= 0x02;      // shared memory
                importSectionContentBytes.push(flags);
                importSectionContentBytes.push(...encodeULEB128(imp.min || 0)); // Default min 0 if not specified
                if (imp.max != null) {
                    importSectionContentBytes.push(...encodeULEB128(imp.max));
                }
                break;
            case 'table':
                importSectionContentBytes.push(IMPORT_KIND.TABLE);
                importSectionContentBytes.push(getWasmType(imp.tableType || imp.type)); // e.g. funcref, externref
                let tableFlags = 0;
                if (imp.max != null) tableFlags |= 0x01;
                // Shared tables are not in MVP, add shared flag if relevant for future proposals
                importSectionContentBytes.push(tableFlags);
                importSectionContentBytes.push(...encodeULEB128(imp.min || 0));
                if (imp.max != null) {
                    importSectionContentBytes.push(...encodeULEB128(imp.max));
                }
                break;
            default:
                throw new Error(`Unsupported import kind: ${imp.kind}`);
        }
    }

    const importSectionStartOffsetInBinary = binary.length;
    binary.push(SECTION.IMPORT);
    const sectionSizeBytesArray = encodeULEB128(importSectionContentBytes.length);
    binary.push(...sectionSizeBytesArray);
    
    setSectionBaseOffset(importSectionStartOffsetInBinary + 1 + sectionSizeBytesArray.length);
    
    for (const entry of sourceMapEntries) {
        addMapping(entry.loc.line, entry.loc.column, entry.relativeOffset);
    }
    
    binary.push(...importSectionContentBytes);
    setSectionBaseOffset(0);
}
