// Generated by 🤖
import wasmConstants from "../constants.mjs";
import { encodeULEB128 } from "../compile-utils.mjs";
import { addMapping, setSectionBaseOffset } from "../../sourcemap.mjs";
import { createError } from "../instructions/error.mjs";


const {
    SECTION,
} = wasmConstants;

export function memorySection(module, binary) {
    if (!module.memories || module.memories.length === 0) {
        return;
    }

    // Memories should be sorted by their AST `index` property if multi-memory is used,
    // though MVP only allows one memory (index 0).
    // The parser for `(memory $id <idx> ...)` would set `memory.index`.
    // For MVP, we typically just have one memory, or parser sets index 0.
    const memoriesToProcess = [...module.memories].sort((a, b) => (a.index || 0) - (b.index || 0));

    const sourceMapEntries = [];
    const memorySectionContentBytes = [];

    memorySectionContentBytes.push(...encodeULEB128(memoriesToProcess.length)); // Count of memories

    for (const memory of memoriesToProcess) {
        // memory AST node should have: id, idLoc, min, minLoc, max, maxLoc, shared, sharedLoc, index, indexLoc, loc
        // We map the memory.loc (location of the `(memory ...)` s-expression or `memory` keyword)
        // to the start of its definition in this section.
        if (memory.loc && memory.loc.line != null) {
            sourceMapEntries.push({ loc: memory.loc, relativeOffset: memorySectionContentBytes.length });
        }

        let needsSharedMemory = memory.shared || false;
        // Infer shared if atomic operations are used (as per original logic)
        if (!needsSharedMemory && module.functions) {
            for (const func of module.functions) {
                if (func.instructions?.some(instr => instr?.op?.includes('atomic') || instr?.type?.includes('atomic'))) {
                    needsSharedMemory = true;
                    break;
                }
            }
        }

        let effectiveMax = memory.max;
        if (needsSharedMemory && (effectiveMax == null || effectiveMax === undefined)) {
            // Shared memory must have a max. Defaulting if not specified.
            // This default might not be what the user intended.
            // A warning or error during parsing/validation would be better.
            effectiveMax = 65536; // Default 4GiB (65536 pages of 64KiB)
            console.warn(`Memory ${memory.id || (memory.index || 0)} is shared or atomics are used; 'max' limit not specified, defaulting to ${effectiveMax}.`);
        }
        
        let flags = 0;
        if (effectiveMax != null && effectiveMax !== undefined) flags |= 0x01; // Bit 0: max is present
        if (needsSharedMemory) flags |= 0x02; // Bit 1: shared memory
        // Bit 2 (0x04) would be for 64-bit memory, not MVP.

        memorySectionContentBytes.push(flags);

        const minPages = memory.min != null ? memory.min : 0; // Default min 0 if not specified
        if (minPages < 0) throw createError(null, null, module, `Memory min pages cannot be negative: ${minPages}`);
        memorySectionContentBytes.push(...encodeULEB128(minPages));

        if ((flags & 0x01) !== 0) { // If max is present
            if (effectiveMax < minPages) {
                 throw createError(null, null, module, `Memory max pages (${effectiveMax}) < min pages (${minPages})`);
            }
            memorySectionContentBytes.push(...encodeULEB128(effectiveMax));
        }
    }
    
    if (memorySectionContentBytes.length === encodeULEB128(memoriesToProcess.length).length && memoriesToProcess.length === 0) {
        return; 
    }

    const sectionStartOffsetInBinary = binary.length;
    binary.push(SECTION.MEMORY);
    const sectionSizeBytesArray = encodeULEB128(memorySectionContentBytes.length);
    binary.push(...sectionSizeBytesArray);
    
    setSectionBaseOffset(sectionStartOffsetInBinary + 1 + sectionSizeBytesArray.length);
    
    for (const entry of sourceMapEntries) {
        addMapping(entry.loc.line, entry.loc.column, entry.relativeOffset);
    }
    
    binary.push(...memorySectionContentBytes);
    setSectionBaseOffset(0);
}