import { createDiagnostic } from "../../diagnostics.mjs";
import { encodeULEB128 } from "../compile-utils.mjs";
import wasmConstants from "../constants.mjs";

const { SECTION } = wasmConstants;

export function startSection(module, functions, binary) {
	// Generated by 🤖
	if (module.start !== null) {
		const startSection = [SECTION.START]; // Section ID (8)

		let startFuncIndex;

		// Resolve the function index - could be numeric or a symbolic name
		if (typeof module.start === "string" && module.start.startsWith("$")) {
			// Look up function index by name
			startFuncIndex = functions.findIndex((f) => f.name === module.start);
			if (startFuncIndex === -1) {
				throw createDiagnostic({
					stage: "compile",
					code: "WAT_UNKNOWN_START",
					message: `Unknown start function: ${module.start}`,
					position: module.position,
				});
			}
		} else {
			// Direct numeric index
			const parsed = Number.parseInt(module.start, 10);
			startFuncIndex = Number.isNaN(parsed) ? 0 : parsed;
		}

		// The start section just contains the function index
		const startEntry = [...encodeULEB128(startFuncIndex)];

		// Set section size
		startSection.push(...encodeULEB128(startEntry.length));

		// Add the function index
		startSection.push(...startEntry);

		// Add start section to binary
		binary.push(...startSection);
	}
}
